{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"EMPLOYEE_MASTER\",\"PR_HEADERS\",\"PR_DETAILS\",\"PO_HEADERS\",\"PO_DETAILS\",\"PR_STATUS\",\"SERVER_NAME\",\"SCHEMA_NAME\",\"DIM_ENTITY\",\"DIM_LEISURE_FACILITY\",\"DIM_DEPARTMENT\",\"DIM_REQUISITION_BU\",\"All Measures\",\"DIM_STATUS\",\"DIM_SOURCE_SYSTEM\",\"DIM_SPEND_CATEGORY\",\"DIM_VOL_VALUE\",\"REQ_LINES\",\"DIM_AGEING_DAYS\",\"DIM_APPROVAL_TIME_CATEGORIES\",\"DIM_OPEX_CAPEX\",\"DIM_SELECTION\",\"DIM_PR_PO_SELECTION\",\"DIM_PR_PROCUREMENT_PROCESS\",\"DIM_EXP_FARAH_SELECTION\",\"PO_STATUS\",\"SUPPLIER_MASTER\",\"DIM_SPEND_RATIO\",\"CONTRACT_EXPIRY_CATEGORY\",\"PBI_PR_CUST_DATE\",\"PBI_PO_CUST_DATE\",\"PBI_CONTRACT_DATE\",\"PR_CURRENT_OWNER\",\"PO_CURRENT_OWNER\",\"DIM_APPROVER_AGEING\",\"DIM_APPROVER_AGEING_PO\",\"AGREEMENT_WITH_PO\",\"DIM_PO_COVERED\",\"DIM_CONTRACT_UPLOAD_AGEING\",\"PO_Historical\",\"DIM_CONTRACT_EXPIRY_ACTION\",\"DIM_BUYER_AGEING\",\"Last Refreshed Date\",\"REQ_DETAILS\",\"REQ_APPROVALS\",\"REQ_AWARD_ALLOCATIONS\",\"SUPPLIER_BUS_CLASSFICATION\",\"SUPPLIER_INITIATIVES\",\"SUPPLIER_QUALIFICATIONS\",\"REQ_PR_LINK\",\"GRN_DETAILS\",\"REQ_HEADERS\",\"PBI_RFP_CUST_DATE\",\"PO_LINES_UNIQUE\",\"DIM_YES_NO\",\"GLOSSARY\",\"SUPPLIER_CATEGORIES\",\"REQ_HEADERS_LATEST_VERSION\",\"DIM_PR_DEPARTMENT\",\"DIM_LICENSES\",\"SUPPLIER_SITE\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.1066.0 (23.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SERVER_NAME",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"proddb_high\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8e2b812b-8b3a-4f8d-8734-7301232be937"
      },
      {
        "name": "SCHEMA_NAME",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"XXPOWERBI\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ac4632d5-120c-4ce3-80e8-d80b99f60120"
      },
      {
        "name": "REQ_HEADERS_LATEST_VERSION",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT #(lf)AUCTION_HEADER_ID,#(lf)DOCUMENT_NUMBER,#(lf)AUCTION_TITLE,#(lf)OPEN_BIDDING_DATE,#(lf)CLOSE_BIDDING_DATE,#(lf)DISPLAY_NAME,#(lf)BU_NAME,#(lf)APPROVAL_AMOUNT,#(lf)ATTRIBUTE_CATEGORY,#(lf)TENDER_CATEGORY,#(lf)DEPARTMENT \"\"NEGOTIATION_TYPE\"\",#(lf)CURRENCY_CODE,#(lf)LAST_RUN_DATE,#(lf)AUCTION_STATUS,#(lf)SCORING_STATUS,#(lf)AWARD_STATUS,#(lf)SEALED_AUCTION_STATUS,#(lf)NEG_APPROVAL_STATUS,#(lf)OUTCOME_STATUS,#(lf)AWARD_APPROVAL_STATUS,#(lf)CREATION_DATE,#(lf)OUTCOME,#(lf)ORIGINAL_CLOSE_BIDDING_DATE,#(lf)ROUND((CLOSE_BIDDING_DATE-ORIGINAL_CLOSE_BIDDING_DATE ),2) \"\"BIDDING_CLOSE_DIFF_DAYS\"\"#(lf)FROM XXMIR_PON_AUCTION_HEADERS_ALL#(lf)#(lf)\"]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AUCTION_HEADER_ID\", type text}, {\"OPEN_BIDDING_DATE\", type date}, {\"CLOSE_BIDDING_DATE\", type date}, {\"LAST_RUN_DATE\", type date},  {\"ORIGINAL_CLOSE_BIDDING_DATE\", type date}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"AUCTION_HEADER_ID\", \"DOCUMENT_NUMBER\", \"BU_NAME\", \"CREATION_DATE\"}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Removed Other Columns\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"BU_NAME\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value1\", each not Text.StartsWith([DOCUMENT_NUMBER], \"30000\")),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows\", each ([BU_NAME] = \"Miral Experiences LLC\")),",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows2\", \"DOCUMENT_NUMBER\", \"BASE_DOCUMENT_NUMBER\"),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Duplicated Column\",\",\",\"-\",Replacer.ReplaceText,{\"BASE_DOCUMENT_NUMBER\"}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Replaced Value\", \"BASE_DOCUMENT_NUMBER\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"BASE_DOCUMENT_NUMBER.1\", \"BASE_DOCUMENT_NUMBER.2\", \"BASE_DOCUMENT_NUMBER.3\", \"BASE_DOCUMENT_NUMBER.4\", \"BASE_DOCUMENT_NUMBER.5\"}),",
          "    #\"Merged Columns\" = Table.CombineColumns(Table.TransformColumnTypes(#\"Split Column by Delimiter\", {{\"BASE_DOCUMENT_NUMBER.3\", type text}}, \"en-US\"),{\"BASE_DOCUMENT_NUMBER.1\", \"BASE_DOCUMENT_NUMBER.2\", \"BASE_DOCUMENT_NUMBER.3\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"BASE_DOCUMENT_NUMBER\"),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Merged Columns\", \"BASE_DOCUMENT_OR_NOT\", each if [BASE_DOCUMENT_NUMBER.4] = null and ",
          "[BASE_DOCUMENT_NUMBER.5]=null  then \"Yes\"",
          "else \"No\"),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"BASE_DOCUMENT_NUMBER.4\", \"BASE_DOCUMENT_NUMBER.5\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"BASE_DOCUMENT_OR_NOT\", type text}}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"DOCUMENT_NUMBER\", Order.Ascending}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Sorted Rows\", {\"BASE_DOCUMENT_NUMBER\"}, {{\"LATEST_CREATION_DATE\", each List.Max([CREATION_DATE]), type nullable datetime}, {\"DOCUMENT_NUMBER\", each List.Max([DOCUMENT_NUMBER]), type nullable text}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "fd8e0ac2-85ce-4fa0-8c5f-255e68233bdf"
      }
    ],
    "relationships": [
      {
        "name": "e5fee5d2-aa00-423f-8d2b-c43e5ceaad98",
        "fromColumn": "REPORTING_ENTITY_ID",
        "fromTable": "DIM_LEISURE_FACILITY",
        "toColumn": "ENTITY_ID",
        "toTable": "DIM_ENTITY"
      },
      {
        "name": "a1918904-b46e-4f07-8b92-ccba0b39ff9a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PR_UNIQUE_KEY",
        "fromTable": "PR_DETAILS",
        "toColumn": "PR_UNIQUE_KEY",
        "toTable": "PR_HEADERS"
      },
      {
        "name": "6712dfff-f3a6-4672-95d7-7a13318a103f",
        "fromColumn": "LEISURE_FACILITY_ID",
        "fromTable": "PR_DETAILS",
        "toColumn": "FACILITY_ID",
        "toTable": "DIM_LEISURE_FACILITY"
      },
      {
        "name": "c3e23755-2406-4356-a040-1551ed6b4309",
        "fromColumn": "DEPARTMENT",
        "fromTable": "PR_DETAILS",
        "toColumn": "DEPARTMENT_ID",
        "toTable": "DIM_DEPARTMENT"
      },
      {
        "name": "f16acac4-d1a4-4a87-b676-dd6e651cfe8d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PO_UNIQUE_KEY",
        "fromTable": "PO_DETAILS",
        "toColumn": "PO_UNIQUE_KEY",
        "toTable": "PO_HEADERS"
      },
      {
        "name": "fa528596-1cf8-47fc-b377-0958c0774473",
        "fromColumn": "STATUS",
        "fromTable": "PR_HEADERS",
        "toColumn": "STATUS",
        "toTable": "DIM_STATUS"
      },
      {
        "name": "7505de64-2d03-46ad-adef-eee5c4f5dacc",
        "fromColumn": "SOURCE_SYSTEM",
        "fromTable": "PR_HEADERS",
        "toColumn": "SOURCE_SYSTEM_NAME",
        "toTable": "DIM_SOURCE_SYSTEM"
      },
      {
        "name": "48967ece-f007-4dc5-a022-85e3f8323759",
        "fromColumn": "PR_SPEND_CATEGORY",
        "fromTable": "PR_HEADERS",
        "toColumn": "SORT_ORDER",
        "toTable": "DIM_SPEND_CATEGORY"
      },
      {
        "name": "d23344cc-465f-485d-b551-df9f34a1fa93",
        "fromColumn": "SPEND_CATEGORY_ID",
        "fromTable": "DIM_AGEING_DAYS",
        "toColumn": "SORT_ORDER",
        "toTable": "DIM_SPEND_CATEGORY"
      },
      {
        "name": "c775aba9-4ce3-495e-a054-e5f836fe5a4d",
        "fromColumn": "PO_APPROVAL_TIME_CATEGORY",
        "fromTable": "PO_HEADERS",
        "toColumn": "APPROVAL_AGEING",
        "toTable": "DIM_APPROVAL_TIME_CATEGORIES"
      },
      {
        "name": "b4d02360-8c9a-456b-b981-17c34e86e7af",
        "fromColumn": "CONTRACT_EXPIRY_CATEGORY",
        "fromTable": "PO_HEADERS",
        "toColumn": "Expiry_Sort_order",
        "toTable": "CONTRACT_EXPIRY_CATEGORY"
      },
      {
        "name": "df9e86ee-ddf5-4518-a6c7-4e3b6cf1e179",
        "fromColumn": "PR_UNIQUE_KEY",
        "fromTable": "PR_CURRENT_OWNER",
        "toColumn": "PR_UNIQUE_KEY",
        "toTable": "PR_HEADERS"
      },
      {
        "name": "405f05d5-fdb1-48c2-ac9a-e35d0a70c99f",
        "fromColumn": "PO_UNIQUE_KEY",
        "fromTable": "PO_CURRENT_OWNER",
        "toColumn": "PO_UNIQUE_KEY",
        "toTable": "PO_HEADERS"
      },
      {
        "name": "8d215d4e-b646-405e-a60c-2661a8874e07",
        "fromColumn": "PO_WITH_CONTRACT_TYPE_COVERED",
        "fromTable": "PO_HEADERS",
        "toColumn": "Sort_order",
        "toTable": "DIM_PO_COVERED"
      },
      {
        "name": "8ad04247-3008-4c96-a361-50c6ca072d34",
        "fromColumn": "ATTRIBUTE5",
        "fromTable": "PO_HEADERS",
        "toColumn": "CONTRACT_EXPIRY_ACTION",
        "toTable": "DIM_CONTRACT_EXPIRY_ACTION"
      },
      {
        "name": "61a4932f-1bd5-40ed-953f-30682f7f67a5",
        "fromColumn": "PR_UNIQUE_KEY",
        "fromTable": "PR_STATUS",
        "toColumn": "PR_UNIQUE_KEY",
        "toTable": "PR_HEADERS"
      },
      {
        "name": "abbbade0-4516-4fe0-886a-2d41b1b59076",
        "fromColumn": "PO_UNIQUE_KEY",
        "fromTable": "PO_STATUS",
        "toColumn": "PO_UNIQUE_KEY",
        "toTable": "PO_HEADERS"
      },
      {
        "name": "3649b455-de7a-45be-b3a6-696cb6bb6d79",
        "fromColumn": "PR_LINE_KEY",
        "fromTable": "PO_DETAILS",
        "toColumn": "PR_LINE_UNIQUE_KEY",
        "toTable": "PR_DETAILS"
      },
      {
        "name": "ec7a9c3d-6c62-4c42-83b7-97fc2e403ab4",
        "fromColumn": "CREATED_DATE",
        "fromTable": "PR_HEADERS",
        "toColumn": "Date",
        "toTable": "DATE_TABLE"
      },
      {
        "name": "9054b601-f044-4f73-a51d-9760a206025d",
        "fromColumn": "AUCTION_HEADER_ID",
        "fromTable": "REQ_DETAILS",
        "toColumn": "AUCTION_HEADER_ID",
        "toTable": "REQ_HEADERS"
      },
      {
        "name": "a7cdb641-8d4e-4d11-9d3c-4871383cca12",
        "fromColumn": "AUCTION_HEADER_ID",
        "fromTable": "REQ_AWARD_ALLOCATIONS",
        "toColumn": "AUCTION_HEADER_ID",
        "toTable": "REQ_HEADERS"
      },
      {
        "name": "45c61b6d-b633-4220-a8b2-921684baf838",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "AUCTION_HEADER_ID",
        "fromTable": "REQ_LINES",
        "toColumn": "AUCTION_HEADER_ID",
        "toTable": "REQ_HEADERS"
      },
      {
        "name": "2d415ce6-1139-4405-86b2-4d8be876a4a9",
        "fromColumn": "CREATION_DATE",
        "fromTable": "REQ_HEADERS",
        "toColumn": "Date",
        "toTable": "DATE_TABLE"
      },
      {
        "name": "4615b797-8500-48b0-8a09-3145c83ef82b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PO_LINE_UNIQUE_KEY",
        "fromTable": "PO_DETAILS",
        "toColumn": "UNIQUE_KEY",
        "toTable": "PO_LINES_UNIQUE"
      },
      {
        "name": "f245afe8-420a-415b-9ced-a9f2f4cfda28",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PO_LINE_UNIQUE_KEY",
        "fromTable": "GRN_DETAILS",
        "toColumn": "UNIQUE_KEY",
        "toTable": "PO_LINES_UNIQUE"
      },
      {
        "name": "48a3f6ad-6da0-4c86-b78a-ab8346030de6",
        "fromColumn": "VENDOR_NUMBER",
        "fromTable": "SUPPLIER_BUS_CLASSFICATION",
        "toColumn": "VENDOR_NUMBER",
        "toTable": "SUPPLIER_MASTER"
      },
      {
        "name": "e7b31d3e-c775-4037-9984-4bb5c35d06ec",
        "fromColumn": "TRADE_LICENSE_EXPIRED_CATEGORY",
        "fromTable": "SUPPLIER_BUS_CLASSFICATION",
        "toColumn": "Expiry_Sort_order",
        "toTable": "CONTRACT_EXPIRY_CATEGORY"
      },
      {
        "name": "ae8f3bb0-ef25-48c0-bfa9-eaa937a5a3e5",
        "fromColumn": "VENDOR_NUMBER",
        "fromTable": "SUPPLIER_INITIATIVES",
        "toColumn": "VENDOR_NUMBER",
        "toTable": "SUPPLIER_MASTER"
      },
      {
        "name": "256a7e48-5c20-4ab9-ab31-898e16853076",
        "fromColumn": "INITIATIVE_UNIQUE_KEY",
        "fromTable": "SUPPLIER_QUALIFICATIONS",
        "toCardinality": "many",
        "toColumn": "INITIATIVE_UNIQUE_KEY",
        "toTable": "SUPPLIER_INITIATIVES"
      },
      {
        "name": "d29c77dc-0937-4d83-9203-c86c547426ee",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "UNIQUE_KEY",
        "fromTable": "SUPPLIER_CATEGORIES",
        "toColumn": "UNIQUE_KEY",
        "toTable": "SUPPLIER_MASTER"
      },
      {
        "name": "68a1cd0e-b312-4370-9fee-5e66567b554b",
        "fromColumn": "CONTRACT_START_DATE",
        "fromTable": "PO_HEADERS",
        "toColumn": "Date",
        "toTable": "CONTRACT_DATE_TABLE"
      },
      {
        "name": "3930d6c0-651a-4b4b-8673-15cd53f108ff",
        "fromColumn": "AGEING_CATEGORY",
        "fromTable": "PR_HEADERS",
        "toColumn": "AGEING_SORT_ORDER",
        "toTable": "DIM_APPROVER_AGEING"
      },
      {
        "name": "aab22c50-0180-442e-9929-8e34db3467ef",
        "fromColumn": "AGEING_CATEGORY",
        "fromTable": "PO_HEADERS",
        "toColumn": "AGEING_SORT_ORDER",
        "toTable": "DIM_APPROVER_AGEING_PO"
      },
      {
        "name": "59ebf87e-c050-44fa-b64d-8a330b05532d",
        "fromColumn": "CERTIFICATION_EXPDATE_MAX",
        "fromTable": "SUPPLIER_BUS_CLASSFICATION",
        "toColumn": "Date",
        "toTable": "SUPPLIER_EXPIRATION_DATE_TABLE"
      },
      {
        "name": "772a8631-1f7a-42d9-8318-fbe8a106b77a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "UNIQUE_KEY",
        "fromTable": "SUPPLIER_SITE",
        "toColumn": "UNIQUE_KEY",
        "toTable": "SUPPLIER_MASTER"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "EMPLOYEE_MASTER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "871ae13f-407f-48fa-b6c2-81451909551c",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "EMPLOYEE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85fc4000-cf60-49a8-9695-bd941ea618e6",
            "sourceColumn": "EMPLOYEE_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "044fd3ba-fb78-4b56-ba20-1d50ce372a12",
            "sourceColumn": "EMP_START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9b33aaf6-f558-4099-8735-12c43b3b942d",
            "sourceColumn": "EMP_END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENT_EMP_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc76e93a-a54d-4f6b-8b9a-51b3b5df9afd",
            "sourceColumn": "CURRENT_EMP_FLAG",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGN_START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "849664a1-f0fe-4285-9380-3ef516b85ab2",
            "sourceColumn": "ASSIGN_START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGN_END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "81a47fb4-75b6-4cd0-81ba-dc102f33bda2",
            "sourceColumn": "ASSIGN_END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9e8065b-d361-46e1-9bd7-9b1ee99dbede",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "EMAIL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ed77b07-7526-499e-a064-3353a50d7516",
            "sourceColumn": "EMAIL",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "758995a2-38ad-42e1-9ff8-6625b64ffa9c",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          },
          {
            "name": "JOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f04d315b-bc8b-44fc-8fe6-6553f8c509bb",
            "sourceColumn": "JOB",
            "summarizeBy": "none"
          },
          {
            "name": "POSITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae9b212b-b562-40b6-a936-b49edc569ba5",
            "sourceColumn": "POSITION",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8fd4d829-b571-4087-99d4-2a29e4bf8001",
            "sourceColumn": "CREATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_MODIFIED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "00b0ab1f-ec70-474f-a37a-be3d923f3104",
            "sourceColumn": "LAST_MODIFIED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c64338e3-800b-4965-8b25-90acc8bdc77a",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f755467-4d3b-40b9-8ff1-87ca0b33d310",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "666b3b1c-cc4e-44ff-ad97-9fd567a697c5",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2166495f-e14d-4a5d-bbb8-9fc9ec0cd4af",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c8d404f-64e7-45c9-9f82-5ebba001d5c5",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bc7a80f-95f6-4406-89ee-bbc5c54f1a8a",
            "sourceColumn": "CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "07213618-82cd-4709-af13-a7ec59a6c214",
            "sourceColumn": "CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_UPDATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c90eea7d-4cb8-4ad3-a6db-da05366db6b6",
            "sourceColumn": "LAST_UPDATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_UPDATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a435fbd1-a6f7-48d4-b80d-9b665a34e815",
            "sourceColumn": "LAST_UPDATE_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_UPDATE_LOGIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42093393-37c7-4982-8b6c-43f69013e18e",
            "sourceColumn": "LAST_UPDATE_LOGIN",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c921f0f6-43fe-4c4c-a80b-111bd0347040",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "RUN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c59bc325-3672-4975-b738-ee7052078b5e",
            "sourceColumn": "RUN_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "DISPLAY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa6eaf47-0391-47b3-a9b8-49c27b17cac3",
            "sourceColumn": "DISPLAY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "EMPLOYEE_DOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7aa1660b-f605-4bd3-b04e-ff7f7baf9c6f",
            "sourceColumn": "EMPLOYEE_DOB",
            "summarizeBy": "none"
          },
          {
            "name": "FIRST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bcd16b1-7e6b-4b41-8c2e-17326156fd79",
            "sourceColumn": "FIRST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f453aac2-9774-4737-8074-e3fe99b075f0",
            "sourceColumn": "LAST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "GRADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edbb02ea-22c4-49d8-b68a-9fa23a8628e5",
            "sourceColumn": "GRADE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fb5262f9-6fcf-4bb8-9c4b-b09a6915a8f4",
        "partitions": [
          {
            "name": "EMPLOYEE_MASTER-727c078d-fe7f-45a2-8877-9009ec0e186d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXFLP_BI_EMPLOYEES_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}, {\"EMP_START_DATE\", type date}, {\"EMP_END_DATE\", type date}, {\"ASSIGN_START_DATE\", type date}}),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Changed Type\", \"DISPLAY_NAME\", each let splitNAME = Splitter.SplitTextByDelimiter(\", \", QuoteStyle.None)([NAME]) in Text.Combine({splitNAME{1}?, \" \", splitNAME{0}?}), type text)",
                "   in",
                "    #\"Added Custom Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PR_HEADERS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "913f592f-401b-4af7-9e5d-67c86d64a7fd",
            "sourceColumn": "PR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "PR_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b2ae497-95e8-42d7-9dca-6e7fa7033ab1",
            "sourceColumn": "PR_DESC",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7899598-0b8e-4517-ab41-b1cc130ea6b9",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b5f5fde-d818-41a1-8213-2afda563e5d8",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_SYSTEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d8db580-74dc-4aab-a2c7-19f8b27b6982",
            "sourceColumn": "SOURCE_SYSTEM",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_PR_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c1abfad-cfb4-4c66-a7a9-b8d942a7c04b",
            "sourceColumn": "SOURCE_PR_NUM",
            "summarizeBy": "none"
          },
          {
            "name": "REJECTION_REASON",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7280b9ad-09cd-43e1-bc5a-ef0ec5770475",
            "sourceColumn": "REJECTION_REASON",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "e3de8a5c-c35e-46e7-8995-ea0582035c70",
            "sourceColumn": "CREATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fa9b9e5-72b0-47bc-80b5-130555cc4642",
            "sourceColumn": "PR_CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "PR_APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "e71069ca-bab0-4b1d-8875-e16c51037da5",
            "sourceColumn": "PR_APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "693a9845-288c-46b8-83e3-c592cdcc3c4e",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5ac2fbf-95b5-4c7c-ad6a-ecbd35f52eb6",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "HEADER_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f8af80ba-dd65-4a09-9f5b-69afc313f2b1",
            "sourceColumn": "HEADER_AMOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "OPEX/CAPEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "272f2110-c2c0-448d-b042-f510ac0c0b95",
            "sourceColumn": "OPEX/CAPEX",
            "summarizeBy": "none"
          },
          {
            "name": "SSJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bec4d16-d3d3-4d83-892b-541a437ac996",
            "sourceColumn": "SSJ",
            "summarizeBy": "none"
          },
          {
            "name": "RFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c265117b-9574-4ef4-a75f-6ed4b5a6d27a",
            "sourceColumn": "RFI",
            "summarizeBy": "none"
          },
          {
            "name": "PR_LINE_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR _PR_UNIQUE_KEY = PR_HEADERS[PR_UNIQUE_KEY]",
              "VAR _APPROVED_PENDING_AMOUNT = CALCULATE (SUM(PR_DETAILS[PR_LINE_AMOUNT]), KEEPFILTERS(FILTER(PR_DETAILS, NOT (PR_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\", \"REJECTED\",  \"RETURNED\", \"SPLIT\", \"WITHDRAWN\" } ))),PR_DETAILS[PR_UNIQUE_KEY]= _PR_UNIQUE_KEY, UPPER(PR_DETAILS[PR_CREATION_TYPE])=\"REAL\")",
              "VAR _OTHER_STATUS = CALCULATE (SUM(PR_DETAILS[PR_LINE_AMOUNT]), KEEPFILTERS(FILTER(PR_DETAILS, NOT (PR_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\" } ))), PR_DETAILS[PR_UNIQUE_KEY]= _PR_UNIQUE_KEY,  UPPER(PR_DETAILS[PR_CREATION_TYPE])=\"REAL\")",
              "RETURN",
              "IF(PR_HEADERS[STATUS] IN {\"APPROVED\", \"PENDING APPROVAL\"}, _APPROVED_PENDING_AMOUNT, _OTHER_STATUS)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "654e3b77-a147-414b-93ca-b5d907094e73",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PR_SPEND_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _PR_VALUE = DIVIDE(PR_HEADERS[PR_LINE_AMOUNT], 1000000, 0)",
              "RETURN",
              "SWITCH(TRUE(),",
              "_PR_VALUE >3, 1, ",
              "AND(_PR_VALUE >1, _PR_VALUE <=3) , 2, ",
              "AND(_PR_VALUE >0.25, _PR_VALUE <=1), 3, ",
              "AND(_PR_VALUE >0.005, _PR_VALUE <=0.25), 4,",
              "_PR_VALUE <=0.005, 5 ",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "afc5a03a-d64b-4cec-a5bc-0631c26898de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_HEADER_CREATION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba0b5d88-f6f3-4961-8e5b-23b180d0ef3e",
            "sourceColumn": "PR_HEADER_CREATION_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_AGEING_DAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(UPPER(PR_HEADERS[STATUS]) = \"PENDING APPROVAL\", DATEDIFF(PR_HEADERS[CREATED_DATE], TODAY(), DAY), BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "53fcf6c3-d956-4dcc-b68a-68c6127ac7bb",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PR_APPROVAL_TIME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _NON_WORKING_DAYS = CALCULATE(COUNT(DATE_TABLE[Date]), FILTER(DATE_TABLE,  DATE_TABLE[Date] IN DATESBETWEEN(DATE_TABLE[Date], PR_HEADERS[CREATED_DATE], PR_HEADERS[PR_APPROVED_DATE]) &&    DATE_TABLE[WEEKDAY] IN {6,7}))",
              "VAR _APPROVAL_TIME = DATEDIFF( PR_HEADERS[CREATED_DATE], PR_HEADERS[PR_APPROVED_DATE], DAY)",
              "RETURN",
              "IF( PR_HEADERS[PR_APPROVED_DATE]<>BLANK(), _APPROVAL_TIME , BLANK())",
              "",
              "// IF( PR_HEADERS[PR_APPROVED_DATE]<>BLANK(), _APPROVAL_TIME-_NON_WORKING_DAYS, BLANK()) -- Requested by Procurement Team to change the logic - 9-Nov-2023",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a04d8a96-58e9-4867-aaa7-16345407b0a0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PR_HEADERS[PR_CREATED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "8d2bc50c-2234-4c22-8c3d-68044f8d0db6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PO_EXIST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _PO_EXIST = CALCULATE(COUNT(PO_HEADERS[PO_UNIQUE_KEY]), FILTER(PO_HEADERS, PO_HEADERS[PR_UNIQUE_KEY]= PR_HEADERS[PR_UNIQUE_KEY]))",
              "VAR _AGEING = NETWORKDAYS(PR_HEADERS[PR_APPROVED_DATE], TODAY(), 1)",
              "RETURN",
              "IF(_PO_EXIST= BLANK() && PR_HEADERS[PR_HEADER_CREATION_TYPE]= \"REAL\" && UPPER(PR_HEADERS[STATUS]) = \"APPROVED\", _AGEING, BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bf58edbd-c305-46b9-a417-74fd60367a96",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "BUYER_AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _AGEING = SWITCH(TRUE(),",
              "PR_HEADERS[PO_EXIST]>=0 &&  PR_HEADERS[PO_EXIST]<=30, \"0 to 30\",",
              "PR_HEADERS[PO_EXIST]>30 && PR_HEADERS[PO_EXIST]<=60, \"31 to 60\",",
              "PR_HEADERS[PO_EXIST]>60, \"60+\",",
              "\"23\"",
              ")",
              "RETURN",
              "IF(PR_HEADERS[PO_EXIST]=BLANK(), BLANK(), _AGEING)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c5fecb29-88d5-41a5-a0cb-7b8676fa6a3d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CURRENT_OWNER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR _CURRENT_OWNER = CALCULATE(MAX(PR_CURRENT_OWNER[CURRENT_ASSIGNEE]), FILTER(PR_CURRENT_OWNER, PR_CURRENT_OWNER[PR_UNIQUE_KEY] = PR_HEADERS[PR_UNIQUE_KEY]))",
              "RETURN",
              "",
              "IF(UPPER(PR_HEADERS[STATUS])=\"PENDING APPROVAL\", IF(_CURRENT_OWNER<>BLANK(), _CURRENT_OWNER, \"NOT ASSIGNED\")  , BLANK())"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "aa928e5e-5d02-41d3-9510-0a3475ce9d7d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_AGEING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _ASSIGNED_DATE = CALCULATE(MAX(PR_CURRENT_OWNER[ASSIGNEDDATE]), FILTER(PR_CURRENT_OWNER, PR_CURRENT_OWNER[PR_UNIQUE_KEY]= PR_HEADERS[PR_UNIQUE_KEY]))",
              "VAR _ASSIGNED_DATE_FROM_HISTORY = CALCULATE(MAX(PR_STATUS[APPROVED_DATE]), FILTER(PR_STATUS, PR_STATUS[PR_UNIQUE_KEY]= PR_HEADERS[PR_UNIQUE_KEY] && PR_STATUS[STATUS]=\"SUBMIT\"))",
              "VAR _UPDATED_ASSIGNED_DATE = SWITCH(TRUE(),",
              "_ASSIGNED_DATE<>BLANK(), _ASSIGNED_DATE,",
              "_ASSIGNED_DATE=BLANK() && _ASSIGNED_DATE_FROM_HISTORY<>BLANK(), _ASSIGNED_DATE_FROM_HISTORY,",
              "_ASSIGNED_DATE=BLANK() && _ASSIGNED_DATE_FROM_HISTORY=BLANK() , PR_HEADERS[CREATED_DATE], ",
              "BLANK()",
              ")",
              "VAR _APPROVAL_TIME =  NETWORKDAYS(_UPDATED_ASSIGNED_DATE, [LAST_REFRESHED_DATE], 1)",
              "VAR _UPDATED_APPROVAL_TIME = IF (_APPROVAL_TIME<=0, 0 , _APPROVAL_TIME)",
              "RETURN",
              "IF(UPPER(PR_HEADERS[STATUS]) = \"PENDING APPROVAL\", _APPROVAL_TIME, BLANK())"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "399cedcd-e2a0-49a8-8726-16010e8d8435",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _AGEING = PR_HEADERS[PR_AGEING]",
              "RETURN",
              "SWITCH(_AGEING<>BLANK(),",
              "_AGEING>=0 && _AGEING<=7, 1,",
              "_AGEING>=8 && _AGEING<=14, 2,",
              "_AGEING>=15 && _AGEING<=30, 3,",
              "_AGEING>=31 && _AGEING<=60, 4,",
              "_AGEING>=61 && _AGEING<=90, 5,",
              "_AGEING>=91, 6,",
              "BLANK()",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0e331216-a009-4f8e-a31a-d79a72fa26c0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a159ab39-6bc4-4d4e-84e6-45ff374d0de6",
        "measures": [
          {
            "name": "Ageing_Days",
            "expression": "Blank()",
            "formatString": "0",
            "lineageTag": "703400f0-b77c-4bdc-9642-0f14f09c2a7c"
          }
        ],
        "partitions": [
          {
            "name": "PR_HEADERS-a85bf467-02c0-47e3-a6fe-14e7d1a5de21",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"---- PR HEADER WITH DUMMY PO, DUMMY REQ -------#(lf)SELECT UNIQUE_KEY \"\"PR_UNIQUE_KEY\"\",#(lf)PR_NUMBER,#(lf)PR_DESC,#(lf)STATUS,#(lf)SOURCE_SYSTEM,#(lf)SOURCE_PR_NUM,#(lf)AMOUNT_AED \"\"HEADER_AMOUNT\"\",#(lf)REJECTION_REASON,#(lf)CREATED_DATE,#(lf)PR_CREATED_BY,#(lf)PR_APPROVED_DATE,#(lf)ATTRIBUTE1 \"\"OPEX/CAPEX\"\",#(lf)ATTRIBUTE3 \"\"SSJ\"\",#(lf)ATTRIBUTE4 \"\"DEPARTMENT\"\",#(lf)ATTRIBUTE5 \"\"RFI\"\",#(lf)SITE,#(lf)'REAL' \"\"PR_HEADER_CREATION_TYPE\"\"#(lf)FROM XXFLP_BI_PR_HEADERS_ALL#(lf)#(lf)UNION#(lf)#(lf)SELECT #(lf)UNIQUE_KEY \"\"PR_UNIQUE_KEY\"\",#(lf)NULL PR_NUMBER,#(lf)NULL PR_DESC,#(lf)CASE WHEN LINE_CLOSE_STATUS IN ('OPEN', 'CLOSED', 'CLOSED FOR INVOICING', 'CLOSED FOR RECEIVING', 'FINALLY CLOSED')   THEN 'APPROVED'#(lf) ELSE LINE_CLOSE_STATUS #(lf)END STATUS,#(lf)PO_ITEM_SOURCE SOURCE_SYSTEM,#(lf)NULL SOURCE_PR_NUM,#(lf)AMOUNT_AED \"\"HEADER_AMOUNT\"\",#(lf)NULL REJECTION_REASON,#(lf)PO_LINE_CREATION_DATE CREATED_DATE,#(lf)NULL PR_CREATED_BY,#(lf)NULL PR_APPROVED_DATE,#(lf)NULL  \"\"OPEX/CAPEX\"\",#(lf)NULL \"\"SSJ\"\",#(lf)NULL \"\"DEPARTMENT\"\",#(lf)NULL \"\"RFI\"\",#(lf)SITE,#(lf)'DUMMY' \"\"PR_HEADER_CREATION_TYPE\"\"#(lf)FROM XXFLP_BI_PO_DETAILS_ALL WHERE PR_LINE_UNIQUE_KEY IS NULL#(lf)#(lf)UNION#(lf)#(lf)SELECT #(lf)AUCTION_HEADER_ID \"\"PR_UNIQUE_KEY\"\",#(lf)NULL PR_NUMBER,#(lf)NULL PR_DESC,#(lf)--CASE WHEN LINE_CLOSE_STATUS IN ('OPEN', 'CLOSED', 'CLOSED FOR INVOICING', 'CLOSED FOR RECEIVING', 'FINALLY CLOSED')   THEN 'APPROVED'#(lf)-- ELSE LINE_CLOSE_STATUS #(lf)--END#(lf)NULL STATUS,#(lf)'ORACLE' SOURCE_SYSTEM,#(lf)NULL SOURCE_PR_NUM,#(lf)NULL \"\"HEADER_AMOUNT\"\",#(lf)NULL REJECTION_REASON,#(lf)NULL CREATED_DATE,#(lf)NULL PR_CREATED_BY,#(lf)NULL PR_APPROVED_DATE,#(lf)NULL  \"\"OPEX/CAPEX\"\",#(lf)NULL \"\"SSJ\"\",#(lf)NULL \"\"DEPARTMENT\"\",#(lf)NULL \"\"RFI\"\",#(lf)BU_NAME SITE ,#(lf)'DUMMY-REQ' \"\"PR_HEADER_CREATION_TYPE\"\"#(lf)FROM XXMIR_PON_AUCTION_LINES_ALL WHERE REQUISITION_NUMBER IS NULL\"]),",
                "    #\"Removed Duplicates\" = Table.Distinct(Source, {\"PR_UNIQUE_KEY\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"PR_UNIQUE_KEY\", type text}, {\"CREATED_DATE\", type date}, {\"PR_APPROVED_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PR_DETAILS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00c94e0a-b3a6-42ae-a201-5848733c558f",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d045edd-36dc-418f-9619-8e8cde25d55d",
            "sourceColumn": "VENDOR_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2557d21-84dd-4238-8e3b-9fe3eebeb6d3",
            "sourceColumn": "ITEM_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_SUB_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2be46b5b-4bb6-4a15-a582-d4604bf4f0af",
            "sourceColumn": "ITEM_SUB_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5f79309-1fc1-4067-a60d-61387e333115",
            "sourceColumn": "SUPPLIER_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e25c9937-5a92-41b6-8d59-322e5c278266",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          },
          {
            "name": "GL_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64fcf60c-c162-4751-aa26-58d3946fbe45",
            "sourceColumn": "GL_ACCOUNT",
            "summarizeBy": "none"
          },
          {
            "name": "LINE_CLOSE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbe46563-c8a2-4096-b478-5d0811be0f0e",
            "sourceColumn": "LINE_CLOSE_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f640ee41-da62-47f2-bdb3-7cf1593959ac",
            "sourceColumn": "ITEM_DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "QUANTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ccc5236c-4299-4178-a7e6-2f83fc3b78b9",
            "sourceColumn": "QUANTITY",
            "summarizeBy": "sum"
          },
          {
            "name": "UNIT_OF_MEASURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2abf33e-c649-46aa-b38a-a838401c71b8",
            "sourceColumn": "UNIT_OF_MEASURE",
            "summarizeBy": "none"
          },
          {
            "name": "UNIT_PRICE_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e59c691d-26e5-4c63-ba6a-3d0a46ebb2a1",
            "sourceColumn": "UNIT_PRICE_AED",
            "summarizeBy": "sum"
          },
          {
            "name": "EXPECTED_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "d72367b3-a645-4b29-8c9e-4b8c6f6430e9",
            "sourceColumn": "EXPECTED_DELIVERY_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPENSE_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea5c37ab-3966-4653-8a5b-ca4feb15b618",
            "sourceColumn": "EXPENSE_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "BUYER_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6f7cdf3-50f2-4e8e-9da4-7d7411528756",
            "sourceColumn": "BUYER_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "PR_LINE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97087348-b3f6-48ce-9b54-728a5cd35acf",
            "sourceColumn": "PR_LINE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "LEISURE_FACILITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c848c3bc-a717-4182-8ae1-2ae1fb8db98f",
            "sourceColumn": "LEISURE_FACILITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PR_LINE_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b8290cae-cf53-4847-965a-133fc4e69cfa",
            "sourceColumn": "PR_LINE_AMOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "PR_LINE_CREATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "3b6100ba-5c06-4952-b553-38fd27bbe5a2",
            "sourceColumn": "PR_LINE_CREATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_HEADER_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(PR_HEADERS[STATUS],PR_HEADERS[PR_UNIQUE_KEY], PR_DETAILS[PR_UNIQUE_KEY])",
            "isDataTypeInferred": true,
            "lineageTag": "ce53fefb-f8c1-473d-af19-6aa06b2e5289",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_LINE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "af67e419-12ce-4f3e-b7ec-77813fe2adf3",
            "sourceColumn": "PR_LINE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_CREATION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa4cd1c-b7af-4819-b7b9-bbd09bf04aad",
            "sourceColumn": "PR_CREATION_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "BUYER_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR _NAME = LOOKUPVALUE(EMPLOYEE_MASTER[NAME],EMPLOYEE_MASTER[EMPLOYEE_NUMBER], PR_DETAILS[BUYER_NUMBER])",
              "RETURN",
              "IF(_NAME=BLANK(), PR_DETAILS[BUYER_NAME_FUSION], _NAME)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "584ab97b-1721-44fb-b25a-2c5d1e45d21a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BUDGETED_PRICE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f10e8ea-454b-4013-bee5-bc2d19e5dd19",
            "sourceColumn": "BUDGETED_PRICE",
            "summarizeBy": "sum"
          },
          {
            "name": "NEGOTIATION_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c2e5612-a942-4e82-ac47-d4bab5f43c3a",
            "sourceColumn": "NEGOTIATION_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "NEGOTIATION_OUTCOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _NEGOTIATION = PR_DETAILS[NEGOTIATION_NUMBER]",
              "RETURN",
              "CALCULATE(MIN(REQ_HEADERS[OUTCOME]), REQ_HEADERS[DOCUMENT_NUMBER] = _NEGOTIATION) "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "219a5518-4349-4ae9-a3c2-14b6e527351e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ee561b0-ee57-43a0-afe5-3ec44c34521a",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_EXIST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _PO_EXIST = CALCULATE(COUNT(PO_DETAILS[PO_UNIQUE_KEY]), FILTER(PO_DETAILS, PO_DETAILS[PR_LINE_UNIQUE_KEY]= PR_DETAILS[PR_LINE_UNIQUE_KEY]))",
              "VAR _APPROVED_DATE = LOOKUPVALUE(PR_HEADERS[PR_APPROVED_DATE], PR_HEADERS[PR_UNIQUE_KEY], PR_DETAILS[PR_UNIQUE_KEY])",
              "VAR _AGEING = NETWORKDAYS(_APPROVED_DATE, TODAY(), 1)",
              "RETURN",
              "IF(_PO_EXIST= BLANK() && PR_DETAILS[PR_CREATION_TYPE]= \"REAL\" && UPPER(PR_DETAILS[PR_HEADER_STATUS]) = \"APPROVED\" && UPPER(PR_DETAILS[LINE_CLOSE_STATUS]) = \"APPROVED\", _AGEING, BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bb4f294a-586c-496c-b2b4-4a881d359791",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "BUYER_AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _AGEING = SWITCH(TRUE(),",
              "PR_DETAILS[PO_EXIST]>=0 &&  PR_DETAILS[PO_EXIST]<=30, \"0 to 30\",",
              "PR_DETAILS[PO_EXIST]>30 && PR_DETAILS[PO_EXIST]<=60, \"31 to 60\",",
              "PR_DETAILS[PO_EXIST]>60, \"60+\",",
              "\"23\"",
              ")",
              "RETURN",
              "IF(PR_DETAILS[PO_EXIST]=BLANK(), BLANK(), _AGEING)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2b98fa7d-e4e2-4e70-ba43-154d6584a875",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BUYER_NAME_FUSION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70002d43-cd97-4908-9c2f-0d66955df0bd",
            "sourceColumn": "BUYER_NAME_FUSION",
            "summarizeBy": "none"
          },
          {
            "name": "NEG_LINE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _PR = CALCULATE(MAX(PR_HEADERS[PR_NUMBER]), FILTER(PR_HEADERS, PR_HEADERS[PR_UNIQUE_KEY]= PR_DETAILS[PR_UNIQUE_KEY]))",
              "VAR _REQ = CALCULATE(MAX(REQ_LINES[DOCUMENT_NUMBER]), FILTER(REQ_LINES, REQ_LINES[REQUISITION_NUMBER]= _PR))",
              "RETURN",
              "_REQ"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2c9fc549-f5ba-4fbe-90ba-42495e4d1f3d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e1e75399-37e6-4fa8-ad4b-b0580adaed08",
        "partitions": [
          {
            "name": "PR_DETAILS-ae7d3b1f-8224-4ef6-bb96-04fdd6e3d52d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"----- PR DETAILS WITH DUMMY PO, DUMMY REQ ------#(lf)SELECT #(lf)UNIQUE_KEY \"\"PR_LINE_UNIQUE_KEY\"\",#(lf)PR_UNIQUE_KEY,#(lf)PR_LINE,#(lf)VENDOR_KEY,#(lf)ITEM_CATEGORY,#(lf)ITEM_SUB_CATEGORY,#(lf)SUPPLIER_CATEGORY,#(lf)DEPARTMENT,#(lf)ENTITY \"\"LEISURE_FACILITY_ID\"\",#(lf)GL_ACCOUNT,#(lf)LINE_CLOSE_STATUS,#(lf)ITEM_DESCRIPTION,#(lf)QUANTITY,#(lf)UNIT_OF_MEASURE,#(lf)UNIT_PRICE_AED,#(lf)AMOUNT_AED \"\"PR_LINE_AMOUNT\"\",#(lf)CREATED_DATE \"\"PR_LINE_CREATED_DATE\"\",#(lf)EXPECTED_DELIVERY_DATE,#(lf)EXPENSE_TYPE,#(lf)BUYER_NUMBER,#(lf)ATTRIBUTE1 \"\"BUYER_NAME_FUSION\"\",#(lf)'REAL' \"\"PR_CREATION_TYPE\"\",#(lf)BUDGETED_PRICE,#(lf)NEGOTIATION_NUMBER,#(lf)SITE#(lf)FROM XXFLP_BI_PR_DETAILS_ALL#(lf)#(lf)UNION#(lf)#(lf)SELECT #(lf)UNIQUE_KEY \"\"PR_LINE_UNIQUE_KEY\"\",#(lf)UNIQUE_KEY PR_UNIQUE_KEY,#(lf)1 \"\"PR_LINE\"\",#(lf)NULL \"\"VENDOR_KEY\"\",#(lf)NULL ITEM_CATEGORY,#(lf)NULL ITEM_SUB_CATEGORY,#(lf)NULL SUPPLIER_CATEGORY,#(lf)null DEPARTMENT,#(lf)CASE WHEN SITE='Farah Experiences LLC' THEN '9999'#(lf)ELSE null#(lf)END \"\"LEISURE_FACILITY_ID\"\",#(lf)null GL_ACCOUNT,#(lf)CASE WHEN LINE_CLOSE_STATUS IN ('OPEN', 'CLOSED', 'CLOSED FOR INVOICING', 'CLOSED FOR RECEIVING', 'FINALLY CLOSED')   THEN 'APPROVED'#(lf) ELSE LINE_CLOSE_STATUS #(lf)END LINE_CLOSE_STATUS,#(lf)NULL ITEM_DESCRIPTION,#(lf)NULL QUANTITY,#(lf)NULL UNIT_OF_MEASURE,#(lf)NULL UNIT_PRICE_AED,#(lf)AMOUNT_AED \"\"PR_LINE_AMOUNT\"\",#(lf)PO_LINE_CREATION_DATE \"\"PR_LINE_CREATED_DATE\"\",#(lf)EXPECTED_DELIVERY_DATE,#(lf)EXPENSE_TYPE,#(lf)NULL BUYER_NUMBER,#(lf)NULL \"\"BUYER_NAME_FUSION\"\",#(lf)'DUMMY' \"\"PR_CREATION_TYPE\"\",#(lf)NULL BUDGETED_PRICE,#(lf)NULL NEGOTIATION_NUMBER,#(lf)SITE#(lf)FROM XXFLP_BI_PO_DETAILS_ALL WHERE PR_LINE_UNIQUE_KEY IS NULL#(lf)#(lf)UNION#(lf)#(lf)SELECT #(lf)AUCTION_HEADER_ID \"\"PR_LINE_UNIQUE_KEY\"\",#(lf)AUCTION_HEADER_ID PR_UNIQUE_KEY,#(lf)1 \"\"PR_LINE\"\",#(lf)NULL \"\"VENDOR_KEY\"\",#(lf)NULL ITEM_CATEGORY,#(lf)NULL ITEM_SUB_CATEGORY,#(lf)NULL SUPPLIER_CATEGORY,#(lf)null DEPARTMENT,#(lf)CASE WHEN BU_NAME='Farah Experiences LLC' THEN '9999'#(lf)ELSE null#(lf)END \"\"LEISURE_FACILITY_ID\"\",#(lf)null GL_ACCOUNT,#(lf)--CASE WHEN LINE_CLOSE_STATUS IN ('OPEN', 'CLOSED', 'CLOSED FOR INVOICING', 'CLOSED FOR RECEIVING', 'FINALLY CLOSED')   THEN 'APPROVED'#(lf)-- ELSE LINE_CLOSE_STATUS #(lf)--END #(lf)NULL LINE_CLOSE_STATUS,#(lf)NULL ITEM_DESCRIPTION,#(lf)NULL QUANTITY,#(lf)NULL UNIT_OF_MEASURE,#(lf)NULL UNIT_PRICE_AED,#(lf)NULL \"\"PR_LINE_AMOUNT\"\",#(lf)NULL \"\"PR_LINE_CREATED_DATE\"\",#(lf)NULL EXPECTED_DELIVERY_DATE,#(lf)NULL EXPENSE_TYPE,#(lf)NULL BUYER_NUMBER,#(lf)NULL \"\"BUYER_NAME_FUSION\"\",#(lf)'DUMMY-REQ' \"\"PR_CREATION_TYPE\"\",#(lf)NULL BUDGETED_PRICE,#(lf)NULL NEGOTIATION_NUMBER,#(lf)BU_NAME \"\"SITE\"\"#(lf)FROM XXMIR_PON_AUCTION_LINES_ALL WHERE REQUISITION_NUMBER IS NULL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PR_LINE_UNIQUE_KEY\", type text}, {\"PR_UNIQUE_KEY\", type text}, {\"VENDOR_KEY\", type text}, {\"PR_LINE_CREATED_DATE\", type date}, {\"EXPECTED_DELIVERY_DATE\", type date}, {\"BUYER_NUMBER\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct( #\"Changed Type\", {\"PR_LINE_UNIQUE_KEY\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_HEADERS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b2da3ba-0af3-42fe-8213-ff2e5dc02e8f",
            "sourceColumn": "PO_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "PO_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb18f019-db35-4316-8c53-345910ea78d1",
            "sourceColumn": "PO_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87b5359d-1e8e-42a4-a191-b5e0f05621cc",
            "sourceColumn": "CURRENCY_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "PAYMENT_TERMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d37fdaa8-c3d5-435d-bd5e-2db18ebc2b3e",
            "sourceColumn": "PAYMENT_TERMS",
            "summarizeBy": "none"
          },
          {
            "name": "PO_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b80d4a8b-8bcf-404f-a38b-794b24289d7d",
            "sourceColumn": "PO_DESC",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a07d9612-72a9-42b2-b250-091721ef298d",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACT_PO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03963b27-9fbe-4000-ade4-3f59a434d42c",
            "sourceColumn": "CONTRACT_PO",
            "summarizeBy": "none"
          },
          {
            "name": "BUYER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ea97986-58bd-45d3-98a2-af18e4455f18",
            "sourceColumn": "BUYER",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "257a78bc-7dcc-4814-ae4f-680b041477dc",
            "sourceColumn": "VENDOR_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "REJECTION_REASON",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b120e52e-9907-4187-88df-a821b5107870",
            "sourceColumn": "REJECTION_REASON",
            "summarizeBy": "none"
          },
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9679aee8-5d5c-4ee3-a9fc-ba84072d43f4",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "6776c0b1-7d3b-4493-867b-dc898817fa6c",
            "sourceColumn": "PO_CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c6fb7f4-de21-4aaa-af7c-697c6d881b97",
            "sourceColumn": "PO_CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "11aaaa22-3682-4ee7-89ec-918368dda68f",
            "sourceColumn": "PO_APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c55da108-2feb-48bb-9462-986727fe4f34",
            "sourceColumn": "SUPPLIER_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67a8b566-a33d-439b-a0e8-a64527ca3042",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACT_END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "4c8ff1f8-3b32-4a80-ad9e-91bf2b3da435",
            "sourceColumn": "CONTRACT_END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d33b0d1f-a4fe-4b1c-ac52-ca21b95cdf59",
            "sourceColumn": "PO_AMOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "PO_SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2769b1ff-7a2f-4f9a-b427-e1b1835b5d4e",
            "sourceColumn": "PO_SITE",
            "summarizeBy": "none"
          },
          {
            "name": "BUYER_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME],EMPLOYEE_MASTER[UNIQUE_KEY], PO_HEADERS[BUYER])",
            "isDataTypeInferred": true,
            "lineageTag": "2b1a9347-2d5b-4c6b-9fb6-0622b62a1088",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "LOOKUPVALUE(PR_HEADERS[PR_APPROVED_DATE],PR_HEADERS[PR_UNIQUE_KEY], PO_HEADERS[PR_UNIQUE_KEY])",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "lineageTag": "b9353533-72e0-4da8-94e0-27a03dced69a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_CONVERSION_TIME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _NON_WORKING_DAYS = CALCULATE(COUNT(DATE_TABLE[Date]), FILTER(DATE_TABLE,  DATE_TABLE[Date] IN DATESBETWEEN(DATE_TABLE[Date], PO_HEADERS[PR_APPROVED_DATE], PO_HEADERS[PO_CREATION_DATE]) &&    DATE_TABLE[WEEKDAY] IN {6,7}))",
              "VAR _APPROVAL_TIME = DATEDIFF(PO_HEADERS[PR_APPROVED_DATE], PO_HEADERS[PO_CREATION_DATE], DAY)",
              "RETURN",
              "//_APPROVAL_TIME",
              "IF(PO_HEADERS[PR_APPROVED_DATE]<>BLANK(),  _APPROVAL_TIME , BLANK())",
              "",
              "// IF(PO_HEADERS[PR_APPROVED_DATE]<>BLANK(),  _APPROVAL_TIME-_NON_WORKING_DAYS, BLANK()) -- Requested by Procurement Team to change the logic - 9-Nov-2023"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "573b018e-8ce5-49e2-868a-d828c74198be",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PO_APPROVAL_TIME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _NON_WORKING_DAYS = CALCULATE(COUNT(DATE_TABLE[Date]), FILTER(DATE_TABLE,  DATE_TABLE[Date] IN DATESBETWEEN(DATE_TABLE[Date], PO_HEADERS[PO_CREATION_DATE], PO_HEADERS[PO_APPROVED_DATE]) &&    DATE_TABLE[WEEKDAY] IN {6,7}))",
              "VAR _APPROVAL_TIME = DATEDIFF( PO_HEADERS[PO_CREATION_DATE], PO_HEADERS[PO_APPROVED_DATE], DAY)",
              "RETURN",
              "IF( PO_HEADERS[PO_APPROVED_DATE]<>BLANK(), _APPROVAL_TIME , BLANK())",
              "",
              "// IF( PO_HEADERS[PO_APPROVED_DATE]<>BLANK(), _APPROVAL_TIME-_NON_WORKING_DAYS, BLANK()) -- Requested by Procurement Team to change the logic - 9-Nov-2023"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9d357fa1-c4bd-4760-8527-b32f1662c8c7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PO_APPROVAL_TIME_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _APPROVAL_TIME = PO_HEADERS[PO_APPROVAL_TIME]",
              "RETURN",
              "SWITCH(TRUE(),",
              "_APPROVAL_TIME>=0 && _APPROVAL_TIME<=3, \"0 to 3\",",
              "_APPROVAL_TIME>=4 && _APPROVAL_TIME<=6, \"4 to 6\",",
              "_APPROVAL_TIME>=7 && _APPROVAL_TIME<=9, \"7 to 9\",",
              "_APPROVAL_TIME>=10 && _APPROVAL_TIME<=12, \"10 to 13\",",
              "_APPROVAL_TIME>=13 , \"13+\",",
              "BLANK()",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "da3ee7ef-6420-4eb8-9017-b75f951bf1b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PO_LINE_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR _PO_UNIQUE_KEY = PO_HEADERS[PO_UNIQUE_KEY]",
              "VAR _APPROVED_PENDING_AMOUNT = CALCULATE (SUM(PO_DETAILS[AMOUNT_AED]), KEEPFILTERS(FILTER(PO_DETAILS, NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\", \"REJECTED\",  \"RETURNED\", \"SPLIT\", \"WITHDRAWN\" } ))),PO_DETAILS[PO_UNIQUE_KEY]= _PO_UNIQUE_KEY)",
              "VAR _OTHER_STATUS = CALCULATE (SUM(PO_DETAILS[AMOUNT_AED]), KEEPFILTERS(FILTER(PO_DETAILS, NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\" } ))), PO_DETAILS[PO_UNIQUE_KEY]= _PO_UNIQUE_KEY)",
              "RETURN",
              "IF(PO_HEADERS[STATUS] IN {\"OPEN\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\", \"FINALLY CLOSED\", \"PENDING ACKNWOLEDGMENT\", \"PENDING APPROVAL\"}, _APPROVED_PENDING_AMOUNT, _OTHER_STATUS)+0"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2ed6545d-fc59-43d6-8b02-be12cddf3c16",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PO_AGEING_DAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _NON_WORKING_DAYS = CALCULATE(COUNT(DATE_TABLE[Date]), FILTER(DATE_TABLE, DATE_TABLE[Date] IN DATESBETWEEN(DATE_TABLE[Date], PO_HEADERS[PO_CREATION_DATE], TODAY()) &&  DATE_TABLE[WEEKDAY] IN {6,7}))",
              "VAR _APPROVAL_TIME =  DATEDIFF(PO_HEADERS[PO_CREATION_DATE], TODAY(), DAY)",
              "RETURN",
              "IF(UPPER(PO_HEADERS[STATUS]) = \"PENDING APPROVAL\", _APPROVAL_TIME , BLANK())",
              "",
              "// IF(UPPER(PO_HEADERS[STATUS]) = \"PENDING APPROVAL\", _APPROVAL_TIME- _NON_WORKING_DAYS, BLANK())  -- Requested by Procurement Team to change the logic - 9-Nov-2023"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e61ccf02-e060-4e61-91e7-1b2741e5625f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VENDOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(SUPPLIER_MASTER[NAME],SUPPLIER_MASTER[UNIQUE_KEY], PO_HEADERS[VENDOR_KEY])",
            "isDataTypeInferred": true,
            "lineageTag": "e1654bc4-4893-49dc-b278-b299bbca7d37",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(PO_HEADERS[PO_SITE]= \"Farah Experiences LLC\", \"Miral Experiences\", PO_HEADERS[PO_SITE])",
            "isDataTypeInferred": true,
            "lineageTag": "c74a09c5-e9cc-4bad-9346-6de7cca8f51c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VENDOR_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(SUPPLIER_MASTER[VENDOR_TYPE],SUPPLIER_MASTER[UNIQUE_KEY], PO_HEADERS[VENDOR_KEY])",
            "isDataTypeInferred": true,
            "lineageTag": "316257e5-278c-4ccd-96ed-a2f57edd3321",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CONTRACT_EXPIRY_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _DIFF = DATEDIFF( [LAST_REFRESHED_DATE], PO_HEADERS[CONTRACT_END_DATE], DAY)",
              "RETURN",
              "IF(PO_HEADERS[PO_TYPE]<> \"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_END_DATE]<>BLANK() , ",
              "",
              "SWITCH(TRUE(),",
              "_DIFF<=0, 1,",
              "_DIFF>0 && _DIFF<=30, 2,",
              "_DIFF>30 && _DIFF<=60, 3,",
              "_DIFF>60 && _DIFF<=90, 4,",
              "_DIFF>90 && _DIFF<=240, 5,",
              "_DIFF>240 && _DIFF<=365, 6,",
              "_DIFF>365, 7",
              "))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0b7c02d8-2399-467d-a8ae-eb3b1146ca72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PO_OR_PO_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a3ac6b6-a18f-4191-8cdd-ede9243493b1",
            "sourceColumn": "PO_OR_PO_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cba4e44-b583-499b-9735-eb9917b9c0e1",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f53e2eb-6a7d-40cb-8897-cc0be602d23a",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "LEGAL_TEAM_MEMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdc2f119-2a55-49f1-bbf5-aded7b78d289",
            "sourceColumn": "LEGAL_TEAM_MEMBER",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7658a40c-c9cd-40ab-aa3a-b3b0e575866b",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACT_START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "27740d3e-483e-4def-962c-89977466badc",
            "sourceColumn": "CONTRACT_START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "298c53df-cff0-4242-b748-30264f1e1699",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          },
          {
            "name": "PO_WITH_CONTRACT_TYPE_COVERED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _PO = PO_HEADERS[PO_NUMBER]",
              "",
              "RETURN",
              "// IF(",
              "// PO_HEADERS[PO_OR_PO_TYPE] IN {\"RFP\", \"SSJ with Contract\", \"RFQ with Contract\"} && UPPER(PO_HEADERS[PO_TYPE]) = \"PURCHASE ORDER\",",
              "// SWITCH(TRUE(),",
              "// CONTAINS(AGREEMENT_WITH_PO,[PO_NUMBER], PO_HEADERS[PO_NUMBER]), 1,",
              "// CONTAINS(AGREEMENT_WITH_PO,[PO_NUMBER], \"Memo\"), 2,",
              "// 3",
              "// ),",
              "// BLANK())",
              "IF(PO_HEADERS[PO_OR_PO_TYPE] IN {\"RFP\", \"SSJ with Contract\", \"RFQ with Contract\"} && UPPER(PO_HEADERS[PO_TYPE]) = \"PURCHASE ORDER\",",
              "    SWITCH(TRUE(),",
              "    CONTAINS(AGREEMENT_WITH_PO,[PO_NUMBER], PO_HEADERS[PO_NUMBER]), 1,",
              "       2 )",
              "    ,",
              "    IF(CONTAINSSTRING(UPPER(PO_HEADERS[PO_OR_PO_TYPE]), \"MEMO\"), 3, BLANK())",
              "",
              "    ) ",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2a84007f-34bd-40e9-9cdf-2739bce37e52",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CONTRACT_UPLOAD_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "CALCULATE(MIN(AGREEMENT_WITH_PO[CONTRACT_UPLOAD_DATE]), FILTER(AGREEMENT_WITH_PO, AGREEMENT_WITH_PO[PO_NUMBER]= PO_HEADERS[PO_NUMBER]))"
            ],
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "lineageTag": "c6b7e7e3-4e5b-4132-af07-6192c25aa8fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CONTRACT_UPLOAD_AGEING_DAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _NON_WORKING_DAYS = CALCULATE(COUNT(DATE_TABLE[Date]), FILTER(DATE_TABLE, DATE_TABLE[Date] IN DATESBETWEEN(DATE_TABLE[Date], PO_HEADERS[PO_APPROVED_DATE], PO_HEADERS[CONTRACT_UPLOAD_DATE]) &&  DATE_TABLE[WEEKDAY] IN {6,7}))",
              "VAR _APPROVAL_TIME =  DATEDIFF(PO_HEADERS[PO_APPROVED_DATE], PO_HEADERS[CONTRACT_UPLOAD_DATE], DAY)",
              "RETURN",
              "IF(UPPER(PO_HEADERS[PO_TYPE]) = \"PURCHASE ORDER\" && UPPER(PO_HEADERS[PO_OR_PO_TYPE]) IN {\"RFP\", \"RFQ WITH CONTRACT\", \"SSJ WITH CONTRACT\"}, _APPROVAL_TIME , BLANK())",
              "",
              "//IF(UPPER(PO_HEADERS[PO_TYPE]) = \"PURCHASE ORDER\" && UPPER(PO_HEADERS[PO_OR_PO_TYPE]) IN {\"RFP\", \"RFQ WITH CONTRACT\", \"SSJ WITH CONTRACT\"}, _APPROVAL_TIME- _NON_WORKING_DAYS, BLANK()) -- Requested by Procurement Team to change the logic - 9-Nov-2023"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2fb85ff2-6721-43f9-ac6b-3fcc7bf1cdd7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PO_DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CALCULATE(MAX(PO_DETAILS[DEPARTMENT]), PO_DETAILS[PO_UNIQUE_KEY] IN VALUES(PO_HEADERS[PO_UNIQUE_KEY]))",
            "isDataTypeInferred": true,
            "lineageTag": "6dfe3cb0-af8f-4a57-b4e8-6efe06d4994c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "BLANK()",
              "//LOOKUPVALUE(PR_HEADERS[PR_NUMBER], PR_HEADERS[PR_UNIQUE_KEY], PO_HEADERS[PR_UNIQUE_KEY])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "187fe858-c450-4b03-9fe2-361f1c531a05",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "SSJ_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(PO_HEADERS[PO_OR_PO_TYPE] IN {\"SSJ WITH CONTRACT\", \"SSJ WITHOUT CONTRACT\"}, \"Yes\", \"No\")",
            "isDataTypeInferred": true,
            "lineageTag": "6434e4db-255d-45f7-865d-77b9ec36549e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CONTRACT_EXPIRATION_STATUS_UPDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "673d5270-a88d-49b2-88fb-3ed0257af3b3",
            "sourceColumn": "CONTRACT_EXPIRATION_STATUS_UPDATE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_AGEING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _ASSIGNED_DATE = CALCULATE(MAX(PO_CURRENT_OWNER[ASSIGNEDDATE]), FILTER(PO_CURRENT_OWNER, PO_CURRENT_OWNER[PO_UNIQUE_KEY]= PO_HEADERS[PO_UNIQUE_KEY]))",
              "VAR _ASSIGNED_DATE_FROM_HISTORY = CALCULATE(MAX(PO_STATUS[APPROVED_DATE]), FILTER(PO_STATUS, PO_STATUS[PO_UNIQUE_KEY]= PO_HEADERS[PO_UNIQUE_KEY] && PO_STATUS[STATUS]=\"SUBMIT\"))",
              "VAR _UPDATED_ASSIGNED_DATE = SWITCH(TRUE(),",
              "_ASSIGNED_DATE<>BLANK(), _ASSIGNED_DATE,",
              "_ASSIGNED_DATE=BLANK() && _ASSIGNED_DATE_FROM_HISTORY<>BLANK(), _ASSIGNED_DATE_FROM_HISTORY,",
              "_ASSIGNED_DATE=BLANK() && _ASSIGNED_DATE_FROM_HISTORY=BLANK() , PO_HEADERS[PO_CREATION_DATE], ",
              "BLANK()",
              ")",
              "VAR _APPROVAL_TIME =  NETWORKDAYS(_UPDATED_ASSIGNED_DATE, [LAST_REFRESHED_DATE], 1)",
              "VAR _UPDATED_APPROVAL_TIME = IF (_APPROVAL_TIME<=0, 0 , _APPROVAL_TIME)",
              "RETURN",
              "IF(UPPER(PO_HEADERS[STATUS]) = \"PENDING APPROVAL\", _APPROVAL_TIME, BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8c587fa8-b2f5-4abd-93f0-3dfcb306eea5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _AGEING = PO_HEADERS[PO_AGEING]",
              "RETURN",
              "SWITCH(_AGEING<>BLANK(),",
              "_AGEING>=0 && _AGEING<=7, 1,",
              "_AGEING>=8 && _AGEING<=14, 2,",
              "_AGEING>=15 && _AGEING<=30, 3,",
              "_AGEING>=31 && _AGEING<=60, 4,",
              "_AGEING>=61 && _AGEING<=90, 5,",
              "_AGEING>=91, 6,",
              "BLANK()",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d4b3ce66-71ba-46f8-ab5f-3ae06ccc4e19",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CURRENT_OWNER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR _CURRENT_OWNER = CALCULATE(MAX(PO_CURRENT_OWNER[CURRENT_ASSIGNEE]), FILTER(PO_CURRENT_OWNER, PO_CURRENT_OWNER[PO_UNIQUE_KEY] = PO_HEADERS[PO_UNIQUE_KEY]))",
              "RETURN",
              "",
              "IF(UPPER(PO_HEADERS[STATUS])=\"PENDING APPROVAL\", IF(_CURRENT_OWNER<>BLANK(), _CURRENT_OWNER, \"NOT ASSIGNED\")  , BLANK())"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e8a1dc40-fa1e-4bdf-b92d-aeb09fa53048",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "bf5f00eb-d342-4674-bb28-f79f2d8ebea7",
        "partitions": [
          {
            "name": "PO_HEADERS-1a85821e-6da6-4ac9-ada9-fc538070cd4b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT #(lf)UNIQUE_KEY \"\"PO_UNIQUE_KEY\"\",#(lf)PO_NUMBER,#(lf)PO_TYPE,#(lf)CURRENCY_CODE,#(lf)PAYMENT_TERMS,#(lf)PO_DESC,#(lf)STATUS,#(lf)CONTRACT_PO,#(lf)SUPPLIER_CATEGORY,#(lf)SUPPLIER_SUB_CATEGORY \"\"CONTRACT_END_DATE\"\",#(lf)BUYER,#(lf)VENDOR_KEY,#(lf)AMOUNT_AED \"\"PO_AMOUNT\"\",#(lf)REJECTION_REASON,#(lf)PR_UNIQUE_KEY,#(lf)PO_CREATION_DATE,#(lf)PO_CREATED_BY,#(lf)PO_APPROVED_DATE,#(lf)ATTRIBUTE1 \"\"PO_OR_PO_TYPE\"\",#(lf)ATTRIBUTE2,#(lf)ATTRIBUTE3,#(lf)CASE WHEN UPPER(ATTRIBUTE4) IN ('YES', 'NO', 'NA') THEN 'Not Applicable'#(lf)ELSE ATTRIBUTE4#(lf)END#(lf)\"\"LEGAL_TEAM_MEMBER\"\",#(lf)ATTRIBUTE5,#(lf)SITE \"\"PO_SITE\"\",#(lf)FACILITY_KEY \"\"CONTRACT_START_DATE\"\", #(lf)DEPARTMENT,#(lf)CONTRACT_EXPI_STS_UPD \"\"CONTRACT_EXPIRATION_STATUS_UPDATE\"\"#(lf)FROM XXFLP_BI_PO_HEADERS_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PO_UNIQUE_KEY\", type text}, {\"VENDOR_KEY\", type text}, {\"PO_CREATION_DATE\", type date}, {\"PO_APPROVED_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_DETAILS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd94d029-0e81-4b6e-8ee6-210051c75733",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PR_HEADER_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "927ef8e1-a985-4444-8b63-6363ecba1c1f",
            "sourceColumn": "PR_HEADER_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PR_LINE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33e82e7d-46d8-4e8d-9cc5-50b873c7ad48",
            "sourceColumn": "PR_LINE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_LINE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95fe3d61-a482-44f1-bbb6-54f918e629ae",
            "sourceColumn": "PO_LINE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_LINE_QTY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d7888042-850f-4681-a033-4cb018da7826",
            "sourceColumn": "PO_LINE_QTY",
            "summarizeBy": "sum"
          },
          {
            "name": "UNIT_OF_MEASURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b7996e6-c35c-49d5-885b-178f32fa1f34",
            "sourceColumn": "UNIT_OF_MEASURE",
            "summarizeBy": "none"
          },
          {
            "name": "PO_SHIPMENT_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cc49814-364b-41df-abf4-a06647ca5f72",
            "sourceColumn": "PO_SHIPMENT_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_DISTRIBUTION_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "938573b0-d144-47de-b1c8-95ce6c99da60",
            "sourceColumn": "PO_DISTRIBUTION_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PR_DISTRIBUTION_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c815aaee-a8e6-4c10-a8db-27b5873fcb46",
            "sourceColumn": "PR_DISTRIBUTION_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "RELEASE_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b65e937-2f69-40f6-af25-7c81e9dd3886",
            "sourceColumn": "RELEASE_NUM",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f96f0389-f73e-424d-a206-caff29ebc390",
            "sourceColumn": "ITEM_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_SUB_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b5d178d-e4aa-4f5c-9098-d69ec9baaaea",
            "sourceColumn": "ITEM_SUB_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "855c9eb4-fef8-47a8-bb44-4c2b6c02b47e",
            "sourceColumn": "ENTITY",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d3785c7-3a14-4b07-9a1b-26276d51baba",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          },
          {
            "name": "GL_ACCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ddd015-3aea-4075-9b7f-d56c11523850",
            "sourceColumn": "GL_ACCOUNT",
            "summarizeBy": "none"
          },
          {
            "name": "LINE_CLOSE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6ac9a0e-8d6f-474b-867b-1c2948df0c48",
            "sourceColumn": "LINE_CLOSE_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "PO_RELEASE_HEADER_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d30efa7-ae25-4026-bf5a-3c698c310ee8",
            "sourceColumn": "PO_RELEASE_HEADER_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "PO_ITEM_ORACLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "925ca489-cb7e-4451-9218-db401574c0c0",
            "sourceColumn": "PO_ITEM_ORACLE",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70569765-7101-431e-82df-113dc93799df",
            "sourceColumn": "ITEM_DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "PO_ITEM_SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d760076-8b8a-4a84-b6a3-dd9aa3af8ba2",
            "sourceColumn": "PO_ITEM_SOURCE",
            "summarizeBy": "none"
          },
          {
            "name": "UNIT_PRICE_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d07d1010-4a20-4e00-9848-4d83aeb2a49e",
            "sourceColumn": "UNIT_PRICE_AED",
            "summarizeBy": "sum"
          },
          {
            "name": "AMOUNT_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "386aff71-4d24-43db-9936-a852608747f5",
            "sourceColumn": "AMOUNT_AED",
            "summarizeBy": "sum"
          },
          {
            "name": "PO_LINE_CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "983b394b-85a4-4b70-bab5-59295dd1cbb6",
            "sourceColumn": "PO_LINE_CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPECTED_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "8f087c10-e39b-4d19-9471-8224c7be8ff9",
            "sourceColumn": "EXPECTED_DELIVERY_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACTUAL_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "2dfa94fd-b086-4115-b626-803c43f39942",
            "sourceColumn": "CONTRACTUAL_DELIVERY_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ACTUAL_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5625efb1-e78e-4ef7-9089-20f833887d44",
            "sourceColumn": "ACTUAL_DELIVERY_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPENSE_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b95f245-02a9-4d7c-8acd-3d2a1e142eaa",
            "sourceColumn": "EXPENSE_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5c52a8d-36e4-4670-a3fc-72cf708b7a58",
            "sourceColumn": "GRN_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "664c2c6a-10aa-4c16-8cec-5a2cf6444b33",
            "sourceColumn": "CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_RELEASE_BUYER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9b6cdfc-ea84-41a7-8256-cb0aaeb0040f",
            "sourceColumn": "PO_RELEASE_BUYER",
            "summarizeBy": "none"
          },
          {
            "name": "PO_LINE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6da91666-c9bc-4146-bf27-a2324e2f02ee",
            "sourceColumn": "PO_LINE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_LINE_SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ab65a1d-2036-40ab-96c9-06c4e6d80b62",
            "sourceColumn": "PO_LINE_SITE",
            "summarizeBy": "none"
          },
          {
            "name": "PR_BUDGET_AVAILABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR _PR_LINE_KEY = PO_DETAILS[PR_LINE_UNIQUE_KEY]",
              "VAR _EXCLUDE_STATUS = {\"CANCELED\", \"WITHDRAWN\", \"REJECTED\"}",
              "VAR _PR_BUDGET = CALCULATE(MIN(PR_DETAILS[BUDGETED_PRICE]), PR_DETAILS[PR_LINE_UNIQUE_KEY]=_PR_LINE_KEY,PR_DETAILS[LINE_CLOSE_STATUS]= \"APPROVED\")",
              "VAR _PO_PRICE = PO_DETAILS[UNIT_PRICE_AED]",
              "VAR _PO_AMOUNT = PO_DETAILS[AMOUNT_AED]",
              "VAR _PO_LINE_KEY = CALCULATE(COUNT(PO_DETAILS[PO_LINE_UNIQUE_KEY]), ALL(PO_DETAILS),PO_DETAILS[PR_LINE_UNIQUE_KEY]= _PR_LINE_KEY,PO_DETAILS[PR_LINE_UNIQUE_KEY]<>BLANK(), NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN _EXCLUDE_STATUS))",
              "VAR _PO_TOTAL_QUANTITY = CALCULATE(SUM(PO_DETAILS[PO_LINE_QTY]), ALL(PO_DETAILS),PO_DETAILS[PR_LINE_UNIQUE_KEY]= _PR_LINE_KEY,PO_DETAILS[PR_LINE_UNIQUE_KEY]<>BLANK(), NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN _EXCLUDE_STATUS))",
              "VAR _PO_LINE_QTY = PO_DETAILS[PO_LINE_QTY]",
              "VAR _BUDGET_MISSING_FLAG = IF(_PR_BUDGET+0=0, 1, 0)",
              "VAR _SHARED_PR_LINE = IF(_PO_LINE_KEY>1, 1, 2)",
              "VAR _ITEM_CATEGORY = PO_DETAILS[ITEM_CATEGORY]",
              "VAR _ITEM_SUBCATEGORY = PO_DETAILS[ITEM_SUB_CATEGORY]",
              "VAR ITEM_MAX_DATE = CALCULATE(MAX(PO_DETAILS[PO_LINE_CREATION_DATE]), ALL(PO_DETAILS),PO_DETAILS[PO_LINE_UNIQUE_KEY]<> _PO_LINE_KEY, NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN _EXCLUDE_STATUS),PO_DETAILS[ITEM_CATEGORY] = _ITEM_CATEGORY,PO_DETAILS[ITEM_SUB_CATEGORY] = _ITEM_SUBCATEGORY )",
              "//VAR _ITEM_PREV_PRICE = CALCULATE(MIN(PO_DETAILS[UNIT_PRICE_AED]), ALL(PO_DETAILS), PO_DETAILS[PO_LINE_UNIQUE_KEY]<> _PO_LINE_KEY, NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN _EXCLUDE_STATUS), PO_DETAILS[PO_LINE_CREATION_DATE] =  ITEM_MAX_DATE)",
              "RETURN",
              "//IF(_PR_BUDGET_FLAG+0<>0, 0, 1)",
              "//ITEM_MAX_DATE",
              "SWITCH(TRUE(),",
              "_BUDGET_MISSING_FLAG =1, BLANK(),",
              "_BUDGET_MISSING_FLAG=0 && NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN _EXCLUDE_STATUS) , (_PR_BUDGET - _PO_PRICE ) * _PO_LINE_QTY,",
              "//_BUDGET_MISSING_FLAG=0 && _SHARED_PR_LINE = 1, (_PR_BUDGET * _PO_LINE_QTY/ _PO_TOTAL_QUANTITY) * _PO_LINE_QTY,",
              "//_BUDGET_MISSING_FLAG=0,  ((_ITEM_PREV_PRICE ) * _PO_LINE_QTY) - _PO_AMOUNT,",
              "BLANK()",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f695738e-1d4f-4ae4-9a1a-162e3f5caf4e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PR_BUDGET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _PR_LINE_KEY = PO_DETAILS[PR_LINE_UNIQUE_KEY]",
              "VAR _PR_BUDGET = CALCULATE(SUM(PR_DETAILS[BUDGETED_PRICE]), PR_DETAILS[PR_LINE_UNIQUE_KEY]=_PR_LINE_KEY,PR_DETAILS[LINE_CLOSE_STATUS]= \"APPROVED\")",
              "VAR _PO_AMOUNT = PO_DETAILS[AMOUNT_AED]",
              "VAR _PO_LINE_KEY = CALCULATE(COUNT(PO_DETAILS[PO_LINE_UNIQUE_KEY]), ALL(PO_DETAILS),PO_DETAILS[PR_LINE_UNIQUE_KEY]= _PR_LINE_KEY,PO_DETAILS[PR_LINE_UNIQUE_KEY]<>BLANK(), NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"WITHDRAWN\", \"REJECTED\"}))",
              "VAR _PO_TOTAL_QUANTITY = CALCULATE(SUM(PO_DETAILS[PO_LINE_QTY]), ALL(PO_DETAILS),PO_DETAILS[PR_LINE_UNIQUE_KEY]= _PR_LINE_KEY,PO_DETAILS[PR_LINE_UNIQUE_KEY]<>BLANK(), NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"WITHDRAWN\", \"REJECTED\"}))",
              "VAR _PO_LINE_QTY = PO_DETAILS[PO_LINE_QTY]",
              "VAR _BUDGET_MISSING_FLAG = IF(_PR_BUDGET+0=0, 1, 0)",
              "VAR _SHARED_PR_LINE = IF(_PO_LINE_KEY>1, 1, 0)",
              "RETURN",
              "//IF(_PR_BUDGET_FLAG+0<>0, 0, 1)",
              "_PR_BUDGET & \"_\" & _BUDGET_MISSING_FLAG & \"_\"&_SHARED_PR_LINE"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c8c049f1-533d-4f1b-8fd7-3bbdbf870723",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_LINE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF (PO_DETAILS[PR_LINE_UNIQUE_KEY]=BLANK(), PO_DETAILS[PO_LINE_UNIQUE_KEY], PO_DETAILS[PR_LINE_UNIQUE_KEY])",
            "isDataTypeInferred": true,
            "lineageTag": "bba0a30a-37f3-4251-b841-6fd6f7341d7f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PO_PRODUCT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa7d7d3d-ede7-4fca-b6f1-28d9259d90ed",
            "sourceColumn": "PO_PRODUCT_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "VAR _GRN = CALCULATE(MAX(GRN_DETAILS[GRN_DATE]), FILTER(GRN_DETAILS, GRN_DETAILS[PO_LINE_UNIQUE_KEY]= PO_DETAILS[PO_LINE_UNIQUE_KEY]))",
              "VAR _FINAL_GRN = IF(_GRN= BLANK() && PO_DETAILS[CONTRACTUAL_DELIVERY_DATE]<>BLANK(), PO_DETAILS[CONTRACTUAL_DELIVERY_DATE], _GRN)",
              "RETURN",
              "_FINAL_GRN"
            ],
            "formatString": "dd-Mmm-YY",
            "isDataTypeInferred": true,
            "lineageTag": "fbb47bd7-07bd-44b7-9f53-649baff070c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SUPPLIER_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7002be1-659f-4e01-acc1-1a566d64ca3c",
            "sourceColumn": "SUPPLIER_NAME",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "294f4dca-aa9c-4060-985f-7d4e18a41992",
        "partitions": [
          {
            "name": "PO_DETAILS-517cd6a4-91fb-4928-86d3-58682b01eaca",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT #(lf)A.UNIQUE_KEY \"\"PO_LINE_UNIQUE_KEY\"\",#(lf)A.PO_UNIQUE_KEY,#(lf)A.PR_HEADER_UNIQUE_KEY,#(lf)A.PR_LINE_UNIQUE_KEY,#(lf)A.PO_LINE,#(lf)A.PO_LINE_QTY,#(lf)A.UNIT_OF_MEASURE,#(lf)A.PO_SHIPMENT_UNIQUE_KEY,#(lf)A.PO_DISTRIBUTION_UNIQUE_KEY,#(lf)A.PR_DISTRIBUTION_UNIQUE_KEY,#(lf)A.RELEASE_NUM,#(lf)A.ITEM_CATEGORY,#(lf)A.ITEM_SUB_CATEGORY,#(lf)A.ENTITY,#(lf)A.DEPARTMENT,#(lf)A.GL_ACCOUNT,#(lf)A.LINE_CLOSE_STATUS,#(lf)A.PO_RELEASE_HEADER_STATUS,#(lf)A.PO_ITEM_ORACLE,#(lf)A.ITEM_DESCRIPTION,#(lf)A.PO_ITEM_SOURCE,#(lf)A.UNIT_PRICE_AED,#(lf)A.AMOUNT_AED,#(lf)A.PO_LINE_CREATION_DATE,#(lf)A.EXPECTED_DELIVERY_DATE,#(lf)A.CONTRACTUAL_DELIVERY_DATE,#(lf)A.ACTUAL_DELIVERY_DATE,#(lf)A.EXPENSE_TYPE,#(lf)A.GRN_KEY,#(lf)A.CREATED_BY,#(lf)A.SITE \"\"PO_LINE_SITE\"\",#(lf)A.PO_RELEASE_BUYER,#(lf)A.ATTRIBUTE1 \"\"PO_PRODUCT_TYPE\"\",#(lf)C.NAME \"\"SUPPLIER_NAME\"\"#(lf)FROM XXFLP_BI_PO_DETAILS_ALL A#(lf)LEFT OUTER JOIN XXFLP_BI_PO_HEADERS_ALL B#(lf)ON A.PO_UNIQUE_KEY = B.UNIQUE_KEY#(lf)LEFT OUTER JOIN XXFLP_BI_SUPPLIERS_ALL C#(lf)ON B.VENDOR_KEY = C.UNIQUE_KEY\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PO_LINE_UNIQUE_KEY\", type text}, {\"PO_UNIQUE_KEY\", type text}, {\"PR_HEADER_UNIQUE_KEY\", type text}, {\"PR_LINE_UNIQUE_KEY\", type text}, {\"PO_LINE\", type text}, {\"PO_SHIPMENT_UNIQUE_KEY\", type text}, {\"PO_DISTRIBUTION_UNIQUE_KEY\", type text}, {\"PR_DISTRIBUTION_UNIQUE_KEY\", type text}, {\"PO_LINE_CREATION_DATE\", type date}, {\"EXPECTED_DELIVERY_DATE\", type date}, {\"CONTRACTUAL_DELIVERY_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PR_STATUS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a71ee4c3-59c1-4030-ab61-5c4a299f3f1a",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d4a79aa-7afa-4e9e-806a-fbc5c29fd180",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_DATETIME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "9a9adf21-0295-4db3-8477-22de728e66ef",
            "sourceColumn": "CREATED_DATETIME",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e98c89d5-682f-4091-973b-296e0f6bd71d",
            "sourceColumn": "ACTION_CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_PERFORMED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5700587-dd3c-4dde-ac2f-3ac83ee95523",
            "sourceColumn": "ACTION_PERFORMED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f99c2bb5-2663-4edf-b7c0-7fbd40c7e6c1",
            "sourceColumn": "UPDATED_BY",
            "summarizeBy": "sum"
          },
          {
            "name": "UPDATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "2501cf34-0830-46fc-ab8f-cacdae080292",
            "sourceColumn": "UPDATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_SEQUENCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dfc33c75-ae33-432d-b071-6c40afefa686",
            "sourceColumn": "ACTION_SEQUENCE",
            "summarizeBy": "sum"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c174e9a9-0cb7-4f4f-a3e1-a741b2f49909",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "4ba2cf0d-30ef-45be-9da4-bb7b341bc0f7",
            "sourceColumn": "APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c687d6d7-94e8-4825-adc0-fbf65927183e",
            "sourceColumn": "APPROVED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94731658-83bd-4b43-83cd-e728bf30f9f1",
            "sourceColumn": "ROLE",
            "summarizeBy": "none"
          },
          {
            "name": "COMMENTS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c5ddccc-19b9-4184-881c-76ec4c7e8bb9",
            "sourceColumn": "COMMENTS",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2092eda8-c539-49e2-8a1b-8a4b3021ead8",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a149b9e-50bf-4603-9411-2c29a0f493f1",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "373f0ed6-5eea-4101-941d-0dae8c610054",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c88be6c9-96de-4d7f-b517-a3684f7b5e86",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1012597d-99df-4df6-be71-11d6feae471b",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "961a0c32-3139-416b-afdb-c80f1d9c8502",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_CREATED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PR_STATUS[ACTION_CREATED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "92b3e2ce-5ff9-4d12-87ea-49d2bfa24c6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ACTION_PERFORMED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PR_STATUS[ACTION_PERFORMED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "981090db-1249-421e-bcb3-bbc92e3fc82c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ACTION_APPROVED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PR_STATUS[APPROVED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "8ecc3181-c44a-499a-a69c-555d27a53a1c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e1a98900-f611-4021-bfd8-d3e801bf22b4",
        "partitions": [
          {
            "name": "PR_STATUS-f2ecf8e7-70dd-4310-8339-4079674d5e1d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT #(lf)UNIQUE_KEY,#(lf)PR_UNIQUE_KEY,#(lf)CREATED_DATETIME,#(lf)ACTION_CREATED_BY,#(lf)ACTION_PERFORMED_BY,#(lf)UPDATED_BY,#(lf)UPDATED_DATE,#(lf)ACTION_SEQUENCE,#(lf)STATUS,#(lf)APPROVED_DATE,#(lf)APPROVED_BY,#(lf)ROLE,#(lf)COMMENTS,#(lf)ATTRIBUTE1,#(lf)ATTRIBUTE2,#(lf)ATTRIBUTE3,#(lf)ATTRIBUTE4,#(lf)ATTRIBUTE5,#(lf)SITE#(lf)FROM XXFLP_BI_PR_STATUS_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}, {\"PR_UNIQUE_KEY\", type text}, {\"CREATED_DATETIME\", type text}, {\"ACTION_CREATED_BY\", type text}, {\"ACTION_PERFORMED_BY\", type text}, {\"UPDATED_BY\", Int64.Type}, {\"UPDATED_DATE\", type text}, {\"ACTION_SEQUENCE\", Int64.Type}, {\"STATUS\", type text}, {\"APPROVED_DATE\", type text}, {\"APPROVED_BY\", type text}, {\"ROLE\", type text}, {\"COMMENTS\", type text}, {\"ATTRIBUTE1\", type text}, {\"ATTRIBUTE2\", type text}, {\"ATTRIBUTE3\", type text}, {\"ATTRIBUTE4\", type text}, {\"ATTRIBUTE5\", type text}, {\"SITE\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DATE_TABLE",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d4b6ce3318b444db869dd8de43be5906"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "55b2368f-56aa-4cc2-b2e0-74780a7d2fa1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5725f88a-c970-46b0-890d-17f74f09952e",
            "sourceColumn": "[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5258d7d1-fcb6-4323-a7bb-77cb99b06304",
            "sortByColumn": "Month NO",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month NO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "868095e1-6011-49b3-b198-cad2f74abf05",
            "sourceColumn": "[Month NO]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ShortMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cc056d8e-794e-41ed-bba5-23e1bcce781e",
            "sortByColumn": "Month NO",
            "sourceColumn": "[ShortMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f6f29635-9d63-42ea-8221-f01c3c68a398",
            "sortByColumn": "YearMonthNum",
            "sourceColumn": "[Year-Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "HY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "19ea7aba-3c4a-4440-9e2a-df901e1af5a9",
            "sourceColumn": "[HY]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "23d2efef-5429-4668-97eb-91152e3c6c22",
            "sourceColumn": "[YearMonthNum]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WEEKDAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8f4cd8d3-71e5-4a50-8145-6230f1ff92a4",
            "sourceColumn": "[WEEKDAY]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "5794854c-588a-47fe-be82-51510e1c483d",
        "partitions": [
          {
            "name": "DATE_TABLE-e3bfe495-881b-4ff3-ad09-44ca515e0dcf",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _MIN_DATE= DATE(2021, 1, 1)",
                "VAR _MAX_DATE= TODAY()",
                "RETURN",
                "ADDCOLUMNS( ",
                "CALENDAR(_MIN_DATE,_MAX_DATE),",
                "\"Year\",YEAR([Date]),",
                "\"Month\",FORMAT([Date],\"MMMM\"),",
                "\"Month NO\",MONTH([Date]),",
                "\"ShortMonth\",FORMAT([Date],\"MMM\"),",
                "\"Year-Month\",FORMAT([Date],\"MMM\") & \"-\" & FORMAT([Date],\"YY\"),",
                "\"YearMonthNum\",  INT(FORMAT([Date],\"YY\") & FORMAT([Date],\"MM\")) ,",
                "\"HY\",ROUNDUP(DIVIDE(MONTH([Date]),6),0),",
                "\"WEEKDAY\", WEEKDAY([Date], 2)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DIM_ENTITY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ENTITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72a04904-c72b-4e3e-8b91-a15a23998abb",
            "sourceColumn": "ENTITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "REPORTING_ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "819c9183-44eb-4bb3-937d-c1da1088a6da",
            "sourceColumn": "REPORTING_ENTITY",
            "summarizeBy": "none"
          },
          {
            "name": "ENTITY_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d05bd29-af39-4ef8-a6ba-d23d9f076760",
            "sourceColumn": "ENTITY_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dcd61889-bf2c-4e88-a073-d63020857bf3",
        "partitions": [
          {
            "name": "DIM_ENTITY-cf7aaaa3-a823-49b1-b7c9-4e0f6f75bbe5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM DIM_ENTITY\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_LEISURE_FACILITY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FACILITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeb557ff-8935-421e-87ae-37a848666109",
            "sourceColumn": "FACILITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "LEISURE_FACILITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "006d01c1-e265-4a54-bbf3-c9354ffd346a",
            "sortByColumn": "FACILITY_SORT_ORDER",
            "sourceColumn": "LEISURE_FACILITY",
            "summarizeBy": "none"
          },
          {
            "name": "REPORTING_ENTITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f6fb0f4-5555-4e39-9637-aaf5c38e2af0",
            "sourceColumn": "REPORTING_ENTITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "FACILITY_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0dbd6157-172f-46b2-acfa-9d2e7b5f0584",
            "sourceColumn": "FACILITY_SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "54da71a5-78e0-4360-9cfa-06951934a067",
        "partitions": [
          {
            "name": "DIM_LEISURE_FACILITY-4a9350e9-bf1a-45ce-af6e-a148da623215",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM DIM_LEISURE_FACILITY\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"FACILITY_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_DEPARTMENT",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DEPARTMENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74ceef84-37dd-4814-bb53-87413bc3dd74",
            "sourceColumn": "DEPARTMENT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d71024b5-ffbe-447e-821c-13fcf7c74f2d",
            "sortByColumn": "DEPARTMENT_SORT_ORDER",
            "sourceColumn": "DEPARTMENT_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "792828f8-98c7-4717-a88e-e235835ed0ca",
            "sourceColumn": "DEPARTMENT_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8675017a-c22e-48a7-80b6-ac9b39396c71",
        "partitions": [
          {
            "name": "DIM_DEPARTMENT-f4848bd5-57c2-4367-a869-26a3b9334791",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM DIM_DEPARTMENT\"]),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(Source, \"DEPARTMENT_ID\", \"DEPARTMENT_ID - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DEPARTMENT_ID - Copy\", \"DEPARTMENT_SORT_ORDER\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"DEPARTMENT_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_REQUISITION_BU",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ENTITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b41bbf75-0ff9-4312-bb38-9673803b59f2",
            "sourceColumn": "ENTITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ENTITY_DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba9e819-0f25-4b09-8cb5-13e18e6dbe69",
            "sortByColumn": "REPORTING_ENTITY",
            "sourceColumn": "ENTITY_DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "REPORTING_ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1a57cf7-1c9e-45c1-8e80-b15ff833a809",
            "sourceColumn": "REPORTING_ENTITY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4337e6b0-9177-4592-b186-0e7975c31920",
        "partitions": [
          {
            "name": "DIM_REQUISITION_BU-cf3a970f-83e5-4a1f-91c7-caeef090652a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM DIM_REQUISITION_BU\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "defaultDetailRowsDefinition": {
          "expression": [
            "EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME_YOY = ",
            "VAR _CY = [EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME]",
            "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
            "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
            "VAR _PY = CALCULATE([EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
            "RETURN",
            "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
          ]
        },
        "lineageTag": "e0ffb2b9-2377-4715-b2ba-90ea88955462",
        "measures": [
          {
            "name": "PR_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE (COUNT(PR_HEADERS[PR_UNIQUE_KEY]), PR_HEADERS[PR_HEADER_CREATION_TYPE]=\"REAL\")"
            ],
            "formatString": "#,0",
            "lineageTag": "21741024-1ff6-4595-b701-e118e1b966cd"
          },
          {
            "name": "PR_APPROVED_PENDING_APPROVAL_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (SUM(PR_DETAILS[PR_LINE_AMOUNT]), KEEPFILTERS(FILTER(PR_DETAILS, NOT (PR_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\", \"REJECTED\",  \"RETURNED\", \"SPLIT\", \"WITHDRAWN\" } ))))"
            ],
            "lineageTag": "a49992df-0ca3-4d21-bda9-f733a7323771"
          },
          {
            "name": "PR_CANCELED_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "BLANK()"
            ],
            "lineageTag": "b3b8ea56-42c3-4237-a8fb-49dec7b357b0"
          },
          {
            "name": "PR_REJECTED_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (SUM(PR_DETAILS[PR_LINE_AMOUNT]), KEEPFILTERS(FILTER(PR_DETAILS, NOT (PR_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\"} ))))"
            ],
            "lineageTag": "e4ba581b-d843-491a-adf2-b12bb02dafb9"
          },
          {
            "name": "PR_OTHER_STATUS_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE (SUM(PR_DETAILS[PR_LINE_AMOUNT]), KEEPFILTERS(FILTER(PR_DETAILS, NOT (PR_DETAILS[LINE_CLOSE_STATUS] IN {\"CANCELED\", \"INCOMPLETE\"} ))))"
            ],
            "lineageTag": "c2977b44-715f-477c-91db-5e16f7e8731a"
          },
          {
            "name": "PR_VALUE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(PR_HEADERS[PR_LINE_AMOUNT]),  PR_HEADERS[PR_HEADER_CREATION_TYPE]=\"REAL\")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "6f49f992-749d-481a-9ecf-198094120779"
          },
          {
            "name": "PR_VOLUME_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PR_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([PR_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(DATE_TABLE[DATE])), DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "971974d3-5168-4254-8ed3-15420eda819b"
          },
          {
            "name": "PR_VALUE_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PR_VALUE]",
              "VAR _PY = CALCULATE([PR_VALUE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b386c238-c676-4bc7-9e21-2a756e7cf37f"
          },
          {
            "name": "PO_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE (COUNT(PO_HEADERS[PO_UNIQUE_KEY]), UPPER(PO_HEADERS[PO_TYPE])= \"PURCHASE ORDER\")"
            ],
            "formatString": "#,0",
            "lineageTag": "cfe078a2-b49c-4502-b014-1c923c0b921e"
          },
          {
            "name": "PO_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(PO_DETAILS[AMOUNT_AED]), UPPER(PO_HEADERS[PO_TYPE])= \"PURCHASE ORDER\", NOT (PO_DETAILS[LINE_CLOSE_STATUS] IN {\"INCOMPLETE\"}))"
            ],
            "lineageTag": "e344b33b-b896-478a-ad99-09d12061bc42"
          },
          {
            "name": "PO_VOLUME_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PO_VOLUME]",
              "VAR _PY = CALCULATE([PO_VOLUME], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c6fd25ca-99e9-4a06-805a-fc4948634d8e"
          },
          {
            "name": "PO_VALUE_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PO_VALUE]",
              "VAR _PY = CALCULATE([PO_VALUE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ba6c5000-00ff-48e5-8c0f-0e070090af49"
          },
          {
            "name": "PR_CONVERSION_TIME",
            "expression": [
              "",
              "CALCULATE(AVERAGE(PO_HEADERS[PR_CONVERSION_TIME]))"
            ],
            "formatString": "0",
            "lineageTag": "bca586b7-d869-4b68-b5e8-9e7a55c6b55e"
          },
          {
            "name": "PR_CONVERSION_BY_AGEING",
            "expression": [
              "",
              "VAR _SELECTED_AGEING = SELECTEDVALUE(DIM_AGEING_DAYS[AGEING_DAYS_ID])",
              "VAR _PR_UNIQUE_KEYS =  CALCULATETABLE(DISTINCT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER( PO_HEADERS, (",
              "                (_SELECTED_AGEING = 1 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 5) ||",
              "                (_SELECTED_AGEING = 3 && [PR_CONVERSION_TIME] > 5) ||",
              "                (_SELECTED_AGEING = 4 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 30) ||",
              "                (_SELECTED_AGEING = 6 && [PR_CONVERSION_TIME] > 30) ||",
              "                (_SELECTED_AGEING = 7 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 45) ||",
              "                (_SELECTED_AGEING = 9 && [PR_CONVERSION_TIME] > 45) ||",
              "                (_SELECTED_AGEING = 10 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 90) ||",
              "                (_SELECTED_AGEING = 12 && [PR_CONVERSION_TIME] > 90) )))",
              "RETURN",
              "COUNTROWS(_PR_UNIQUE_KEYS)",
              "",
              "// VAR _SELECTED_AGEING = SELECTEDVALUE(DIM_AGEING_DAYS[AGEING_DAYS_ID])",
              "// VAR _PR_UNIQUE_KEYS =  CALCULATETABLE(DISTINCT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER( PO_HEADERS, (",
              "//                 (_SELECTED_AGEING = 1 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 3) ||",
              "//                 (_SELECTED_AGEING = 2 && [PR_CONVERSION_TIME] > 3 && [PR_CONVERSION_TIME] <= 5) ||",
              "//                 (_SELECTED_AGEING = 3 && [PR_CONVERSION_TIME] > 5) ||",
              "//                 (_SELECTED_AGEING = 4 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 20) ||",
              "//                 (_SELECTED_AGEING = 5 && [PR_CONVERSION_TIME] > 20 && [PR_CONVERSION_TIME] <= 30) ||",
              "//                 (_SELECTED_AGEING = 6 && [PR_CONVERSION_TIME] > 30) ||",
              "//                 (_SELECTED_AGEING = 7 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 30) ||",
              "//                 (_SELECTED_AGEING = 8 && [PR_CONVERSION_TIME] > 30 && [PR_CONVERSION_TIME] <= 45) ||",
              "//                 (_SELECTED_AGEING = 9 && [PR_CONVERSION_TIME] > 45) ||",
              "//                 (_SELECTED_AGEING = 10 && [PR_CONVERSION_TIME] >= 0 && [PR_CONVERSION_TIME] <= 60) ||",
              "//                 (_SELECTED_AGEING = 11 && [PR_CONVERSION_TIME] > 60 && [PR_CONVERSION_TIME] <= 90) ||",
              "//                 (_SELECTED_AGEING = 12 && [PR_CONVERSION_TIME] > 90) )))",
              "// RETURN",
              "// COUNTROWS(_PR_UNIQUE_KEYS)",
              "",
              "// VAR _SELECTED_AGEING = SELECTEDVALUE(DIM_AGEING_DAYS[AGEING_DAYS_ID])",
              "// RETURN",
              "// SWITCH(_SELECTED_AGEING,",
              "// 1, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>=0 ,  [PR_CONVERSION_TIME]<=3))),  ",
              "// 2, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS,AND( [PR_CONVERSION_TIME]>3 , [PR_CONVERSION_TIME]<=5))),  ",
              "// 3, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, [PR_CONVERSION_TIME]>5 )),",
              "// 4, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS,AND( [PR_CONVERSION_TIME]>=0, [PR_CONVERSION_TIME]<=20 ))),  ",
              "// 5, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>20 , [PR_CONVERSION_TIME]<=30))),  ",
              "// 6, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, [PR_CONVERSION_TIME]>30 )),  ",
              "// 7, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>=0 ,  [PR_CONVERSION_TIME]<=30))),  ",
              "// 8, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>30 ,  [PR_CONVERSION_TIME]<=45))),",
              "// 9, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, [PR_CONVERSION_TIME]>45)),",
              "// 10, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>=0 ,  [PR_CONVERSION_TIME]<=60))),",
              "// 11, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, AND([PR_CONVERSION_TIME]>60 ,  [PR_CONVERSION_TIME]<=90))),",
              "// 12, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PR_UNIQUE_KEY]), FILTER(PO_HEADERS, [PR_CONVERSION_TIME]>90)),",
              "// BLANK()",
              "// )"
            ],
            "formatString": "0",
            "lineageTag": "da105984-4a6a-49b1-9cda-3f27538b71a5"
          },
          {
            "name": "PR_CONVERSION_AGEING_TOTAL",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUMX(DIM_AGEING_DAYS, [PR_CONVERSION_BY_AGEING]))"
            ],
            "formatString": "#,0",
            "lineageTag": "5c6e7df5-29e6-4f4b-bcac-8e169ebcc17c"
          },
          {
            "name": "PR_PROCESSED_PER_DAY",
            "expression": [
              "",
              "VAR _WORKING_DAY = CALCULATE(COUNT(DATE_TABLE[Date]))",
              "VAR _PR_COUNT = CALCULATE(COUNT(PO_HEADERS[PO_UNIQUE_KEY]), PO_HEADERS[PO_CREATION_DATE] IN VALUES((DATE_TABLE[Date])))",
              "RETURN",
              "DIVIDE(_PR_COUNT, _WORKING_DAY, 0)",
              "",
              "// VAR _WORKING_DAY = CALCULATE(COUNT(DATE_TABLE[Date]), DATE_TABLE[WEEKDAY]<>6, DATE_TABLE[WEEKDAY]<>7)  -- Requested by Procurement Team to change the logic - 9-Nov-2023"
            ],
            "formatString": "0",
            "lineageTag": "146ef1bf-6864-40b9-857e-5ac630e5bc20"
          },
          {
            "name": "PR_SAVINGS",
            "expression": [
              "",
              "VAR _BUDGET_SAVINGS = CALCULATE(SUM(PO_DETAILS[PR_BUDGET_AVAILABLE]))",
              "// VAR _PR_AMOUNT = CALCULATE([PR_VALUE], FILTER(PR_HEADERS, PR_HEADERS[PR_UNIQUE_KEY] IN VALUES(PO_HEADERS[PR_UNIQUE_KEY])))",
              "// VAR _PO_AMOUNT = CALCULATE(SUM(PO_HEADERS[PO_LINE_AMOUNT]), UPPER(PO_HEADERS[PO_TYPE])= \"PURCHASE ORDER\")",
              "RETURN",
              "\"0\"",
              "",
              "// _BUDGET_SAVINGS",
              ""
            ],
            "lineageTag": "85c360df-0715-468b-a3a7-2c37983f8cce"
          },
          {
            "name": "PR_INPROCESS_PER_BUYER",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PR_COUNT = CALCULATE(DISTINCTCOUNT(PR_DETAILS[PR_UNIQUE_KEY]), ALL(DIM_STATUS), UPPER(DIM_STATUS[STATUS])= \"APPROVED\")",
              "RETURN",
              "_PR_COUNT"
            ],
            "formatString": "#,0",
            "lineageTag": "aa283b9b-23fc-49d3-b341-89e14f631b02"
          },
          {
            "name": "PR_PENDING_APPROVAL",
            "expression": [
              "",
              "CALCULATE([PR_VOLUME], ALL(DIM_STATUS), UPPER(PR_HEADERS[STATUS])=\"PENDING APPROVAL\")"
            ],
            "formatString": "0",
            "lineageTag": "48cba6a5-f637-446b-8ebe-71737c893b1e"
          },
          {
            "name": "PR_VALUE_PENDING_APPROVAL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([PR_VALUE], ALL(DIM_STATUS), UPPER(PR_HEADERS[STATUS])=\"PENDING APPROVAL\")"
            ],
            "lineageTag": "adfde9cd-7948-4d3a-ad20-3b487f9a2c7d"
          },
          {
            "name": "BUYER_PR_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " CALCULATE([PR_VALUE], FILTER(PR_HEADERS, PR_HEADERS[PR_UNIQUE_KEY] IN VALUES(PO_HEADERS[PR_UNIQUE_KEY])))",
              ""
            ],
            "lineageTag": "2a4fc4f8-d9d5-44b2-b143-711f31c63bfb"
          },
          {
            "name": "PO_LINE_AMOUNT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(PO_HEADERS[PO_LINE_AMOUNT]), UPPER(PO_HEADERS[PO_TYPE])= \"PURCHASE ORDER\")",
            "lineageTag": "4a0efc44-03eb-4dcb-97aa-6c75e11143ce"
          },
          {
            "name": "PR_ASSIGNED_TO_BUYER",
            "expression": [
              "",
              "CALCULATE([PR_VOLUME], PR_HEADERS[STATUS] = \"APPROVED\", PR_DETAILS[BUYER_NUMBER]<>BLANK() )"
            ],
            "formatString": "0",
            "lineageTag": "29472496-feb5-469e-bff5-3c8c82c72430"
          },
          {
            "name": "RFP_RFQ_PR_COUNT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(REQ_LINES[AUCTION_HEADER_ID]), FILTER(REQ_LINES,  REQ_LINES[REQUISITION_NUMBER] IN VALUES(PR_HEADERS[PR_NUMBER])))",
              "//CALCULATE(COUNT(PR_HEADERS[PR_UNIQUE_KEY]), FILTER(PR_HEADERS,  PR_HEADERS[PR_NUMBER] IN VALUES(REQ_LINES[REQUISITION_NUMBER])))"
            ],
            "formatString": "#,0",
            "lineageTag": "185fe201-552a-47ad-9eee-a68296d7a5b5"
          },
          {
            "name": "ACTIVE_CONTRACTS_COUNT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_LIST = VALUES( PO_DETAILS[PO_UNIQUE_KEY])",
              "VAR _MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PO_NUMBERS = CALCULATETABLE(VALUES(PO_HEADERS[PO_NUMBER]), ALL(PO_HEADERS), PO_HEADERS[PO_UNIQUE_KEY] IN _PO_LIST)",
              "VAR _CONTRACTS = CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_UNIQUE_KEY]), ALL(PO_DETAILS), FILTER(ALL(PO_HEADERS), UPPER(PO_HEADERS[PO_TYPE])<>\"PURCHASE ORDER\" && UPPER(PO_HEADERS[Entity]) = \"MIRAL EXPERIENCES\" && PO_HEADERS[CONTRACT_START_DATE]>=_MIN_DATE && PO_HEADERS[CONTRACT_START_DATE]<=_MAX_DATE ))--&& UPPER(PO_HEADERS[PO_OR_PO_TYPE]) IN {\"RFP\", \"RFQ WITH CONTRACT\", \"SSJ WITH CONTRACT\"}))",
              "RETURN",
              " _CONTRACTS",
              "//CALCULATE(DISTINCTCOUNT(PR_DETAILS[PR_UNIQUE_KEY]), UPPER(PR_DETAILS[NEGOTIATION_OUTCOME])<>BLANK(), UPPER(PR_DETAILS[NEGOTIATION_OUTCOME])<>\"STANDARD\"  )+0"
            ],
            "formatString": "0",
            "lineageTag": "e9849c12-d2d4-4995-b752-5491230327fc"
          },
          {
            "name": "INVOIVING_PR_COUNT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "BLANK()",
              "//CALCULATE(DISTINCTCOUNT(PAY_DETAILS[PR_HEADER_UNIQUE_KEY]), PAY_DETAILS[PR_HEADER_UNIQUE_KEY]<>BLANK())"
            ],
            "formatString": "#,0",
            "lineageTag": "1be70d89-99f7-46e7-a3ed-070f80bf185f"
          },
          {
            "name": "SUPPLIERS_COUNT",
            "expression": "CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_KEY]), PO_HEADERS[VENDOR_KEY]<>BLANK())",
            "formatString": "0",
            "lineageTag": "aa5e186a-ad81-4e29-a88f-fe87698807e5"
          },
          {
            "name": "DYNAMIC_PR_VOLUME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABEL_K]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PR_VOLUME]",
              "VAR _FORMATTED_VOLUME = IF(_VOLUME<1000, TRUNC(_VOLUME,0), FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0K\"))",
              "VAR _YOY = [PR_VOLUME_YOY]",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "formatString": "#,0",
            "lineageTag": "dbf80c38-9460-471c-afb2-e487024174be"
          },
          {
            "name": "DATA_LABEL_K",
            "expression": "1000",
            "formatString": "0",
            "lineageTag": "8324eca8-9692-4899-8d7f-f235a855d9c4"
          },
          {
            "name": "DYNAMIC_PR_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PR_VALUE]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _YOY = [PR_VALUE_YOY]",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "4d126602-d505-40c8-95c1-3f5979ad51a2"
          },
          {
            "name": "DATA_LABLE_M",
            "expression": "1000000",
            "formatString": "0",
            "lineageTag": "a4117829-ce6a-4f17-b7cd-f3909776eca3"
          },
          {
            "name": "DYNAMIC_PO_VOLUME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABEL_K]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PO_VOLUME]",
              "VAR _FORMATTED_VOLUME = IF(_VOLUME<1000, TRUNC(_VOLUME,0), FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0K\"))",
              "VAR _YOY = [PO_VOLUME_YOY]",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "formatString": "0",
            "lineageTag": "73e70804-7fc4-45ca-9bf0-525fd69d9055"
          },
          {
            "name": "DYNAMIC_PO_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _MIN_DATE = CALCULATE((MIN(DATE_TABLE[Date])), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PO_VALUE]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0M\")",
              "VAR _PY_VALUE = CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _YOY = 0",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "b1299d09-df73-4529-acb8-dabb81a038cb"
          },
          {
            "name": "DYNAMIC_PR_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_VOLUME],",
              "SEL = 2,[PR_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "298c447a-90e9-4981-9506-ccbedb59508a"
          },
          {
            "name": "PR_ASSIGNED_TO_BUYER_VALUE",
            "expression": [
              "",
              "CALCULATE([PR_VALUE], PR_HEADERS[STATUS] = \"APPROVED\", PR_DETAILS[BUYER_NUMBER]<>BLANK() )"
            ],
            "formatString": "0",
            "lineageTag": "92db696f-c22e-4d96-9628-12933bc0eba5"
          },
          {
            "name": "RFP_RFQ_PR_COUNT_VALUE",
            "expression": [
              "",
              "CALCULATE(SUM(REQ_LINES[CURRENT_PRICE]), FILTER(REQ_LINES,  REQ_LINES[REQUISITION_NUMBER] IN VALUES(PR_HEADERS[PR_NUMBER])))",
              "//CALCULATE([PR_VALUE], FILTER(PR_HEADERS,  PR_HEADERS[PR_NUMBER] IN VALUES(REQ_LINES[REQUISITION_NUMBER])))"
            ],
            "formatString": "0",
            "lineageTag": "a5e90237-6170-4fad-b22c-ccf34d0eb29b"
          },
          {
            "name": "ACTIVE_CONTRACTS_COUNT_VALUE",
            "expression": [
              "",
              "VAR _MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "RETURN",
              "CALCULATE(SUM(PO_HEADERS[PO_AMOUNT]), ALL(PO_DETAILS), FILTER(ALL(PO_HEADERS), UPPER(PO_HEADERS[PO_TYPE])<>\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_START_DATE]>=_MIN_DATE && PO_HEADERS[CONTRACT_START_DATE]<=_MAX_DATE ))",
              "//CALCULATE([PR_VALUE], UPPER(PR_DETAILS[NEGOTIATION_OUTCOME])<>BLANK(), UPPER(PR_DETAILS[NEGOTIATION_OUTCOME])<>\"STANDARD\"  )+0"
            ],
            "formatString": "0",
            "lineageTag": "b045b216-61d6-487e-8828-af3e7a029f14"
          },
          {
            "name": "SUPPLIERS_COUNT_VALUE",
            "expression": [
              "",
              "BLANK()",
              "//CALCULATE([PR_VALUE], PR_DETAILS[VENDOR_KEY]<>BLANK())"
            ],
            "formatString": "0",
            "lineageTag": "3738f703-7e67-4383-99dc-f55cfa1dcb08"
          },
          {
            "name": "DYNAMIC_BUYER_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_ASSIGNED_TO_BUYER],",
              "SEL = 2,[PR_ASSIGNED_TO_BUYER_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c55616b6-ce6c-41ea-a277-d09da085b109"
          },
          {
            "name": "DYNAMIC_RFP_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[RFP_RFQ_PR_COUNT],",
              "SEL = 2,[RFP_RFQ_PR_COUNT_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "73a821be-2541-4813-9746-75f280b9b7d2"
          },
          {
            "name": "DYNAMIC_CONTRACT_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1, [ACTIVE_CONTRACTS_COUNT],",
              "SEL = 2, [ACTIVE_CONTRACTS_COUNT_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "16190e9f-3157-43f9-a593-908d87ab74e5"
          },
          {
            "name": "DYNAMIC_PO_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PO_VOLUME],",
              "SEL = 2,[PO_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "330c5443-a27a-4c26-aa53-4c7027cec01b"
          },
          {
            "name": "DYNAMIC_SUPPLIER_VALUE_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[SUPPLIERS_COUNT],",
              "SEL = 2,[SUPPLIERS_COUNT_VALUE]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "852e4fc5-ce63-497a-9d93-fa866b7671bd"
          },
          {
            "name": "DYNAMIC_PR_PO_TREND_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_VOLUME],",
              "SEL = 2,[PO_VOLUME]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "b4d951d6-cf36-423e-8d64-c7bde1391696"
          },
          {
            "name": "DYNAMIC_PR_PO_TREND_VALUE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_VALUE],",
              "SEL = 2,[PO_VALUE]",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "c164b99c-a692-4bb3-9843-f22336cd38e1"
          },
          {
            "name": "PO_PENDING_APPROVAL",
            "expression": [
              "",
              "CALCULATE([PO_VOLUME], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS])=\"PENDING APPROVAL\")"
            ],
            "formatString": "0",
            "lineageTag": "2454c2a5-e0c2-4f42-9bc3-f44a58beb7bb"
          },
          {
            "name": "PO_VALUE_PENDING_APPROVAL",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE([PO_VALUE], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS])=\"PENDING APPROVAL\")"
            ],
            "formatString": "#,0",
            "lineageTag": "0261c36a-ef8f-41b0-a279-8f93346b46ff"
          },
          {
            "name": "DYNAMIC_PENDING_APPROVAL_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_PENDING_APPROVAL],",
              "SEL = 2,CALCULATE([PO_VOLUME], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS])=\"OPEN\")",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "411d7953-40f9-48d9-b3ff-b20a7a76d944"
          },
          {
            "name": "DYNAMIC_PENDING_APPROVAL_VALUE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_VALUE_PENDING_APPROVAL],",
              "SEL = 2, CALCULATE([PO_VALUE], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS])=\"OPEN\")",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "56b39794-33c3-422d-a2c3-37391fc28514"
          },
          {
            "name": "DYNAMIC_AVG_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,IF(ISINSCOPE(PR_HEADERS[PR_NUMBER]), BLANK(), CALCULATE([PR_CONVERSION_TIME], REMOVEFILTERS(PR_HEADERS[PR_NUMBER]))),",
              "SEL = 2, IF(ISINSCOPE(PO_HEADERS[PO_NUMBER]), BLANK(), CALCULATE([PO_AVG_CYCLE_TIME], REMOVEFILTERS(PO_HEADERS[PO_NUMBER])))",
              ")"
            ],
            "lineageTag": "bae086bc-9a81-4f53-bcfe-d17e47a5c6c6"
          },
          {
            "name": "PO_AVG_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "AVERAGE(PO_HEADERS[PO_APPROVAL_TIME])"
            ],
            "lineageTag": "cc41accc-45d9-4d40-9f2a-a429024d57cf"
          },
          {
            "name": "DYNAMIC_TITLE_PR_PO",
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,\"PR Volume in Procurement Process\",",
              "SEL = 2,\"PR Value in Procurement Process\"",
              ")",
              ""
            ],
            "lineageTag": "14a6fbca-0a2e-453d-a1d3-8014ddb22834"
          },
          {
            "name": "DYNAMIC_TITLE_PR_PO_SELECTION",
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,\"PR Trend (Last 12 Months)\",",
              "SEL = 2,\"PO Trend (Last 12 Months)\"",
              ")",
              ""
            ],
            "lineageTag": "ace2408c-d620-42c3-abb5-04b713e7666d"
          },
          {
            "name": "DYNAMIC_TITLE_PR_PO_APPROVAL",
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,\"PRs (Pending for Approval)\",",
              "SEL = 2,\"Open POs\"",
              ")"
            ],
            "lineageTag": "d8b647b0-6d65-458f-b9ed-43d56c7ffb91"
          },
          {
            "name": "PR_AGEING_PENDING",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(PR_HEADERS[PR_AGEING_DAYS]))",
            "lineageTag": "1d42ad5a-2c57-4aab-88b6-0aede7323ef9"
          },
          {
            "name": "PO_AGEING_PENDING",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(PO_HEADERS[PO_AGEING_DAYS]))",
            "lineageTag": "87e22e78-367f-4539-a0a3-50b6c99a72f0"
          },
          {
            "name": "DYNAMIC_AVG_AGEING_DAYS",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_PR_PO_SELECTION[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_AGEING_PENDING],",
              "SEL = 2,[PO_AGEING_PENDING]",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "6da61ec6-8ea4-4bfe-b82f-176879971c0a"
          },
          {
            "name": "Measure 4",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "8435447d-8ae7-4a33-8ac1-85a964e384b3"
          },
          {
            "name": "BUYER_ON_TARGET_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _GREEN_VALUE = CALCULATE(SUMX(FILTER(DIM_AGEING_DAYS, DIM_AGEING_DAYS[AGEING_COLOR_CODE]=1), [PR_CONVERSION_BY_AGEING] ))",
              "VAR _TOTAL = 'All Measures'[PR_CONVERSION_AGEING_TOTAL]",
              "RETURN",
              "DIVIDE(_GREEN_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4940942c-6060-4540-af17-1112288be4ae"
          },
          {
            "name": "LAST_REFRESHED_DATE_TIME",
            "expression": [
              "",
              "VAR _DATETIME = format([LAST_REFRESHED_DATE], \"dd-Mmm-yy\")",
              "VAR _DISPLAY_TEXT = \"Data Last refreshed: \"",
              "RETURN",
              "_DISPLAY_TEXT & _DATETIME"
            ],
            "lineageTag": "eb38bf0e-fe1d-42b5-bde3-2d1e7f2b8c8a"
          },
          {
            "name": "DYNAMIC_APPROVED_PR_VOLUME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABEL_K]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = CALCULATE([PR_VOLUME], ALL(DIM_STATUS), UPPER(DIM_STATUS[STATUS]) IN { \"APPROVED\", \"CLOSED\" })",
              "VAR _FORMATTED_VOLUME = IF(_VOLUME<1000, TRUNC(_VOLUME,0), FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0K\"))",
              "VAR _YOY = CALCULATE([PR_VOLUME_YOY], ALL(DIM_STATUS), UPPER(DIM_STATUS[STATUS]) IN { \"APPROVED\", \"CLOSED\" })",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "9b2d257e-a6c2-4e62-8a0d-5f04759ec231"
          },
          {
            "name": "DYNAMIC_APPROVED_PR_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = CALCULATE([PR_VALUE], ALL(DIM_STATUS), UPPER(DIM_STATUS[STATUS]) IN {\"APPROVED\", \"CLOSED\"})",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _YOY = CALCULATE([PR_VALUE_YOY], ALL(DIM_STATUS), UPPER(DIM_STATUS[STATUS]) IN {\"APPROVED\", \"CLOSED\"})",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "17160ee5-82c8-4a1a-b3dd-099f03b9ae4e"
          },
          {
            "name": "DYNAMIC_PR_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _CYCLE_TIME = CALCULATE([PR_CYCLE_TIME])",
              "//VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.#M\")",
              "VAR _YOY = CALCULATE([PR_CYCLE_TIME_YOY])",
              "//VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _CYCLE_TIME, _YOY)"
            ],
            "lineageTag": "7e56d4d7-eedb-4c02-8d09-c8eb4cace968"
          },
          {
            "name": "PR_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(AVERAGE(PR_HEADERS[PR_APPROVAL_TIME]),PR_HEADERS[PR_APPROVAL_TIME]>=0)"
            ],
            "lineageTag": "e19281f5-858f-454c-90c5-459bd3080a23"
          },
          {
            "name": "PR_CYCLE_TIME_YOY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PR_CYCLE_TIME]",
              "VAR _PY = CALCULATE([PR_CYCLE_TIME], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "lineageTag": "13e8d521-8eae-4166-afaa-dd0263e2305f"
          },
          {
            "name": "DYNAMIC_PR_CONVERSION_RATE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _CONVERSION_RATE = FORMAT([PR_CONVERSION_RATE], \"0%\")",
              "//VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.#M\")",
              "VAR _YOY = CALCULATE([PR_CONVERSION_RATE_YOY])",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _CONVERSION_RATE, _FORMATTED_YOY)"
            ],
            "lineageTag": "badce918-2e69-4a33-8fa9-52695c00e91e"
          },
          {
            "name": "PR_CONVERSION_RATE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _APPROVED_PR = CALCULATE([PR_VOLUME], ALL(DIM_STATUS),DIM_STATUS[STATUS] IN {\"APPROVED\", \"CLOSED\"})",
              "VAR _TOTAL_PR = CALCULATE([PR_VOLUME], ALL(DIM_STATUS))",
              "RETURN",
              "DIVIDE(_APPROVED_PR, _TOTAL_PR, BLANK())"
            ],
            "lineageTag": "1800e0e2-5800-4091-8762-f8248373892d"
          },
          {
            "name": "PR_CONVERSION_RATE_YOY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [PR_CONVERSION_RATE]",
              "VAR _PY = CALCULATE([PR_CONVERSION_RATE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "lineageTag": "f236809e-0897-4c9a-bae7-faed66ffe7b7"
          },
          {
            "name": "DYNAMIC_EXP_FARAH_PR_VOLUME_VALUE",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_EXP_FARAH_SELECTION[SELECTION_SORT_ORDER])",
              "VAR _EXP = CALCULATE([DYNAMIC_PR_VALUE_VOLUME], ALL(DIM_ENTITY), ALL(DIM_LEISURE_FACILITY),DIM_LEISURE_FACILITY[FACILITY_ID]=\"102\")",
              "VAR _FARAH = CALCULATE([DYNAMIC_PR_VALUE_VOLUME], ALL(DIM_ENTITY), ALL(DIM_LEISURE_FACILITY), DIM_LEISURE_FACILITY[FACILITY_ID]<>\"102\")",
              "RETURN",
              "IF(_SELECTION=1, _EXP, _FARAH)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5fca09e8-0cba-48e0-b98f-3929cef775f4"
          },
          {
            "name": "SELECTED_DIM_VOLUME_VALUE",
            "expression": "SELECTEDVALUE(DIM_VOL_VALUE[CATEGORY])",
            "lineageTag": "e8976c3a-d596-4940-8714-10920147c02d"
          },
          {
            "name": "CONTROL_CATEGORY",
            "expression": [
              "",
              "VAR _CATEGORY = SELECTEDVALUE(PR_DETAILS[ITEM_CATEGORY])",
              "RETURN",
              "IF(ISERROR(INT(MID(_CATEGORY, 1, 1))),1,0)"
            ],
            "formatString": "0",
            "lineageTag": "cc99864c-c7ea-45ae-9b2f-9420117cad8d"
          },
          {
            "name": "AVG_SPEND_PER_PO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(DIVIDE([PO_VALUE], [PO_VOLUME], BLANK()))"
            ],
            "lineageTag": "76ae775f-7e93-494c-81be-0aea8af35dd7"
          },
          {
            "name": "AVG_SPEND_PER_SUPPLIER",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(DIVIDE([PO_VALUE], [SUPPLIERS_COUNT_WITH_PO], BLANK()))"
            ],
            "lineageTag": "07ba29b7-12b6-4b7e-886f-b0697592713e"
          },
          {
            "name": "SUPPLIERS_COUNT_WITH_PO",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_KEY]))"
            ],
            "formatString": "0",
            "lineageTag": "bfd95da7-a8be-43a7-9eb4-015657c4a4b8"
          },
          {
            "name": "AVG_SPEND_PER_CATEGORY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CATEGROY_COUNT = CALCULATE(DISTINCTCOUNT(PR_DETAILS[ITEM_CATEGORY]))",
              "RETURN",
              "CALCULATE(DIVIDE([PO_VALUE], _CATEGROY_COUNT , BLANK()))"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3adbfa0e-8a10-465b-9f72-b17bcaff046a"
          },
          {
            "name": "DYNAMIC_AVG_SPEND_PER_PO",
            "expression": [
              "",
              "VAR NUM = 1000 ",
              "VAR _MIN_DATE = CALCULATE((MIN(DATE_TABLE[Date])), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [AVG_SPEND_PER_PO]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0K\")",
              "VAR _PY_SPEND = CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_PO_COUNT = CALCULATE(DISTINCTCOUNT(PO_Historical[PO_NUMBER]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_VALUE = DIVIDE(_PY_SPEND, _PY_PO_COUNT, 0)",
              "VAR _YOY = DIVIDE((_VOLUME- _PY_VALUE),_PY_VALUE, 0) ",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "5c807b50-356a-46cb-a171-2edf490d6e04"
          },
          {
            "name": "DYNAMIC_AVG_SPEND_PER_SUPPLIER",
            "expression": [
              "",
              "VAR NUM = 1000000 ",
              "VAR _MIN_DATE = CALCULATE((MIN(DATE_TABLE[Date])), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [AVG_SPEND_PER_SUPPLIER]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0M\")",
              "VAR _PY_SPEND = CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(PO_Historical[SUPPLIER]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_VALUE = DIVIDE(_PY_SPEND, _PY_SUPPLIER_COUNT, 0)",
              "VAR _YOY = DIVIDE((_VOLUME- _PY_VALUE),_PY_VALUE, 0) ",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "a04c2ec0-5d95-478c-8cf1-80063f745ad9"
          },
          {
            "name": "DYNAMIC_AVG_SPEND_PER_CATEGORY",
            "expression": [
              "",
              "VAR NUM = 1000000 ",
              "VAR _MIN_DATE = CALCULATE((MIN(DATE_TABLE[Date])), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [AVG_SPEND_PER_CATEGORY]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0M\")",
              "VAR _PY_SPEND = CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_CATEGORY_COUNT = CALCULATE(DISTINCTCOUNT(PO_Historical[CATEGORY]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _PY_VALUE = DIVIDE(_PY_SPEND, _PY_CATEGORY_COUNT, 0)",
              "VAR _YOY = DIVIDE((_VOLUME- _PY_VALUE),_PY_VALUE, 0) ",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "678ffc5e-bfc1-49ae-9672-a21ff0b2be35"
          },
          {
            "name": "SPEND_CONTRIBUTION",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PO_HEADERS[VENDOR_NAME]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ccf4c3f3-cc0c-4dc4-a54b-c90cfb70fea0"
          },
          {
            "name": "SPEND_VALUE_BY_RATIO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _SELECTED_RATIO = SELECTEDVALUE(DIM_SPEND_RATIO[SPEND_RATIO_SORT_ORDER])",
              "VAR _80_SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_NAME]), FILTER(ALLSELECTED(PO_HEADERS[VENDOR_NAME]), 'All Measures'[SPEND_CONTRIBUTION_RT]<=0.8))",
              "VAR _20_SUPPLIER_COUNT = 'All Measures'[SUPPLIERS_COUNT_WITH_PO]- _80_SUPPLIER_COUNT",
              "",
              "RETURN",
              "IF(_SELECTED_RATIO=1, _80_SUPPLIER_COUNT, _20_SUPPLIER_COUNT)"
            ],
            "lineageTag": "7c772551-817d-46a2-b70f-ab5772a2cddd"
          },
          {
            "name": "SPEND_RATIO",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var sales=SUMX(FILTER(ALLSELECTED(PO_HEADERS[VENDOR_NAME]), [SPEND_CONTRIBUTION_RANK]<=1), [SPEND_CONTRIBUTION])",
              "var totalsales=CALCULATE([PO_VALUE],ALLSELECTED(PO_HEADERS[VENDOR_NAME]))",
              "return ",
              "sales"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "973c7b08-33cb-408d-bb2b-a4a78a329660"
          },
          {
            "name": "SPEND_CONTRIBUTION_RANK",
            "expression": [
              "",
              "VAR _RANK = RANKX(ALLSELECTED(PO_HEADERS[VENDOR_NAME]), [PO_VALUE], [PO_VALUE], DESC)",
              "RETURN",
              "_RANK"
            ],
            "formatString": "0",
            "lineageTag": "381a3b52-e53f-4f31-bdf6-f25ef6f2aa6a"
          },
          {
            "name": "SPEND_CONTRIBUTION_BUYER",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PO_HEADERS[BUYER_NAME]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b014323d-a68c-4bdd-b7a2-45c26d0b0b10"
          },
          {
            "name": "SPEND_CONTRIBUTION_CATEGORY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PR_DETAILS[ITEM_CATEGORY]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f9f9576d-90de-4b16-b801-7d304473d073"
          },
          {
            "name": "SPEND_CONTRIBUTION_DEPARTMENT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PR_HEADERS[DEPARTMENT]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ebf19157-89f5-493a-916a-b2724ef92617"
          },
          {
            "name": "SPEND_CONTRIBUTION_LEISURE FACILITY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PO_HEADERS), ALLSELECTED(PR_DETAILS))",
              "//CALCULATE([PO_VALUE], ALLSELECTED(DIM_LEISURE_FACILITY[LEISURE_FACILITY]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "25871719-368f-40ee-810d-d00927279698"
          },
          {
            "name": "CONTRACTS_VOLUME",
            "expression": [
              "",
              "CALCULATE (COUNT(PO_HEADERS[PO_UNIQUE_KEY]), FILTER(PO_HEADERS, PO_HEADERS[PO_TYPE]<>BLANK() && UPPER(PO_HEADERS[PO_TYPE])<>\"PURCHASE ORDER\"))"
            ],
            "formatString": "0",
            "lineageTag": "e2ae72aa-11df-438d-b540-6eae96480e46"
          },
          {
            "name": "CONTRACT_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(PO_HEADERS[PO_AMOUNT]), FILTER(PO_HEADERS, UPPER(PO_HEADERS[PO_TYPE])<> \"PURCHASE ORDER\"&& PO_HEADERS[PO_TYPE]<>BLANK() ))"
            ],
            "lineageTag": "7aa56f98-03bc-4c44-991c-c2af60d659f3"
          },
          {
            "name": "EXPIRED_CONTRACTS_VOLUME",
            "expression": [
              "",
              "CALCULATE([CONTRACTS_VOLUME], ALL(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, PO_HEADERS[CONTRACT_END_DATE]<>BLANK() && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]=1 && UPPER(PO_HEADERS[STATUS])=\"OPEN\"))"
            ],
            "formatString": "0",
            "lineageTag": "f0e6c504-c603-477a-9bad-578a20457976"
          },
          {
            "name": "EXPIRED_CONTRACTS_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([CONTRACT_VALUE], ALL(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, PO_HEADERS[CONTRACT_END_DATE]<> BLANK() && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]=1 && UPPER(PO_HEADERS[STATUS])=\"OPEN\"))"
            ],
            "lineageTag": "75fee8ff-6778-4e01-9d6d-e49b0aa28086"
          },
          {
            "name": "BPA_CONTRACTS_VOLUME",
            "expression": [
              "",
              "CALCULATE (COUNT(PO_HEADERS[PO_UNIQUE_KEY]), UPPER(PO_HEADERS[PO_TYPE])=\"BLANKET PURCHASE AGREEMENT\")"
            ],
            "formatString": "0",
            "lineageTag": "81168b7a-6a8a-4520-aeab-e5fc8550f56b"
          },
          {
            "name": "CPA_CONTRACTS_VOLUME",
            "expression": [
              "",
              "CALCULATE (COUNT(PO_HEADERS[PO_UNIQUE_KEY]), UPPER(PO_HEADERS[PO_TYPE])=\"CONTRACT PURCHASE AGREEMENT\")"
            ],
            "formatString": "0",
            "lineageTag": "28326985-0dc9-4b63-9bd0-984a2bdf3529"
          },
          {
            "name": "RUNNING TOTAL PO_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _RANK = [SPEND_CONTRIBUTION_RANK]",
              "",
              "RETURN",
              "",
              "CALCULATE(SUMX(TOPN(_RANK, ALLSELECTED(PO_HEADERS[VENDOR_NAME]), [PO_VALUE], DESC), [PO_VALUE]))",
              "",
              "// VAR RANKS = RANKX(ALLSELECTED(PO_HEADERS[VENDOR_NAME]), [PO_VALUE],, DESC,Dense)",
              "// VAR RUN_TOTAL = CALCULATE([PO_VALUE], FILTER(ALLSELECTED(PO_HEADERS[VENDOR_NAME]),[PO_VALUE] >= EARLIER([PO_VALUE] )",
              "//FILTER(ALLSELECTED(PO_HEADERS[VENDOR_NAME]),",
              "//RANKS >= RANKX(ALLSELECTED(PO_HEADERS[VENDOR_NAME]), [PO_VALUE],, DESC,Dense)))",
              "",
              "//RETURN",
              "// RUN_TOTAL"
            ],
            "lineageTag": "bedc3fee-fc40-486c-b26b-368371c8e518"
          },
          {
            "name": "SPEND_CONTRIBUTION_SUPPLIER",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [RUNNING TOTAL PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PO_HEADERS[VENDOR_NAME]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ff08b79-9afe-48be-bcd2-775f117e7bc6"
          },
          {
            "name": "CONTRIBUTION_FLAG",
            "expression": [
              "",
              "VAR _FLAG = [SPEND_CONTRIBUTION_RT]",
              "RETURN",
              "IF(_FLAG<=0.8, 1 , 0)"
            ],
            "formatString": "0",
            "lineageTag": "10e6db04-dd65-4edc-8161-dba5597ac696"
          },
          {
            "name": "DYNAMIC_PR_VALUE_CREATION_APPROVED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_PR_CUST_DATE[ID]),",
              "   1, CALCULATE([PR_VALUE], ALL(DATE_TABLE), PR_HEADERS[CREATED_DATE]>=MIN_DATE,  PR_HEADERS[CREATED_DATE]<=MAX_DATE,PR_HEADERS[CREATED_DATE]<>BLANK()  ),",
              "   2, CALCULATE([PR_VALUE], ALL(DATE_TABLE), PR_HEADERS[PR_APPROVED_DATE]>=MIN_DATE,  PR_HEADERS[PR_APPROVED_DATE]<=MAX_DATE,PR_HEADERS[PR_APPROVED_DATE]<>BLANK() )",
              ")",
              "",
              "",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "219f66f7-2575-4138-87cb-fd2345c9dfee"
          },
          {
            "name": "DYNAMIC_PR_VOLUME_CREATION_APPROVED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_PR_CUST_DATE[ID]),",
              "   1, CALCULATE([PR_VOLUME], ALL(DATE_TABLE), PR_HEADERS[CREATED_DATE]>=MIN_DATE,  PR_HEADERS[CREATED_DATE]<=MAX_DATE, PR_HEADERS[CREATED_DATE]<>BLANK()  ),",
              "   2, CALCULATE([PR_VOLUME], ALL(DATE_TABLE), PR_HEADERS[PR_APPROVED_DATE]>=MIN_DATE,  PR_HEADERS[PR_APPROVED_DATE]<=MAX_DATE,PR_HEADERS[PR_APPROVED_DATE]<>BLANK() )",
              ")",
              "",
              "",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "71be2cf0-d2d9-44c4-8260-1d66f06f6522"
          },
          {
            "name": "DYNAMIC_PO_VALUE_CREATED_APPROVED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_PO_CUST_DATE[ID]),",
              "   1, CALCULATE([PO_VALUE], ALL(DATE_TABLE), ALL(CONTRACT_DATE_TABLE),  PO_HEADERS[PO_CREATION_DATE]>=MIN_DATE,  PO_HEADERS[PO_CREATION_DATE]<=MAX_DATE,PO_HEADERS[PO_CREATION_DATE]<>BLANK()  ),",
              "   2, CALCULATE([PO_VALUE], ALL(DATE_TABLE), ALL(CONTRACT_DATE_TABLE), PO_HEADERS[PO_APPROVED_DATE]>=MIN_DATE,  PO_HEADERS[PO_APPROVED_DATE]<=MAX_DATE,PO_HEADERS[PO_APPROVED_DATE]<>BLANK() )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "9b13f0e7-152c-4e74-abe4-36b695ebb489"
          },
          {
            "name": "DYNAMIC_PO_VOLUME_CREATED_APPROVED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_PO_CUST_DATE[ID]),",
              "   1, CALCULATE([PO_VOLUME], ALL(DATE_TABLE), PO_HEADERS[PO_CREATION_DATE]>=MIN_DATE,  PO_HEADERS[PO_CREATION_DATE]<=MAX_DATE,PO_HEADERS[PO_CREATION_DATE]<>BLANK()  ),",
              "   2, CALCULATE([PO_VOLUME], ALL(DATE_TABLE), PO_HEADERS[PO_APPROVED_DATE]>=MIN_DATE,  PO_HEADERS[PO_APPROVED_DATE]<=MAX_DATE,PO_HEADERS[PO_APPROVED_DATE]<>BLANK() )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "32c627b6-e133-4e2f-afc3-925c04fe9f58"
          },
          {
            "name": "DYNAMIC_CONTRACT_VALUE_START_EXPIRED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_CONTRACT_DATE[ID]),",
              "   1, CALCULATE([CONTRACT_VALUE], ALL(DATE_TABLE), PO_HEADERS[CONTRACT_START_DATE]>=MIN_DATE,  PO_HEADERS[CONTRACT_START_DATE]<=MAX_DATE,PO_HEADERS[CONTRACT_START_DATE]<>BLANK()  ),",
              "   2, CALCULATE([CONTRACT_VALUE], ALL(DATE_TABLE), PO_HEADERS[CONTRACT_END_DATE]>=MIN_DATE,  PO_HEADERS[CONTRACT_END_DATE]<=MAX_DATE,PO_HEADERS[CONTRACT_END_DATE]<>BLANK() && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]<>BLANK() )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "02011d98-900d-45a7-8c42-24f51e795085"
          },
          {
            "name": "DYNAMIC_CONTRACT_VOLUME_START_EXPIRED",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_CONTRACT_DATE[ID]),",
              "   1, CALCULATE([CONTRACTS_VOLUME], ALL(DATE_TABLE), PO_HEADERS[CONTRACT_START_DATE]>=MIN_DATE,  PO_HEADERS[CONTRACT_START_DATE]<=MAX_DATE,PO_HEADERS[CONTRACT_START_DATE]<>BLANK()  ),",
              "   2, CALCULATE([CONTRACTS_VOLUME], ALL(DATE_TABLE), PO_HEADERS[CONTRACT_END_DATE]>=MIN_DATE,  PO_HEADERS[CONTRACT_END_DATE]<=MAX_DATE,PO_HEADERS[CONTRACT_END_DATE]<>BLANK()  && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]<>BLANK())",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "dfbb951b-6c59-44f4-8488-73462aac52e0"
          },
          {
            "name": "SPEND_CONTRIBUTION_RT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _PO_VALUE = [RUNNING TOTAL PO_VALUE]",
              "VAR _TOTAL = CALCULATE([PO_VALUE], ALLSELECTED(PO_HEADERS[VENDOR_NAME]))",
              "RETURN",
              "DIVIDE(_PO_VALUE, _TOTAL, BLANK())"
            ],
            "lineageTag": "77de2245-2ded-4eef-8e5c-5f50a268683b"
          },
          {
            "name": "SORTING_FLAG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SWITCH(SELECTEDVALUE(DIM_SPEND_RATIO[SPEND_RATIO_SORT_ORDER]),",
              "    1,IF([CONTRIBUTION_FLAG] = 1,1),",
              "    2,IF([CONTRIBUTION_FLAG] = 0,1),",
              "    IF([CONTRIBUTION_FLAG] IN {0,1},1)",
              ")"
            ],
            "lineageTag": "5da5498e-788d-447b-a1d3-0ff2cc94fa05"
          },
          {
            "name": "DYNAMIC_PO_VALUE_VOLUME_WITH_SSJ",
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,CALCULATE([PO_VOLUME], UPPER(PO_HEADERS[PO_OR_PO_TYPE]) IN {\"SSJ WITH CONTRACT\", \"SSJ WITHOUT CONTRACT\"}),",
              "SEL = 2,CALCULATE([PO_VALUE], UPPER(PO_HEADERS[PO_OR_PO_TYPE]) IN {\"SSJ WITH CONTRACT\", \"SSJ WITHOUT CONTRACT\"})",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "572e211c-a7eb-402c-a10d-bc5b2770ab0e"
          },
          {
            "name": "PR_STATUS_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _VOL = CALCULATE([PR_VOLUME])",
              "VAR _TOTAL = CALCULATE([PR_VOLUME], ALL(DIM_STATUS))",
              "RETURN",
              "DIVIDE(_VOL, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a4a61a48-9449-48e4-9ca3-db9ddfa9ab94"
          },
          {
            "name": "PR_CURRENT_OWNER_AVG_AGEING",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(PR_HEADERS[PR_AGEING])",
            "lineageTag": "3559d111-76df-43b3-9b5a-50844072a5ff"
          },
          {
            "name": "PR_VOLUME_BY_AGEING",
            "expression": [
              "",
              "BLANK()",
              "//VAR _SELECTED_AGEING = SELECTEDVALUE(DIM_APPROVER_AGEING[AGEING_SORT_ORDER])",
              "//VAR _AGEING = CALCULATE([PR_VOLUME])",
              "//RETURN",
              "//SWITCH(TRUE(),",
              "//_SELECTED_AGEING =1 , CALCULATE([PR_VOLUME], FILTER(PR_CURRENT_OWNER, PR_CURRENT_OWNER[PR_AGEING]>=0 && PR_CURRENT_OWNER[PR_AGEING]<=7,",
              "//",
              "//)))"
            ],
            "lineageTag": "9ed0a81d-daf4-4941-a1d7-41c375bbe95a"
          },
          {
            "name": "PR_VALUE_CURRENT_PENDING_OWNER",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([PR_VALUE], FILTER(PR_HEADERS, PR_HEADERS[PR_UNIQUE_KEY] IN VALUES(PR_CURRENT_OWNER[PR_UNIQUE_KEY])))"
            ],
            "lineageTag": "fc9bfc26-25ac-4275-b537-2f098db6baf4"
          },
          {
            "name": "PO_VALUE_CURRENT_PENDING_OWNER",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([PO_VALUE], FILTER(PO_HEADERS, PO_HEADERS[PO_UNIQUE_KEY] IN VALUES(PO_CURRENT_OWNER[PO_UNIQUE_KEY])))"
            ],
            "lineageTag": "364898a8-7619-4ea9-94be-b0fe72613c8e"
          },
          {
            "name": "EXPIRED_CONTRACT_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _EXPIRED_CONTACTS = [EXPIRED_CONTRACTS_VOLUME]",
              "VAR _TOTAL = [CONTRACTS_VOLUME]",
              "RETURN",
              "DIVIDE(_EXPIRED_CONTACTS, _TOTAL, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "449ad5d3-620e-40b0-b0b7-dc4b7c4dc662"
          },
          {
            "name": "PO_COVERED_CONTRACTS",
            "expression": [
              "",
              "VAR _MIN_DATE = CALCULATE(MIN(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE))",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE))",
              "VAR _COVERED = CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE], PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE),KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE  ))",
              "VAR _MEMO = CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE], PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])<>\"PURCHASE ORDER\" && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE))",
              "VAR _SEL = SELECTEDVALUE(DIM_PO_COVERED[Sort_order])",
              "RETURN",
              "IF(_SEL IN {1,2}, _COVERED, _MEMO)"
            ],
            "formatString": "0",
            "lineageTag": "8241af8e-b17b-405f-ab81-6beded7ccd66"
          },
          {
            "name": "CONTRACT_UPLOAD_AGEING",
            "expression": [
              "",
              "VAR _MIN_DATE = CALCULATE(MIN(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE))",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE))",
              "VAR _SEL = SELECTEDVALUE(DIM_CONTRACT_UPLOAD_AGEING[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(), ",
              "_SEL=1, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE], PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]>=0 && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]<=5  && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE )),",
              "_SEL=2, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE] , PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]>=6 && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]<=30 && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE  )),",
              "_SEL=3, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE] , PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]>=31 && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]<=60 && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE  )),",
              "_SEL=4, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE] , PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]>=61 && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE )),",
              "_SEL=5, CALCULATE(DISTINCTCOUNT(PO_HEADERS[PO_NUMBER]), REMOVEFILTERS(PO_HEADERS[PO_TYPE] , PO_HEADERS[CONTRACT_START_DATE], PO_HEADERS[CONTRACT_END_DATE]), ALL(CONTRACT_DATE_TABLE), KEEPFILTERS(UPPER(PO_HEADERS[PO_TYPE])=\"PURCHASE ORDER\" && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]<>BLANK() && PO_HEADERS[CONTRACT_UPLOAD_AGEING_DAYS]<0 && PO_HEADERS[PO_CREATION_DATE]>=_MIN_DATE && PO_HEADERS[PO_CREATION_DATE]<=_MAX_DATE )),",
              "BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e783fd2d-2e4c-4e00-9e99-46efe8eb3386"
          },
          {
            "name": "DYNAMIC_PO_HISTORY_VALUE_CREATED_APPROVED",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(CONTRACT_DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_PO_CUST_DATE[ID]),",
              "   1, CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(DATE_TABLE), PO_Historical[CREATION_DATE]>=MIN_DATE,  PO_Historical[CREATION_DATE]<=MAX_DATE,PO_Historical[CREATION_DATE]<>BLANK()  ),",
              "   2, CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(DATE_TABLE), PO_Historical[APPROVED_DATE]>=MIN_DATE,  PO_Historical[APPROVED_DATE]<=MAX_DATE,PO_Historical[APPROVED_DATE]<>BLANK() )",
              ")"
            ],
            "lineageTag": "679bcc66-a400-464b-9c5f-1b5d7c254a03"
          },
          {
            "name": "DYNAMIC_PO_HISTORY_CURRENT_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _YEAR = SELECTEDVALUE(CONTRACT_DATE_TABLE[Year])",
              "VAR _HISTORY = [DYNAMIC_PO_HISTORY_VALUE_CREATED_APPROVED]",
              "VAR _CURRENT = CALCULATE([DYNAMIC_PO_VALUE_CREATED_APPROVED], ALL(DATE_TABLE),TREATAS(VALUES(CONTRACT_DATE_TABLE[Date]),  DATE_TABLE[Date]))",
              "",
              "RETURN",
              "IF(_HISTORY=BLANK(), _CURRENT, _HISTORY)"
            ],
            "lineageTag": "08bed7f2-9fa5-49ac-aea6-d47db80f008d"
          },
          {
            "name": "CONTRACT_SIGNED_TOTAL",
            "expression": "CALCULATE(SUMX(DIM_CONTRACT_UPLOAD_AGEING, [CONTRACT_UPLOAD_AGEING]))",
            "formatString": "0",
            "lineageTag": "cefba3b3-e4cb-4611-a129-3f1b1f4b57aa"
          },
          {
            "name": "COVERED_PO_TOTAL",
            "expression": "CALCULATE(SUMX(DIM_PO_COVERED, [PO_COVERED_CONTRACTS]))",
            "formatString": "0",
            "lineageTag": "130b777e-6ddc-4e74-871e-b88e1ab5adb1"
          },
          {
            "name": "DYNAMIC_APPROVED_PO_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = CALCULATE([PO_VALUE], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS]) IN {\"OPEN\", \"FINALLY CLOSED\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\"})",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _YOY = CALCULATE([PO_VALUE_YOY], ALL(DIM_STATUS), UPPER(PO_HEADERS[STATUS]) IN {\"OPEN\", \"FINALLY CLOSED\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\"})",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "9ecec7c2-8291-43e1-b17f-b51f60cab8d6"
          },
          {
            "name": "DYNAMIC_SPEND_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _MIN_DATE = CALCULATE((MIN(DATE_TABLE[Date])), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]), ALLSELECTED(DATE_TABLE))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PO_VALUE]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _PY_VALUE = CALCULATE(SUM(PO_Historical[AMOUNT_AED]), ALL(CONTRACT_DATE_TABLE), PO_Historical[CREATION_DATE]>= _PY_MIN_DATE && PO_Historical[CREATION_DATE]<=_PY_MAX_DATE )",
              "VAR _YOY = DIVIDE((_VOLUME- _PY_VALUE), _PY_VALUE, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "80937329-7a4f-48a9-94fa-04e6edfa40d3"
          },
          {
            "name": "DYNAMIC_PO_APPROVAL_RATE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _TOTAL_PO = CALCULATE([PO_VOLUME])",
              "VAR _PO = VALUES(PO_HEADERS[PO_UNIQUE_KEY])",
              "VAR _APPROVED_PO = CALCULATE([PO_VOLUME], ALL(DIM_STATUS), REMOVEFILTERS(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, UPPER(PO_HEADERS[STATUS]) IN {\"OPEN\", \"FINALLY CLOSED\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\"} && PO_HEADERS[PO_UNIQUE_KEY] IN _PO))",
              "VAR _APROVAL_RATE = DIVIDE( _APPROVED_PO, _TOTAL_PO, 0)",
              "VAR _FORMATED_APROVAL_RATE = FORMAT(_APROVAL_RATE, \"#0.0%\")",
              "//VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.#M\")",
              "VAR _YOY = CALCULATE([PR_CONVERSION_RATE_YOY])",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATED_APROVAL_RATE, _FORMATTED_YOY)"
            ],
            "lineageTag": "02895921-2af0-4b4d-b9c6-6d5f47f4851b"
          },
          {
            "name": "DYNAMIC_APPROVED_PO_VOLUME",
            "expression": [
              "",
              "VAR NUM = 1000",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _PO = VALUES(PO_HEADERS[PO_UNIQUE_KEY])",
              "VAR _VOLUME = CALCULATE([PO_VOLUME], ALL(DIM_STATUS), REMOVEFILTERS(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, UPPER(PO_HEADERS[STATUS]) IN {\"OPEN\", \"FINALLY CLOSED\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\"} && PO_HEADERS[PO_UNIQUE_KEY] IN _PO))",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0K\")",
              "VAR _YOY = CALCULATE([PO_VOLUME_YOY],  UPPER(PO_HEADERS[STATUS]) IN {\"OPEN\", \"FINALLY CLOSED\", \"CLOSED\", \"CLOSED FOR RECEIVING\", \"CLOSED FOR INVOICING\"})",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "719bfe41-d2a4-42f3-9f32-82f9ff743cb5"
          },
          {
            "name": "EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME",
            "expression": [
              "",
              "CALCULATE([CONTRACTS_VOLUME], ALL(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, PO_HEADERS[CONTRACT_END_DATE]<>BLANK() && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]=1 && UPPER(PO_HEADERS[STATUS])=\"OPEN\" && PO_HEADERS[ATTRIBUTE5]= \"Continuing Service - Sourcing Decision\"))+0"
            ],
            "formatString": "0",
            "lineageTag": "3b3b910b-2dd0-4b4a-b66f-cebd3a1f0f9c"
          },
          {
            "name": "LAST_REFRESHED_DATE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "//TODAY()-1",
              "MAX('Last Refreshed Date'[Date Last Refreshed])"
            ],
            "formatString": "dd-Mmm-YY",
            "lineageTag": "638326ed-931c-4a89-abfe-43ee64f6ab2b"
          },
          {
            "name": "EXPIRED_SERVICE_REQUIRED_CONTRACTS_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([CONTRACT_VALUE], ALL(PO_HEADERS[STATUS]), FILTER(PO_HEADERS, PO_HEADERS[CONTRACT_END_DATE]<>BLANK() && PO_HEADERS[CONTRACT_EXPIRY_CATEGORY]=1 && UPPER(PO_HEADERS[STATUS])=\"OPEN\" && PO_HEADERS[ATTRIBUTE5]= \"Continuing Service - Sourcing Decision\"))+0"
            ],
            "lineageTag": "fec7f8f1-6cc0-4925-8e1c-c25fc1867cb6"
          },
          {
            "name": "EXPIRED_SERVICE_REQUIRED_CONTRACT_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _EXPIRED_CONTACTS = [EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME]",
              "VAR _TOTAL = [CONTRACTS_VOLUME]",
              "RETURN",
              "DIVIDE(_EXPIRED_CONTACTS, _TOTAL, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ae89cfde-c6ff-42ac-bc59-184a7a249210"
          },
          {
            "name": "Measure 5",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "a3bfe14c-1c41-4002-951e-22e35f2e1b38"
          },
          {
            "name": "DYNAMIC_PO_VALUE_WITH_YOY",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [PO_VALUE]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _YOY = [PO_VALUE_YOY]",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "532366a4-5ac3-491a-9c9f-574a6db4ac4d"
          },
          {
            "name": "REQ_VOLUME",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE (DISTINCTCOUNT(REQ_HEADERS[AUCTION_HEADER_ID]))"
            ],
            "formatString": "#,0",
            "lineageTag": "53a9ae0a-14e4-4867-a792-41d444c50559"
          },
          {
            "name": "REQ_VALUE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE (SUM(REQ_HEADERS[APPROVAL_AMOUNT]))"
            ],
            "formatString": "#,0.00",
            "lineageTag": "ae5ee547-b471-4948-93fd-f2a0680c7d2b"
          },
          {
            "name": "DYNAMIC_RFP_VOLUME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABEL_K]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [REQ_VOLUME]",
              "VAR _FORMATTED_VOLUME = IF(_VOLUME<1000, TRUNC(_VOLUME,0), FORMAT(DIVIDE(_VOLUME,NUM), \"#0.0K\"))",
              "VAR _PY = CALCULATE([REQ_VOLUME], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "VAR _YOY = DIVIDE(_VOLUME - _PY, _PY, 0 )",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "70e1e1ff-a993-4045-9d40-fceccc678ef0"
          },
          {
            "name": "DYNAMIC_RFP_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = [REQ_VALUE]",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _PY = CALCULATE([REQ_VALUE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "VAR _YOY = DIVIDE(_VOLUME-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "3ccbb697-99c2-4f8a-a35e-1e1cc8498d06"
          },
          {
            "name": "DYNAMIC_APPROVED_RFP_VALUE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = CALCULATE([REQ_VALUE],  UPPER(REQ_HEADERS[NEG_APPROVAL_STATUS]) IN {\"APPROVED\"})",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0M\")",
              "VAR _PY = CALCULATE([REQ_VALUE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]), UPPER(REQ_HEADERS[NEG_APPROVAL_STATUS]) IN {\"APPROVED\"})",
              "VAR _YOY = DIVIDE(_VOLUME-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "61bb6d66-87da-4df2-b584-3f1d47fbb043"
          },
          {
            "name": "DYNAMIC_APPROVED_RFP_VOLUME",
            "expression": [
              "",
              "VAR NUM = [DATA_LABEL_K]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _VOLUME = CALCULATE([REQ_VOLUME],  UPPER(REQ_HEADERS[NEG_APPROVAL_STATUS]) IN {\"APPROVED\"})",
              "VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#,##0.0K\")",
              "VAR _PY = CALCULATE([REQ_VOLUME], SAMEPERIODLASTYEAR(DATE_TABLE[Date]), UPPER(REQ_HEADERS[NEG_APPROVAL_STATUS]) IN {\"APPROVED\"})",
              "VAR _YOY = DIVIDE(_VOLUME-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_VOLUME, _FORMATTED_YOY)"
            ],
            "lineageTag": "bc217739-f7ac-46af-94e0-6f15893765fb"
          },
          {
            "name": "DYNAMIC_RFP_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _CYCLE_TIME = CALCULATE(AVERAGE(REQ_HEADERS[CYCLE_TIME]), REQ_HEADERS[CYCLE_TIME]<>BLANK())",
              "VAR _PY = CALCULATE(AVERAGE(REQ_HEADERS[CYCLE_TIME]), SAMEPERIODLASTYEAR(DATE_TABLE[Date]), REQ_HEADERS[CYCLE_TIME]<>BLANK())",
              "//VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.#M\")",
              "VAR _YOY = DIVIDE(_CYCLE_TIME-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _CYCLE_TIME, _YOY)"
            ],
            "lineageTag": "e0a0842d-8f02-4a02-9f22-1f1b36861316"
          },
          {
            "name": "RFP_CONVERSION_RATE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _APPROVED_RFP = CALCULATE([REQ_VOLUME], ALL(REQ_HEADERS[NEG_APPROVAL_STATUS]), REQ_HEADERS[NEG_APPROVAL_STATUS] IN {\"APPROVED\"})",
              "VAR _TOTAL_RFP = CALCULATE([REQ_VOLUME], ALL(REQ_HEADERS[NEG_APPROVAL_STATUS]))",
              "RETURN",
              "DIVIDE(_APPROVED_RFP, _TOTAL_RFP, BLANK())"
            ],
            "lineageTag": "1c543524-e494-4884-aea8-1a7a3ad2394f"
          },
          {
            "name": "DYNAMIC_RFP_CONVERSION_RATE",
            "expression": [
              "",
              "VAR NUM = [DATA_LABLE_M]",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _CY = CALCULATE([RFP_CONVERSION_RATE])",
              "VAR _CONVERSION_RATE = FORMAT(_CY, \"0%\")",
              "//VAR _FORMATTED_VOLUME =  FORMAT(DIVIDE(_VOLUME,NUM), \"#0.#M\")",
              "VAR _PY = CALCULATE([RFP_CONVERSION_RATE], SAMEPERIODLASTYEAR(DATE_TABLE[Date]))",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY,0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _CONVERSION_RATE, _FORMATTED_YOY)"
            ],
            "lineageTag": "f89d0191-8587-4d7b-b89a-ab1a58bd374a"
          },
          {
            "name": "DYNAMIC_EXP_FARAH_RFP_VOLUME_VALUE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_EXP_FARAH_SELECTION[SELECTION_SORT_ORDER])",
              "VAR _EXP = CALCULATE([DYNAMIC_RFP_VOLUME_VALUE], REMOVEFILTERS(REQ_HEADERS[PR_ENTITY]), REQ_HEADERS[PR_ENTITY]=\"Experience Hub\")",
              "VAR _FARAH = CALCULATE([DYNAMIC_RFP_VOLUME_VALUE], REMOVEFILTERS(REQ_HEADERS[PR_ENTITY]), REQ_HEADERS[PR_ENTITY]<>\"Experience Hub\")",
              "RETURN",
              "IF(_SELECTION=1, _EXP, _FARAH)",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "59484d69-f98a-472b-b858-2ecae2542108"
          },
          {
            "name": "DYNAMIC_RFP_VOLUME_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[REQ_VOLUME],",
              "SEL = 2,[REQ_VALUE]",
              ")"
            ],
            "lineageTag": "596794cf-46b8-47e3-8beb-96223ac11abc"
          },
          {
            "name": "DYNAMIC_RFP_VOLUME_CREATION_CLOSED",
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_RFP_CUST_DATE[ID]),",
              "   1, CALCULATE([REQ_VOLUME], ALL(DATE_TABLE), REQ_HEADERS[CREATION_DATE]>=MIN_DATE,  REQ_HEADERS[CREATION_DATE]<=MAX_DATE, REQ_HEADERS[CREATION_DATE]<>BLANK()  ),",
              "   2, CALCULATE([REQ_VOLUME], ALL(DATE_TABLE), REQ_HEADERS[CLOSE_BIDDING_DATE]>=MIN_DATE,  REQ_HEADERS[CLOSE_BIDDING_DATE]<=MAX_DATE,REQ_HEADERS[CLOSE_BIDDING_DATE]<>BLANK() )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f17d435d-dda7-4e66-8dec-1d7aaf05010c"
          },
          {
            "name": "DYNAMIC_RFP_VALUE_CREATION_CLOSED",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MIN_DATE = CALCULATE(MIN(DATE_TABLE[Date]))",
              "VAR MAX_DATE = CALCULATE(MAX(DATE_TABLE[Date]))",
              "RETURN",
              "SWITCH(SELECTEDVALUE(PBI_RFP_CUST_DATE[ID]),",
              "   1, CALCULATE([REQ_VALUE], ALL(DATE_TABLE), REQ_HEADERS[CREATION_DATE]>=MIN_DATE,  REQ_HEADERS[CREATION_DATE]<=MAX_DATE, REQ_HEADERS[CREATION_DATE]<>BLANK()  ),",
              "   2, CALCULATE([REQ_VALUE], ALL(DATE_TABLE), REQ_HEADERS[CLOSE_BIDDING_DATE]>=MIN_DATE,  REQ_HEADERS[CLOSE_BIDDING_DATE]<=MAX_DATE,REQ_HEADERS[CLOSE_BIDDING_DATE]<>BLANK() )",
              ")"
            ],
            "lineageTag": "af6feeda-2fc0-4dce-a80d-08df02aa1bde"
          },
          {
            "name": "RFP_CYCLE_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(REQ_HEADERS[CYCLE_TIME]), REQ_HEADERS[CYCLE_TIME]<>BLANK())",
            "lineageTag": "18e55745-e10f-49d0-b087-871790ccb716"
          },
          {
            "name": "GRN_ON_TIME_DELIVERY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _TOTAL_GRN = SUMX( DISTINCT ( GRN_DETAILS[GRN_NUM] ) ,1)",
              "VAR _ON_TIME_GRN = CALCULATE( SUMX( DISTINCT ( GRN_DETAILS[GRN_NUM]),1), GRN_DETAILS[GRN_DATE]< GRN_DETAILS[EXPECTED_DELIVERY_DATE] )",
              "RETURN",
              "DIVIDE(_ON_TIME_GRN, _TOTAL_GRN, BLANK())",
              "",
              "// VAR _TOTAL_GRN = CALCULATE(DISTINCTCOUNT(GRN_DETAILS[GRN_NUM]))",
              "// VAR _ON_TIME_GRN = CALCULATE(DISTINCTCOUNT(GRN_DETAILS[GRN_NUM]), GRN_DETAILS[GRN_DATE]< GRN_DETAILS[EXPECTED_DELIVERY_DATE] )",
              "// RETURN",
              "// DIVIDE(_ON_TIME_GRN, _TOTAL_GRN, BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "de5ffbfb-143f-48a8-95eb-e8816c4fe4e8"
          },
          {
            "name": "ITEM_RETURN_RATE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _TOTAL_GRN = CALCULATE( SUMX( DISTINCT( GRN_DETAILS[GRN_NUM] ),1 ), GRN_DETAILS[GRN_TYPE] IN { \"DELIVER\"})",
              "VAR _ON_TIME_GRN = CALCULATE( SUMX( DISTINCT( GRN_DETAILS[GRN_NUM] ),1 ),  GRN_DETAILS[GRN_TYPE] IN {\"RETURN TO VENDOR\"})",
              "RETURN",
              "DIVIDE(_ON_TIME_GRN, _TOTAL_GRN, BLANK())",
              "",
              "// VAR _TOTAL_GRN = CALCULATE(DISTINCTCOUNT(GRN_DETAILS[GRN_NUM]), GRN_DETAILS[GRN_TYPE] IN { \"DELIVER\"})",
              "// VAR _ON_TIME_GRN = CALCULATE(DISTINCTCOUNT(GRN_DETAILS[GRN_NUM]),  GRN_DETAILS[GRN_TYPE] IN {\"RETURN TO VENDOR\"})",
              "// RETURN",
              "// DIVIDE(_ON_TIME_GRN, _TOTAL_GRN, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9f93a602-69d1-4548-a3bd-6274b10c2af1"
          },
          {
            "name": "ITEM_RETURN_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(GRN_DETAILS[VALUE_AED]),  GRN_DETAILS[GRN_TYPE] IN {\"RETURN TO VENDOR\"})"
            ],
            "lineageTag": "69d46f46-9f75-424b-9e20-bfddbb98c9f3"
          },
          {
            "name": "SUPPLIER_AVAILABILTY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _LAST_REFRESHED = [LAST_REFRESHED_DATE]",
              "VAR _ORDER_ITEM_QUANTITY = CALCULATE(SUM(PO_DETAILS[PO_LINE_QTY]), NOT (UPPER(PO_DETAILS[LINE_CLOSE_STATUS]) IN {\"CANCELLED\"}), PO_DETAILS[EXPECTED_DELIVERY_DATE]<_LAST_REFRESHED)",
              "VAR _GRN_QUANTITY = CALCULATE(SUM(GRN_DETAILS[GRN_QTY])/2)",
              "RETURN",
              "DIVIDE(_GRN_QUANTITY, _ORDER_ITEM_QUANTITY, BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9ddca38f-4445-467b-b227-da76a00dc14c"
          },
          {
            "name": "OVERDUE_PO",
            "expression": [
              "",
              "VAR _LAST_REFRESHED_DATE = [LAST_REFRESHED_DATE]",
              "VAR _PO_COUNT = CALCULATE(DISTINCTCOUNT(PO_DETAILS[PO_UNIQUE_KEY]), FILTER(PO_DETAILS, PO_DETAILS[EXPECTED_DELIVERY_DATE]<_LAST_REFRESHED_DATE && PO_DETAILS[GRN_DATE] =BLANK()))",
              " RETURN",
              " _PO_COUNT"
            ],
            "formatString": "0",
            "lineageTag": "b50d130a-0a30-419b-8d69-296a9d813a3c"
          },
          {
            "name": "DYNAMIC_GRN_ON_TIME_DELIVERY",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _MIN_DATE = CALCULATE((MIN(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE((MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _CY = [GRN_ON_TIME_DELIVERY]",
              "VAR _FORMATTED_CY =  FORMAT(_CY, \"0%\")",
              "VAR _PY = CALCULATE([GRN_ON_TIME_DELIVERY], ALL(PO_DETAILS[EXPECTED_DELIVERY_DATE]), PO_DETAILS[EXPECTED_DELIVERY_DATE]>= _PY_MIN_DATE && PO_DETAILS[EXPECTED_DELIVERY_DATE]<= _PY_MAX_DATE )",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_CY, _FORMATTED_YOY)",
              ""
            ],
            "lineageTag": "de0311bc-8c97-4dfb-b6bc-b716bf48513f"
          },
          {
            "name": "DYNAMIC_ITEM_RETURN_RATE",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _MIN_DATE = CALCULATE((MIN(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE((MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _CY = [ITEM_RETURN_RATE]",
              "VAR _FORMATTED_CY =  FORMAT(_CY, \"0.0%\")",
              "VAR _PY = CALCULATE([ITEM_RETURN_RATE], ALL(PO_DETAILS[EXPECTED_DELIVERY_DATE]), PO_DETAILS[EXPECTED_DELIVERY_DATE]>= _PY_MIN_DATE && PO_DETAILS[EXPECTED_DELIVERY_DATE]<= _PY_MAX_DATE )",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0.0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_CY, _FORMATTED_YOY)"
            ],
            "lineageTag": "5764daa9-4881-4e28-b35e-cd9483e4cd78"
          },
          {
            "name": "DYNAMIC_ITEM_RETURN_VALUE",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _DECIMAL = 1000000",
              "VAR _MIN_DATE = CALCULATE((MIN(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE((MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _CY = [ITEM_RETURN_VALUE]",
              "VAR _FORMATTED_CY =  FORMAT(DIVIDE(_CY, _DECIMAL), \"#,##0.0M\")",
              "VAR _PY = CALCULATE([ITEM_RETURN_VALUE], ALL(PO_DETAILS[EXPECTED_DELIVERY_DATE]), PO_DETAILS[EXPECTED_DELIVERY_DATE]>= _PY_MIN_DATE && PO_DETAILS[EXPECTED_DELIVERY_DATE]<= _PY_MAX_DATE )",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0.0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_CY, _FORMATTED_YOY)"
            ],
            "lineageTag": "dbc064fc-261d-46ac-b641-f2d8d5e08e3a"
          },
          {
            "name": "DYNAMIC_SUPPLIER_AVAILABILTY",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _MIN_DATE = CALCULATE((MIN(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE((MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _CY = [SUPPLIER_AVAILABILTY]",
              "VAR _FORMATTED_CY =  FORMAT(_CY, \"0.0%\")",
              "VAR _PY = CALCULATE([SUPPLIER_AVAILABILTY], ALL(PO_DETAILS[EXPECTED_DELIVERY_DATE]), PO_DETAILS[EXPECTED_DELIVERY_DATE]>= _PY_MIN_DATE && PO_DETAILS[EXPECTED_DELIVERY_DATE]<= _PY_MAX_DATE )",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0.0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_CY, _FORMATTED_YOY)"
            ],
            "lineageTag": "c0b4e89e-adf7-4b7e-9703-00fa6c681500"
          },
          {
            "name": "DYNAMIC_OVERDUE_PO",
            "expression": [
              "",
              "VAR _SELECTION = SELECTEDVALUE(DIM_SELECTION[SORT_ORDER])",
              "VAR _MIN_DATE = CALCULATE((MIN(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MIN_DATE = DATE(YEAR(_MIN_DATE)-1, MONTH(_MIN_DATE), DAY(_MIN_DATE))",
              "VAR _MAX_DATE = CALCULATE((MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE])), ALLSELECTED(PO_DETAILS[EXPECTED_DELIVERY_DATE]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE)-1, MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _CY = [OVERDUE_PO]",
              "VAR _FORMATTED_CY =  FORMAT(_CY, \"0,###\")",
              "VAR _PY = CALCULATE([OVERDUE_PO], ALL(PO_DETAILS[EXPECTED_DELIVERY_DATE]), PO_DETAILS[EXPECTED_DELIVERY_DATE]>= _PY_MIN_DATE && PO_DETAILS[EXPECTED_DELIVERY_DATE]<= _PY_MAX_DATE )",
              "VAR _YOY = DIVIDE(_CY-_PY, _PY, 0)",
              "VAR _FORMATTED_YOY = FORMAT(_YOY, \"0.0%\")",
              "RETURN",
              "IF(_SELECTION=1, _FORMATTED_CY, _FORMATTED_YOY)"
            ],
            "lineageTag": "45b0ee43-2804-436b-9989-008961492ffa"
          },
          {
            "name": "PROMISED_DATE_AVAILABLE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _YES = CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_NAME]), PO_DETAILS[EXPECTED_DELIVERY_DATE]<>BLANK()) ",
              "VAR _NO = CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_NAME]), PO_DETAILS[EXPECTED_DELIVERY_DATE]=BLANK()) ",
              "VAR _SELECTION= SELECTEDVALUE(DIM_YES_NO[Sort_Number])",
              "RETURN",
              "SWITCH(TRUE(),",
              "_SELECTION=1, _YES,",
              "_SELECTION=2, _NO",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "62288609-f0a2-49d9-b1a5-72e079cfe2dc"
          },
          {
            "name": "PROMISED_DATE_AVAILABLE_PO",
            "expression": [
              "",
              "VAR _YES = CALCULATE(DISTINCTCOUNT(PO_DETAILS[PO_UNIQUE_KEY]), PO_DETAILS[EXPECTED_DELIVERY_DATE]<>BLANK()) ",
              "VAR _NO = CALCULATE(DISTINCTCOUNT(PO_DETAILS[PO_UNIQUE_KEY]), PO_DETAILS[EXPECTED_DELIVERY_DATE]=BLANK()) ",
              "VAR _SELECTION= SELECTEDVALUE(DIM_YES_NO[Sort_Number])",
              "RETURN",
              "SWITCH(TRUE(),",
              "_SELECTION=1, _YES,",
              "_SELECTION=2, _NO",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "72c9e6d0-bfa8-4459-ab70-8b7192ff0c05"
          },
          {
            "name": "SUPPLIERS_DELIVERY",
            "expression": [
              "",
              "VAR _YES = CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_NAME]), PO_DETAILS[GRN_DATE]<>BLANK()) ",
              "VAR _NO = CALCULATE(DISTINCTCOUNT(PO_HEADERS[VENDOR_NAME]), PO_DETAILS[GRN_DATE]=BLANK()) ",
              "VAR _SELECTION= SELECTEDVALUE(DIM_YES_NO[Sort_Number])",
              "RETURN",
              "SWITCH(TRUE(),",
              "_SELECTION=1, _YES,",
              "_SELECTION=2, _NO",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "7940db46-b421-4396-b153-96550d282799"
          },
          {
            "name": "ITEM_OVERDUE_BY_TIME_FLAG",
            "expression": [
              "",
              "VAR _LAST_REFRESHED_DATE = [LAST_REFRESHED_DATE]",
              "VAR _PO_COUNT = CALCULATE(COUNT(PO_DETAILS[PO_LINE_UNIQUE_KEY]), FILTER(PO_DETAILS, PO_DETAILS[EXPECTED_DELIVERY_DATE]<_LAST_REFRESHED_DATE && PO_DETAILS[GRN_DATE] =BLANK()))",
              " RETURN",
              " _PO_COUNT"
            ],
            "formatString": "0",
            "lineageTag": "7afd134d-99dd-436e-bbda-e60a91c829d2"
          },
          {
            "name": "GRN_DELIVERED_QTY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(GRN_DETAILS[GRN_QTY])/2)",
            "lineageTag": "02507121-05ac-422c-9a03-c4714fddcf50"
          },
          {
            "name": "LATE_DELIVERY_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _TOTAL_DELIVERIES =",
              "    SUMX(DISTINCT ( PO_DETAILS[PO_LINE_UNIQUE_KEY] ),1 )",
              "VAR _LATE_DELIVARIES =",
              "    CALCULATE (",
              "        SUMX(DISTINCT ( PO_DETAILS[PO_LINE_UNIQUE_KEY] ),1 ),",
              "        FILTER (",
              "            PO_DETAILS,",
              "            (",
              "                PO_DETAILS[GRN_DATE] <> BLANK ()",
              "                    && PO_DETAILS[GRN_DATE] > PO_DETAILS[EXPECTED_DELIVERY_DATE]",
              "            )",
              "                || (",
              "                    PO_DETAILS[GRN_DATE] = BLANK ()",
              "                        && PO_DETAILS[EXPECTED_DELIVERY_DATE] < [LAST_REFRESHED_DATE]",
              "                )",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        _TOTAL_DELIVERIES <> 0,",
              "        DIVIDE ( _LATE_DELIVARIES + 0, _TOTAL_DELIVERIES, 0 ),",
              "        BLANK ()",
              "    )",
              "",
              "// VAR _TOTAL_DELIVERIES = CALCULATE(DISTINCTCOUNT(PO_DETAILS[PO_LINE_UNIQUE_KEY]))",
              "// VAR _LATE_DELIVARIES = CALCULATE(DISTINCTCOUNT(PO_DETAILS[PO_LINE_UNIQUE_KEY]), FILTER(PO_DETAILS, (PO_DETAILS[GRN_DATE]<>BLANK()&& PO_DETAILS[GRN_DATE]>PO_DETAILS[EXPECTED_DELIVERY_DATE]) || (PO_DETAILS[GRN_DATE]=BLANK() && PO_DETAILS[EXPECTED_DELIVERY_DATE]<[LAST_REFRESHED_DATE])))",
              "// RETURN",
              "// IF(_TOTAL_DELIVERIES<>BLANK(), DIVIDE(_LATE_DELIVARIES+0, _TOTAL_DELIVERIES, 0), BLANK())",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "757c7ce1-5903-4d05-90ca-2f9d2d3d8680"
          },
          {
            "name": "ACTIVE_TRADE_LICENSE_SUPPLIER",
            "expression": [
              "",
              "VAR _LAST_REFRESHED_DATE = [LAST_REFRESHED_DATE]",
              "VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NUMBER]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"ACTIVE\",ALL(SUPPLIER_BUS_CLASSFICATION[EXPIRATION_DATE]))",
              "RETURN",
              "_SUPPLIER_COUNT",
              "",
              "// VAR _LAST_REFRESHED_DATE = [LAST_REFRESHED_DATE]",
              "// VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NAME]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"ACTIVE\",ALL(SUPPLIER_EXPIRATION_DATE_TABLE[Date]))",
              "// RETURN",
              "// _SUPPLIER_COUNT",
              "",
              "// VAR _LAST_REFRESHED_DATE = [LAST_REFRESHED_DATE]",
              "// VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NAME]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"ACTIVE\")",
              "// RETURN",
              "// _SUPPLIER_COUNT",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5d2ce728-57a7-4cc3-84df-ad6d0e7e60f8"
          },
          {
            "name": "EXPIRED_TRADE_LICENSE_SUPPLIER",
            "expression": [
              "",
              "VAR _MAX_DATE = CALCULATE(MAX(SUPPLIER_EXPIRATION_DATE_TABLE[Date]), ALLSELECTED(SUPPLIER_EXPIRATION_DATE_TABLE))",
              "VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NUMBER]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"EXPIRED\",ALL(SUPPLIER_BUS_CLASSFICATION[EXPIRATION_DATE]))",
              "RETURN",
              "_SUPPLIER_COUNT",
              "",
              "// VAR _MAX_DATE = CALCULATE(MAX(SUPPLIER_EXPIRATION_DATE_TABLE[Date]), ALLSELECTED(SUPPLIER_EXPIRATION_DATE_TABLE))",
              "// VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NAME]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"EXPIRED\",ALL(SUPPLIER_EXPIRATION_DATE_TABLE[Date]))",
              "// RETURN",
              "// _SUPPLIER_COUNT",
              "",
              "",
              "// VAR _MAX_DATE = CALCULATE(MAX(SUPPLIER_EXPIRATION_DATE_TABLE[Date]), ALLSELECTED(SUPPLIER_EXPIRATION_DATE_TABLE))",
              "// VAR _SUPPLIER_COUNT = CALCULATE(DISTINCTCOUNT(SUPPLIER_BUS_CLASSFICATION[VENDOR_NAME]), SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG]=1 && UPPER(SUPPLIER_BUS_CLASSFICATION[LICENSE_STATUS])=\"EXPIRED\" )",
              "// RETURN",
              "// _SUPPLIER_COUNT",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c77bdd13-707f-4790-9897-fd056308b950"
          },
          {
            "name": "SUPPLIER_REGISTRATION_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGEX(SUPPLIER_MASTER, NETWORKDAYS(SUPPLIER_MASTER[REQUESTED_DATE], SUPPLIER_MASTER[APPROVED_DATE])-1), FILTER(SUPPLIER_MASTER, UPPER(SUPPLIER_MASTER[REGISTRATION_STATUS])=\"APPROVED\" )) ",
            "lineageTag": "9573268d-8171-4589-80b8-0d88088b9d3e"
          },
          {
            "name": "SUPPLIER_REGISTRATION_APPROVAL_BY_TIME",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _MIN_DATE = CALCULATE(MIN(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "RETURN",
              "CALCULATE([SUPPLIER_REGISTRATION_TIME], FILTER(SUPPLIER_MASTER, SUPPLIER_MASTER[APPROVED_DATE]>=_MIN_DATE && SUPPLIER_MASTER[APPROVED_DATE]<= _MAX_DATE))",
              ""
            ],
            "lineageTag": "63591256-ecc9-41cb-b67a-656b012615c3"
          },
          {
            "name": "SUPPLIER_REGISTRATION_COUNT",
            "expression": "CALCULATE(DISTINCTCOUNT(SUPPLIER_MASTER[VENDOR_NUMBER]), FILTER(SUPPLIER_MASTER, UPPER(SUPPLIER_MASTER[REGISTRATION_STATUS])=\"APPROVED\" ))",
            "formatString": "0",
            "lineageTag": "fdb4cb67-3e5f-49f5-a09e-ce15219645ba"
          },
          {
            "name": "SUPPLIER_REGISTRATION_APPROVAL_COUNT_BY_TIME",
            "expression": [
              "",
              "VAR _MIN_DATE = CALCULATE(MIN(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "RETURN",
              "CALCULATE([SUPPLIER_REGISTRATION_COUNT], FILTER(SUPPLIER_MASTER, SUPPLIER_MASTER[APPROVED_DATE]>=_MIN_DATE && SUPPLIER_MASTER[APPROVED_DATE]<= _MAX_DATE))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f53827bc-dce6-451a-80ac-f3109818c69d"
          },
          {
            "name": "REQ_SUPPLIER_NAME",
            "expression": [
              "",
              "VAR _SUPPLIER = CALCULATE(MIN(REQ_AWARD_ALLOCATIONS[SUPPLIER_NAME]), FILTER(REQ_AWARD_ALLOCATIONS, REQ_AWARD_ALLOCATIONS[BID_NUMBER] IN VALUES(REQ_DETAILS[BID_NUMBER])))",
              "RETURN",
              "IF(HASONEVALUE(REQ_HEADERS[AUCTION_HEADER_ID]), _SUPPLIER, BLANK())"
            ],
            "lineageTag": "d9172c61-c56f-4cf6-9a36-0ce493a8c2c9"
          },
          {
            "name": "QUALIFIED_SUPPLIERS",
            "expression": "CALCULATE(DISTINCTCOUNT(SUPPLIER_QUALIFICATIONS[SUPPLIER]), FILTER(SUPPLIER_QUALIFICATIONS, UPPER(SUPPLIER_QUALIFICATIONS[STATUS])=\"COMPLETED\"))",
            "formatString": "0",
            "lineageTag": "799749e8-638d-4197-88f5-00b868399aa6"
          },
          {
            "name": "QUALIFIED_SUPPLIER_PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _QUALIFIED_SUPPLIER = [QUALIFIED_SUPPLIERS]",
              "VAR _TOTAL_SUPPLIERS = CALCULATE(DISTINCTCOUNT(SUPPLIER_MASTER[UNIQUE_KEY]))",
              "RETURN",
              "DIVIDE(_QUALIFIED_SUPPLIER, _TOTAL_SUPPLIERS, BLANK())"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b3e6e7d6-4335-48a2-9b63-6248f06ea355"
          },
          {
            "name": "PR_IN_PROCESS_BUYER_INTERACTIVITY",
            "expression": [
              "",
              "VAR _BUYER_FILETED = ISFILTERED(PO_HEADERS[BUYER_NAME])",
              "VAR _FILTERED_BUYERS = VALUES(PO_HEADERS[BUYER_NAME])",
              "VAR _FILTERED_VALUE = IF(SELECTEDVALUE(PR_DETAILS[BUYER_NAME]) IN  _FILTERED_BUYERS , 1,BLANK())",
              "RETURN",
              "IF(_BUYER_FILETED=TRUE() , ",
              "CALCULATE(DISTINCTCOUNT(PO_HEADERS[BUYER_NAME]), ALL(PR_DETAILS), FILTER(PR_DETAILS, PR_DETAILS[BUYER_NAME] IN _FILTERED_BUYERS )),",
              "//IF(COUNTROWS(FILTER(PR_DETAILS,PR_DETAILS[BUYER_NAME] IN _FILTERED_BUYERS ))>0, 1, 0),",
              " 1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "638d09d5-f7ad-42bc-b803-b90a6a8c152a"
          },
          {
            "name": "CONTRACT_VOLUME_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [CONTRACTS_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a98c5a1b-86dc-46da-a6a3-896cf6d65115"
          },
          {
            "name": "CONTRACT_VALUE_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [CONTRACT_VALUE]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([CONTRACT_VALUE], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b496f016-6557-481c-9fa4-83ca339e9ae1"
          },
          {
            "name": "EXPIRED_CONTRACTS_VOLUME_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [EXPIRED_CONTRACTS_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([EXPIRED_CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29e8971f-8608-478a-9659-6a3410490407"
          },
          {
            "name": "EXPIRED_CONTRACTS_VALUE_YOY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [EXPIRED_CONTRACTS_VALUE]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([EXPIRED_CONTRACTS_VALUE], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b21408d6-7a9e-475c-b41e-d5d45a518974"
          },
          {
            "name": "EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME_YOY",
            "expression": [
              "",
              "VAR _CY = [EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([EXPIRED_SERVICE_REQUIRED_CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "00e724aa-30e6-4bae-9e89-826866c11713"
          },
          {
            "name": "EXPIRED_SERVICE_REQUIRED_CONTRACTS_VALUE_YOY",
            "expression": [
              "",
              "VAR _CY = [EXPIRED_SERVICE_REQUIRED_CONTRACTS_VALUE]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([EXPIRED_SERVICE_REQUIRED_CONTRACTS_VALUE], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "573b7980-d655-4591-a90f-536fd0a180ba"
          },
          {
            "name": "BPA_CONTRACTS_VOLUME_YOY",
            "expression": [
              "",
              "VAR _CY = [BPA_CONTRACTS_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([BPA_CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "844a8e63-8089-4437-bf74-47272d13b113"
          },
          {
            "name": "CPA_CONTRACTS_VOLUME_YOY",
            "expression": [
              "",
              "VAR _CY = [CPA_CONTRACTS_VOLUME]",
              "VAR _MAX_DATE = CALCULATE(MAX(CONTRACT_DATE_TABLE[Date]), ALLSELECTED(CONTRACT_DATE_TABLE[Date]))",
              "VAR _PY_MAX_DATE = DATE(YEAR(_MAX_DATE), MONTH(_MAX_DATE), DAY(_MAX_DATE))",
              "VAR _PY = CALCULATE([CPA_CONTRACTS_VOLUME], SAMEPERIODLASTYEAR(ALLSELECTED(CONTRACT_DATE_TABLE[DATE])), CONTRACT_DATE_TABLE[Date]<=_PY_MAX_DATE)",
              "RETURN",
              "IF(_PY=BLANK(), 0, (_CY-_PY)/_PY)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "446491ec-5170-4e8e-a0ba-3ffbd4e27d9d"
          },
          {
            "name": "PR_VALUE_INPROCESS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([PR_VALUE], FILTER(PR_DETAILS, PR_DETAILS[BUYER_AGEING_CATEGORY]<>BLANK() && PR_DETAILS[PO_EXIST]<>BLANK() ))"
            ],
            "lineageTag": "3c821f44-d311-4a24-bca6-8176f93f68ee"
          },
          {
            "name": "DYNAMIC_BUYER_INPROCESS_VALUE_VOLUME",
            "expression": [
              "",
              "VAR SEL = SELECTEDVALUE(DIM_VOL_VALUE[SORT_ORDER])",
              "RETURN",
              "SWITCH(TRUE(),",
              "SEL = 1,[PR_INPROCESS_PER_BUYER],",
              "SEL = 2,[PR_VALUE_INPROCESS]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f0fbb7ba-0f11-41d4-b98a-bfb9e73a16b8"
          },
          {
            "name": "PR_CONVERSION_AGEING_ONTARGET_TOTAL_",
            "expression": [
              "",
              "CALCULATE(SUMX(DIM_AGEING_DAYS, [PR_CONVERSION_BY_AGEING]),KEEPFILTERS(DIM_AGEING_DAYS[AGEING_COLOR_CODE] = 1))"
            ],
            "formatString": "#,0",
            "lineageTag": "9482248c-8887-4f7a-a7b8-1f3573560bb3"
          },
          {
            "name": "LAST_REFRESHED_DATE_TIMEZONE",
            "expression": [
              "",
              "VAR _DATETIME = FORMAT(VALUES('Last Refreshed Date'[Last_Refreshed_Date_GST_Zone]),\"dd-Mmm-yy hh:nn:ss AM/PM\") & \"  GST\"",
              "VAR _DISPLAY_TEXT = \"Data Last refreshed: \"",
              "RETURN",
              "_DISPLAY_TEXT & _DATETIME"
            ],
            "lineageTag": "daca4865-03fc-4bbd-bba8-0b0aacfdd225"
          },
          {
            "name": "REFRESH_DATE_TOOLTIP",
            "expression": "\"Report refreshes on daily basis for every 2 hours ( 8AM, 10AM, 12PM etc)\"",
            "lineageTag": "d3052e35-6d82-4989-8104-5d5b81bd3e89"
          }
        ],
        "partitions": [
          {
            "name": "All Measures-2d49114d-42f3-4632-811c-67be0808446b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_STATUS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c893e4c5-b6af-4e3d-a363-6a336a9813cd",
            "sortByColumn": "STATU_SORT_ORDER",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "STATU_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55cd73a2-8304-4c63-8729-1ddfdf649c09",
            "sourceColumn": "STATU_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "187576d7-2f56-435d-ae3c-45bc12dfc180",
        "partitions": [
          {
            "name": "DIM_STATUS-148a2a8f-8f4c-4e82-a3b6-3df852ca3dda",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Lcg7DoAgDADQq5jOLv5nAo1isDQNykC4/zUk1Te+UoCRnKe9M8wSHxOghxFqX+ALdC0GDWvIYtCYNARPtElj/iPdQhqLRvbpcGIytVl1PNl4ccCErTao9QU=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [STATUS = _t, STATU_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"STATUS\", type text}, {\"STATU_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_SOURCE_SYSTEM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SOURCE_SYSTEM_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82def5d6-b8c2-457a-9ac8-681d271e58d8",
            "sourceColumn": "SOURCE_SYSTEM_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE_SYSTEM_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "705ebcb5-049c-44b3-91d5-d9e9be7334d1",
            "sourceColumn": "SOURCE_SYSTEM_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "87955d79-a3fc-4668-b192-25e830745ef9",
        "partitions": [
          {
            "name": "DIM_SOURCE_SYSTEM-52176ddc-c01a-4e0f-9697-0205f01c5043",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g9ydPZxVdJRMlSK1YlW8nWM8PT1B3KNwFxXxxBXZyDPWCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SOURCE_SYSTEM_NAME = _t, SOURCE_SYSTEM_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SOURCE_SYSTEM_NAME\", type text}, {\"SOURCE_SYSTEM_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_SPEND_CATEGORY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SPEND_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "114c75fe-c26a-4e6e-a3bb-e62a5f510cf1",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "SPEND_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b41d9d7-da08-49a8-a045-9f728bcfa925",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "01dfa83f-8d16-476a-b06c-42e4c4a4b25b",
        "partitions": [
          {
            "name": "DIM_SPEND_CATEGORY-a1dfbe6d-1ef3-4b46-9769-4da9135993cb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckzKL0tVMPZV0lEyVIrViVYy9FUoyYcIGIEFjEwNvEFChiAhY7CQKVgAJAEUMgELGYBETEF8U6XYWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SPEND_CATEGORY = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SPEND_CATEGORY\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_VOL_VALUE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1b52d99-f9fe-4572-9d88-32d9cebdeea7",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be5a6388-e075-4a8e-9de0-76233ddaa80e",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5600579a-d97b-4e77-9b6b-7b02417f8595",
        "partitions": [
          {
            "name": "DIM_VOL_VALUE-167f2eb9-a2b1-4fb4-9e49-6121961a37d1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCsvPKc1NVdJRMlSK1QFyE3NKQTwjpdhYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CATEGORY = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CATEGORY\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_LINES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AUCTION_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f1cb6f1-b2a4-4d60-818f-c1aea753637b",
            "sourceColumn": "AUCTION_HEADER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DOCUMENT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a83109c7-4309-42a0-81a1-5542a9f7af98",
            "sourceColumn": "DOCUMENT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "LINE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44bdce0f-fcab-464d-bb53-f14dacba1098",
            "sourceColumn": "LINE_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "BU_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8427f23-df04-4006-ad1a-6a2a2f8278b4",
            "sourceColumn": "BU_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a470a041-d4f2-48c6-8a67-28a548b13e66",
            "sourceColumn": "ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "ITEM_DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f02b85e-279c-440b-8bd6-e892312e9703",
            "sourceColumn": "ITEM_DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f9b4aa9-7ac9-4a62-9f72-b1b220203fe5",
            "sourceColumn": "CATEGORY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "QUANTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "55f63212-e189-4cd4-a6f2-b701a936be26",
            "sourceColumn": "QUANTITY",
            "summarizeBy": "sum"
          },
          {
            "name": "UOM_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39e2802e-be7b-497f-83c1-4bd922515ac0",
            "sourceColumn": "UOM_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "REQUESTED_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16e5b272-1880-475a-bdb1-dc2945b96895",
            "sourceColumn": "REQUESTED_DELIVERY_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENT_PRICE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dabf1a49-4691-4f91-9f91-d5a958dad642",
            "sourceColumn": "CURRENT_PRICE",
            "summarizeBy": "sum"
          },
          {
            "name": "REQUISITION_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f8fdf30-9599-4209-b774-e9d8860fca2d",
            "sourceColumn": "REQUISITION_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_RUN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c2fed550-e0c5-4bc3-a888-6b72354e5994",
            "sourceColumn": "LAST_RUN_DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68ad21ce-651d-4311-87c6-a0edcd0a92e4",
        "partitions": [
          {
            "name": "REQ_LINES-1abf7525-6933-42d0-b47a-1d0432797b24",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXMIR_PON_AUCTION_LINES_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AUCTION_HEADER_ID\", type text}, {\"LAST_RUN_DATE\", type date}, {\"REQUESTED_DELIVERY_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_AGEING_DAYS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SPEND_CATEGORY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3041e6b-dc0d-4713-9ce9-07b8e7ac31a3",
            "sourceColumn": "SPEND_CATEGORY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "AGEING_DAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae24fdc1-d0cb-4451-ba0b-06f6bd05be31",
            "sortByColumn": "AGEING_DAYS_ID",
            "sourceColumn": "AGEING_DAYS",
            "summarizeBy": "none"
          },
          {
            "name": "AGEING_DAYS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b02ad373-3b0b-4ef4-9784-f7da3b34fc60",
            "sourceColumn": "AGEING_DAYS_ID",
            "summarizeBy": "count"
          },
          {
            "name": "AGEING_COLOR_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0935ce3-b0cb-440d-894d-7e6ba4bd4ac0",
            "sourceColumn": "AGEING_COLOR_CODE",
            "summarizeBy": "sum"
          },
          {
            "name": "COLOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eadd3e4d-923d-4493-a22c-82cfcfa51cb2",
            "sourceColumn": "COLOR_NAME",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ec251501-adb3-4719-a922-a08d3500e666",
        "partitions": [
          {
            "name": "DIM_AGEING_DAYS-a900026c-b3c4-48f0-b667-7e3a6c98376e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlXSUTJQKMlXMFVISawsBvIModi9KDU1TylWB6LGVBsmbwzFQakpYFkTmAnGBjAlJhhGgESMDeBmmKGZYQwzwwTuDHMMM0CKTBDusEQzwwhmhqUBSKsBhn6QAksDbZC4EZpeQ0J6DXHojQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SPEND_CATEGORY_ID = _t, AGEING_DAYS = _t, AGEING_DAYS_ID = _t, AGEING_COLOR_CODE = _t, COLOR_NAME = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SPEND_CATEGORY_ID\", Int64.Type}, {\"AGEING_DAYS\", type text}, {\"AGEING_DAYS_ID\", Int64.Type}, {\"AGEING_COLOR_CODE\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_APPROVAL_TIME_CATEGORIES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "APPROVAL_AGEING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "45da5754-3c00-4b37-aa0a-7a54c51499df",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "APPROVAL_AGEING",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e618ee1-2c28-4658-977b-2564b4f21271",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "382333a9-a2ea-4935-b72c-2497374a323b",
        "partitions": [
          {
            "name": "DIM_APPROVAL_TIME_CATEGORIES-614dbf7f-71d9-4bec-bd76-6ce2ff8d199b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlAoyVcwVtJRMlSK1YlWMgFxzYBcIzDXHMS1BHKNwVxDsGpDkHITiICxNpBtqhQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [APPROVAL_AGEING = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"APPROVAL_AGEING\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_OPEX_CAPEX",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1dfb3ad1-46fe-4a25-be00-604087d70ca0",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa8a820b-dc0e-48fa-8640-f1d537bf32c0",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "03d6c369-8a56-471d-a28a-9aebcb4c9b1f",
        "partitions": [
          {
            "name": "DIM_OPEX_CAPEX-f208b9fb-4ca6-474c-993e-559bb3bfa967",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8i9IrVDSUTJUitWJVnJOhPCMwDyn/JIMBZC8QkypgYGRmQJM2lgpNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CATEGORY = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CATEGORY\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_SELECTION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "719801d6-226d-4508-9e77-36fa17e9d65b",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cc4ddda-f76f-4978-9595-8d7476dc45ab",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5d4fe6c9-aec2-4f44-8d55-23d5909017b9",
        "partitions": [
          {
            "name": "DIM_SELECTION-3fbe360e-ed69-4b71-8fa0-c3ab3a8f9fdd",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W+jB3xlwgXgTEa4F4GxAvU9JRMlSK1QFLLgDiaSBaQRUobKQUGwsA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CATEGORY = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CATEGORY\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_PR_PO_SELECTION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PR_PO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7646737-0dec-4a7a-a51d-0ccdf61ae972",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "PR_PO",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40015c3d-39e4-44df-bb4b-3520f686835f",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "604e17a2-3750-4db5-9b8b-d3f79a17bfb1",
        "partitions": [
          {
            "name": "DIM_PR_PO_SELECTION-0bd8f585-ee3b-4a4d-a000-4ff8940b9b30",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCghS0lEyVIrVATL9gUwjpdhYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PR_PO = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PR_PO\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_PR_PROCUREMENT_PROCESS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e3a8c00-399b-4d2b-9077-7ac20ec31f0e",
            "sortByColumn": "ID",
            "sourceColumn": "VALUE",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41e51461-c9f1-40df-82e6-95365ef47c74",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "6d99ba02-3980-408b-b9dd-f59244dca0b7",
        "partitions": [
          {
            "name": "DIM_PR_PROCUREMENT_PROCESS-91859272-4271-4a10-8f1a-89b73695eee9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCghS0lEyVIrViVZyKq1MLQLyjMC8ILcA/SC3QCDfGMx3zs8rKUpMLgEKmIAFAvyBTFMwM7i0oCAnE6zZTCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [VALUE = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"VALUE\", type text}, {\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_EXP_FARAH_SELECTION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SELECTION_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e43261b-1d9d-48d6-b87f-f88b7226c637",
            "sortByColumn": "SELECTION_SORT_ORDER",
            "sourceColumn": "SELECTION_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SELECTION_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77b73054-e93e-43e4-adc3-f680d5c34d45",
            "sourceColumn": "SELECTION_SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7bb722e7-0cba-4d34-b8f1-46bf204523fb",
        "partitions": [
          {
            "name": "DIM_EXP_FARAH_SELECTION-802e39e7-00f3-4db3-89e9-c874c21f69a3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8s0sSsxRcEktLsnMSyzJzM8rVtJRMlSK1YFJuVYUpBZlpuYlp4JkjJRiYwE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SELECTION_CATEGORY = _t, SELECTION_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SELECTION_CATEGORY\", type text}, {\"SELECTION_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_STATUS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_STATUS_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7b597e5-fa18-4d0e-a958-acd84161639a",
            "sourceColumn": "PO_STATUS_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90969233-7430-4bc0-8936-4e1f5fd9a738",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_CREATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "be879de7-d3dd-4c4f-a803-48d75c833373",
            "sourceColumn": "ACTION_CREATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b0ba62c-82e6-45ae-8201-c658778e481c",
            "sourceColumn": "ACTION_CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_PERFORMED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c159e3ce-858e-4d64-ac80-29477d68b3f3",
            "sourceColumn": "ACTION_PERFORMED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34b6f2cb-5c20-4798-ade7-88cc29a8575c",
            "sourceColumn": "UPDATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "6314f8bd-9db0-4133-9754-9aeca03da17e",
            "sourceColumn": "UPDATED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "SEQUENCE_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e8059f8b-1e38-4a89-a430-f1f1e62ec498",
            "sourceColumn": "SEQUENCE_NUM",
            "summarizeBy": "sum"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33b36fad-e7f5-42ea-a804-436558d5c928",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "f8509e52-af65-490e-a6b4-033181c141e4",
            "sourceColumn": "APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fd66691-46e5-4ea7-a9cd-dd9abfa745a2",
            "sourceColumn": "APPROVED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9852fa0c-229c-49b0-bfee-8311963ad897",
            "sourceColumn": "ROLE",
            "summarizeBy": "none"
          },
          {
            "name": "COMMENTS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6348b8fd-de9b-4f65-90c9-030d8224c462",
            "sourceColumn": "COMMENTS",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e77267a3-da00-4343-a58a-81d210bfd189",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "ACTION_CREATED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[EMAIL], PO_STATUS[ACTION_CREATED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "a4d2badd-265e-4280-b8f1-375843f26d37",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ACTION_APPROVED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PO_STATUS[APPROVED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "b4c16589-61ec-4b41-8574-8f44ce32587f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ACTION_PERFORMED_BY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(EMPLOYEE_MASTER[NAME], EMPLOYEE_MASTER[UNIQUE_KEY], PO_STATUS[ACTION_PERFORMED_BY])",
            "isDataTypeInferred": true,
            "lineageTag": "9b4ae3b8-4a26-4c6b-94d9-281443d60ce3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "94eff0f4-06fc-454b-a891-75332a9ac3eb",
        "partitions": [
          {
            "name": "PO_STATUS-250cb500-0d1f-482c-9e54-7f6a2b135c18",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT \"\"UNIQUE_KEY\"\" \"\"PO_STATUS_UNIQUE_KEY\"\", #(lf)\"\"PO_UNIQUE_KEY\"\", #(lf)\"\"ACTION_CREATED_DATE\"\", #(lf)\"\"ACTION_CREATED_BY\"\",#(lf) \"\"ACTION_PERFORMED_BY\"\",#(lf) \"\"UPDATED_BY\"\",#(lf) \"\"UPDATED_DATE\"\",#(lf) \"\"SEQUENCE_NUM\"\",#(lf) \"\"STATUS\"\", #(lf)\"\"APPROVED_DATE\"\", #(lf)\"\"APPROVED_BY\"\",#(lf) \"\"ROLE\"\",#(lf) \"\"COMMENTS\"\",#(lf) \"\"SITE\"\" #(lf) FROM XXFLP_bi_PO_STATUS_ALL#(lf)\"]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"PO_STATUS_UNIQUE_KEY\", type text}, {\"PO_UNIQUE_KEY\", type text}, {\"ACTION_CREATED_DATE\", type date}, {\"UPDATED_DATE\", type date}, {\"APPROVED_DATE\", type date} })",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_MASTER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feee5797-ed52-4c12-bc63-e4d3f1b49d42",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce1620b-981f-4344-946c-94337015d89c",
            "sourceColumn": "VENDOR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "011bf73e-dad2-49f2-bc39-a4e6fda48a31",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c338cc1a-5fc7-4098-96c4-7bec24eb3e4b",
            "sourceColumn": "VENDOR_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "REGISTRATION_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4174ee67-01ca-4146-bd33-6ed218b79adf",
            "sourceColumn": "REGISTRATION_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "REG_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "428d8bb7-ccdc-4e80-b202-b99ea19fb370",
            "sourceColumn": "REG_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "INVITING_PROCUREMENT_BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4fb1fee-0a89-4936-bed7-98a8f92c76e5",
            "sourceColumn": "INVITING_PROCUREMENT_BU",
            "summarizeBy": "none"
          },
          {
            "name": "REGISTRATION_ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3959153-edeb-4934-92b3-889730147c14",
            "sourceColumn": "REGISTRATION_ENTITY",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe761110-407c-4abc-8fe6-fdfdb67cd6eb",
            "sourceColumn": "SUPPLIER_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15d7c1b8-ecaf-4a3a-8360-ef2785d925c6",
            "sourceColumn": "SUPPLIER_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "TAX_ORGANIZATION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "564b96c2-b0d2-4def-b400-2fa4ac848505",
            "sourceColumn": "TAX_ORGANIZATION_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "DD-Mmm-yy",
            "lineageTag": "dfd93e74-aa2c-4b61-a1b4-6c80bd48c575",
            "sourceColumn": "APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "REQUESTED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-Yy",
            "lineageTag": "b5265673-8676-4246-8669-408126eb7e87",
            "sourceColumn": "REQUESTED_DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a8959908-a42e-45fc-9a2c-626906ef1ff2",
        "partitions": [
          {
            "name": "SUPPLIER_MASTER-d324ec5f-efee-45a4-afad-5e24bd5cfe75",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT DISTINCT#(lf)UNIQUE_KEY, VENDOR_NUMBER, NAME, #(lf)VENDOR_TYPE, #(lf)REGISTRATION_STATUS,#(lf)REG_KEY,#(lf)ATTRIBUTE4 \"\"INVITING_PROCUREMENT_BU\"\",#(lf)REGISTRATION_ENTITY,#(lf)ATTRIBUTE5 \"\"SUPPLIER_CATEGORY\"\",#(lf)SUPPLIER_STATUS,#(lf)APPROVED_DATE,#(lf)REQUESTED_DATE,#(lf)TAX_ORGANIZATION_TYPE#(lf)FROM XXFLP_BI_SUPPLIERS_ALL#(lf)--WHERE TAX_ORGANIZATION_TYPE <> 'EMPLOYEE'\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{\"UNIQUE_KEY\", type text}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"INVITING_PROCUREMENT_BU\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{ \"INVITING_PROCUREMENT_BU\", \"REGISTRATION_ENTITY\"})",
                "in",
                "    #\"Replaced Value1\"",
                "    ",
                "// let",
                "//    Source = Oracle.Database(#\"SERVER_NAME(UAT)\", [HierarchicalNavigation=true, Query=\"SELECT DISTINCT#(lf)UNIQUE_KEY, VENDOR_NUMBER, NAME, #(lf)VENDOR_TYPE, #(lf)REGISTRATION_STATUS,#(lf)REG_KEY,#(lf)APPROVED_DATE, #(lf)REQUESTED_DATE,#(lf)ATTRIBUTE4 \"\"INVITING_PROCUREMENT_BU\"\",#(lf)REGISTRATION_ENTITY,#(lf)ATTRIBUTE5 \"\"SUPPLIER_CATEGORY\"\",#(lf)SUPPLIER_STATUS,#(lf)TAX_ORGANIZATION_TYPE#(lf)FROM XXFLP_BI_SUPPLIERS_ALL#(lf)--WHERE TAX_ORGANIZATION_TYPE <> 'EMPLOYEE'\"]),",
                "//     #\"Replaced Value\" = Table.ReplaceValue(Source,\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"INVITING_PROCUREMENT_BU\"}),",
                "//     #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"UNIQUE_KEY\", type text}}),",
                "//     #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{ \"INVITING_PROCUREMENT_BU\", \"REGISTRATION_ENTITY\"})",
                "// in",
                "//     #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_SPEND_RATIO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SPEND_RATIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4da517f5-98dc-4a92-907e-1a328f8bf064",
            "sortByColumn": "SPEND_RATIO_SORT_ORDER",
            "sourceColumn": "SPEND_RATIO",
            "summarizeBy": "none"
          },
          {
            "name": "SPEND_RATIO_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7dabb79d-61eb-45a6-bb1b-0b66a251e494",
            "sourceColumn": "SPEND_RATIO_SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "778a46a0-4e61-4be4-b899-cc7dc060bc29",
        "partitions": [
          {
            "name": "DIM_SPEND_RATIO-7279fee6-244b-4ff4-80d8-f0f01814d64c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WsjBQVchPUwguSM1LUdJRMlSK1YlWMkIVNFKKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SPEND_RATIO = _t, SPEND_RATIO_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SPEND_RATIO\", type text}, {\"SPEND_RATIO_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CONTRACT_DATE_TABLE",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "586f60dc63e54829814658cfeb9e2a3a"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dddacd0e-2050-4c01-b363-3338d022a661",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "16771f52-37dc-41f6-84da-f0c7fcdd3c6b",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1c026ab5-fcab-4b24-89cd-c3e8e1f69b0a",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month NO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ca34dfac-d2e5-48de-8157-235de8610641",
            "sourceColumn": "[Month NO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ShortMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dd3f0f3f-e3fb-495a-8db9-5671da2b4ffa",
            "sortByColumn": "Month NO",
            "sourceColumn": "[ShortMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3d735a6f-1edb-46bb-a8c9-12724b35cd7c",
            "sortByColumn": "YearMonthNum",
            "sourceColumn": "[Year-Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6b93f92-86b3-4a34-8c5b-de15b3b5b55c",
            "sourceColumn": "[YearMonthNum]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "HY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1f571f59-d4c7-48a6-841d-39091043aca7",
            "sourceColumn": "[HY]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WEEKDAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f524bcd4-bcef-4ac5-b14c-450111d0732c",
            "sourceColumn": "[WEEKDAY]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WEEKNUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3101374d-4b93-4e6c-99b2-eb3ce2c43a2e",
            "sourceColumn": "[WEEKNUM]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "dff7004e-43f9-487d-abe8-12e2c168f43e",
        "partitions": [
          {
            "name": "CONTRACT_DATE_TABLE-e14da7ba-55a8-4349-800a-23b885f6a946",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _MIN_DATE= DATE(2016, 1, 1)",
                "VAR _MAX_DATE= CALCULATE(MAX(PO_HEADERS[CONTRACT_START_DATE]))",
                "RETURN",
                "ADDCOLUMNS( ",
                "CALENDAR(_MIN_DATE,_MAX_DATE),",
                "\"Year\",YEAR([Date]),",
                "\"Month\",FORMAT([Date],\"MMMM\"),",
                "\"Month NO\",MONTH([Date]),",
                "\"ShortMonth\",FORMAT([Date],\"MMM\"),",
                "\"Year-Month\",FORMAT([Date],\"MMM\") & \"-\" & FORMAT([Date],\"YY\"),",
                "\"YearMonthNum\",  INT(FORMAT([Date],\"YY\") & FORMAT([Date],\"MM\")) ,",
                "\"HY\",ROUNDUP(DIVIDE(MONTH([Date]),6),0),",
                "\"WEEKDAY\", WEEKDAY([Date], 2),",
                "\"WEEKNUM\", WEEKNUM([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CONTRACT_EXPIRY_CATEGORY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EXPIRY_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2b3b979-63dd-4b77-b629-a0549ba346e2",
            "sortByColumn": "Expiry_Sort_order",
            "sourceColumn": "EXPIRY_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "Expiry_Sort_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "771791a6-41a6-4922-8628-29137a1c738c",
            "sourceColumn": "Expiry_Sort_order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e289c88c-ac26-464d-a851-0ebbe656b79c",
        "partitions": [
          {
            "name": "CONTRACT_EXPIRY_CATEGORY-84556e5a-3c0e-4946-be85-6957ec93d4d0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcq0oyCxKTVHSUTJUitWB8jPz0hUy8xSMDRRcEiuLgXJGmHKGCroKZnAFxhgKzEAKLOEKTDBNAMpbKPjm55VkgBSYYiiwACowNEKoMMNQYWikrZALkzZXio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [EXPIRY_CATEGORY = _t, Expiry_Sort_order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"EXPIRY_CATEGORY\", type text}, {\"Expiry_Sort_order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PBI_PR_CUST_DATE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7083968-d7d5-40da-9b46-c2f95db2c578",
            "sortByColumn": "ID",
            "sourceColumn": "Names",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8873e7f-54f1-437e-b950-0a90e42130fd",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "0930776c-f64c-4043-9e90-9df7e2ebf3f3",
        "partitions": [
          {
            "name": "PBI_PR_CUST_DATE-1b785212-4b9e-4be9-bc7d-2daefb40b4cb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCghScC5KTSzJzM9TcEksSVXSUTJUitUBSzgWFBTll6WmwCSMlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Names = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PBI_PO_CUST_DATE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8e6c88c-fc22-4068-b354-aaaaf17b7e87",
            "sortByColumn": "ID",
            "sourceColumn": "Names",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c1245f8-8f39-4ada-9e94-06f7e059fb5e",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "d3914bce-92ce-4960-96c9-c64ec80e8121",
        "partitions": [
          {
            "name": "PBI_PO_CUST_DATE-27853ce3-19a6-4792-b001-78e2c04b9d30",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCvBXcC5KTSzJzM9TcEksSVXSUTJUitUBSzgWFBTll6WmwCSMlGJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Names = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Names\", type text}, {\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PBI_CONTRACT_DATE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f752599d-cd87-4907-a28d-21a8807b6856",
            "sortByColumn": "ID",
            "sourceColumn": "Names",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e959ed2-796c-4896-8e75-4c7ecf00a5c3",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "9aba279d-743c-4429-b453-06a51cc1689c",
        "partitions": [
          {
            "name": "PBI_CONTRACT_DATE-c5d2dae4-7e63-4596-9626-73734d8b9ffc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs7PKylKTC5RCC5JLCpRcEksSVXSUTJUitVBknOtKMgsSk2ByRopxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Names = _t, ID = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PR_CURRENT_OWNER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d42a4e0-2925-4668-8762-704ba31fb1ea",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGNEDDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "535334bb-ab17-4d18-817d-5f49bde8245d",
            "sourceColumn": "ASSIGNEDDATE",
            "summarizeBy": "none"
          },
          {
            "name": "CREATEDDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "40b8dd51-5bed-4f9e-beda-176a080631c5",
            "sourceColumn": "CREATEDDATE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENT_ASSIGNEE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea39d75d-9408-4cea-859b-b05724fb5b05",
            "sourceColumn": "CURRENT_ASSIGNEE",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGNED_FROM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "333c3a84-bd0a-4b06-92d7-a2047c28b8c9",
            "sourceColumn": "ASSIGNED_FROM",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_POSITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CALCULATE(MIN(EMPLOYEE_MASTER[POSITION]), FILTER(EMPLOYEE_MASTER, EMPLOYEE_MASTER[DISPLAY_NAME]= PR_CURRENT_OWNER[CURRENT_ASSIGNEE]))",
            "isDataTypeInferred": true,
            "lineageTag": "f807befb-9aeb-4517-81ad-78c7cf791c48",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "466cd0cd-de4d-463e-be58-2fa62b4fd4c6",
        "partitions": [
          {
            "name": "PR_CURRENT_OWNER-647b349c-0d02-4062-883c-72495dd306f1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT  SUBSTR( IDENTIFICATIONKEY, #(lf)                INSTR(IDENTIFICATIONKEY, '_', 4, 1)+1, #(lf)                INSTR(IDENTIFICATIONKEY, '_', 5, 1) - INSTR(IDENTIFICATIONKEY, '_', 3, 1)-1  ) PR_UNIQUE_KEY,#(lf)                ASSIGNEESDISPLAYNAME CURRENT_ASSIGNEE,#(lf)                SUBSTR(ASSIGNEES, 1, INSTR(ASSIGNEES, ',', 1,1)-1 ) CURRENT_ASSIGNEE_EMAIL,#(lf)                ASSIGNEDDATE,#(lf)                CREATEDDATE,#(lf)                FROMUSERDISPLAYNAME ASSIGNED_FROM,#(lf)                TASKNUMBER,#(lf)                STAGE,#(lf)                APPROVERS#(lf)    FROM XXAPPS.XXFLP_BI_WF_TASK_ALL#(lf)    WHERE IDENTIFICATIONKEY LIKE  'REQ_%'#(lf)    AND CATEGORY = 'Purchase Requisitions'#(lf)    AND STATE ='ASSIGNED'\"]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"ASSIGNEDDATE\", type date}, {\"CREATEDDATE\", type date}, {\"TASKNUMBER\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type1\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"TASKNUMBER\", Order.Descending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows\", each ([APPROVERS] = null)),",
                "    #\"Grouped Rows\" = Table.Group(#\"Filtered Rows\", {\"PR_UNIQUE_KEY\"}, {{\"CURRENT_ASSIGNEE\", each List.Max([CURRENT_ASSIGNEE]), type nullable text}, {\"ASSIGNEDDATE\", each List.Max([ASSIGNEDDATE]), type nullable date}, {\"CREATEDDATE\", each List.Max([CREATEDDATE]), type nullable date}, {\"ASSIGNED_FROM\", each List.Max([ASSIGNED_FROM]), type nullable text}})",
                "in",
                "    #\"Grouped Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_CURRENT_OWNER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d5fdaf3-cfcc-46ed-9fa6-b821814e5c36",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENT_ASSIGNEE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fafe36e7-2e89-405a-a211-b997df5aa25d",
            "sourceColumn": "CURRENT_ASSIGNEE",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGNEDDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "7c582ff2-685c-4f3d-88c4-c944efb04490",
            "sourceColumn": "ASSIGNEDDATE",
            "summarizeBy": "none"
          },
          {
            "name": "CREATEDDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "23e069df-61f5-4757-a6d2-2fc32a90c5d9",
            "sourceColumn": "CREATEDDATE",
            "summarizeBy": "none"
          },
          {
            "name": "ASSIGNED_FROM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4442c705-343b-4963-9510-624d33624b6f",
            "sourceColumn": "ASSIGNED_FROM",
            "summarizeBy": "none"
          },
          {
            "name": "PO_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaade35d-19e7-4fd3-acd5-abead2d4dc05",
            "sourceColumn": "PO_HEADER_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9b554f75-9b44-4c82-a7f2-723b9e376a19",
        "partitions": [
          {
            "name": "PO_CURRENT_OWNER-2ecf3101-99ec-4ea9-b755-18fa03de6ead",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT  SUBSTR( IDENTIFICATIONKEY, #(lf)                INSTR(IDENTIFICATIONKEY, '_', 3, 1)+1, #(lf)                INSTR(IDENTIFICATIONKEY, '_', 5, 1) - INSTR(IDENTIFICATIONKEY, '_', 3, 1)-1  ) PO_UNIQUE_KEY,#(lf)                ASSIGNEESDISPLAYNAME CURRENT_ASSIGNEE,#(lf)                SUBSTR(ASSIGNEES, 1, INSTR(ASSIGNEES, ',', 1,1)-1 ) CURRENT_ASSIGNEE_EMAIL,#(lf)                ASSIGNEDDATE,#(lf)                CREATEDDATE,#(lf)                FROMUSERDISPLAYNAME ASSIGNED_FROM,#(lf)                TASKNUMBER,#(lf)                STAGE,#(lf)                PO_HEADER_ID,#(lf)                APPROVERS#(lf)    FROM XXAPPS.XXFLP_BI_WF_TASK_ALL#(lf)    WHERE (IDENTIFICATIONKEY LIKE  'PO_%' OR IDENTIFICATIONKEY LIKE  'PA_%')#(lf)    AND UPPER(CATEGORY) = 'PURCHASING'#(lf)    AND STATE ='ASSIGNED'#(lf)  \"]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"ASSIGNEDDATE\", type date}, {\"CREATEDDATE\", type date}, {\"PO_HEADER_ID\", type text}, {\"TASKNUMBER\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type1\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"TASKNUMBER\", Order.Descending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows\", each ([CURRENT_ASSIGNEE] <> \"Applications Development Framework Application Identity for Procurement\")),",
                "    #\"Grouped Rows\" = Table.Group(#\"Filtered Rows\", {\"PO_UNIQUE_KEY\"}, {{\"CURRENT_ASSIGNEE\", each List.Max([CURRENT_ASSIGNEE]), type nullable text}, {\"ASSIGNEDDATE\", each List.Max([ASSIGNEDDATE]), type nullable date}, {\"CREATEDDATE\", each List.Max([CREATEDDATE]), type nullable date}, {\"ASSIGNED_FROM\", each List.Max([ASSIGNED_FROM]), type nullable text}, {\"PO_HEADER_ID\", each List.Max([PO_HEADER_ID]), type nullable text}})",
                "in",
                "    #\"Grouped Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_APPROVER_AGEING",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1b0eb1a-9054-4a68-93e8-533877b71746",
            "sortByColumn": "AGEING_SORT_ORDER",
            "sourceColumn": "AGEING_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "AGEING_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc795fbc-fa4f-4b52-b6c0-99fd8e9887ff",
            "sourceColumn": "AGEING_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d0595292-084a-4afd-8a29-f6e1101fc8f0",
        "partitions": [
          {
            "name": "DIM_APPROVER_AGEING-ca46af1a-3428-439f-9489-b186d6039651",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"HcixEQAhCAXRVpyfngEciloLQw0m1/8ckO0+M1D7blvoYHg37Fwe8W89zwShACkQTtCEUaAFJ2EWHHqiFe4/\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [AGEING_CATEGORY = _t, AGEING_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AGEING_CATEGORY\", type text}, {\"AGEING_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_APPROVER_AGEING_PO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "648c934c-1681-4422-a17e-2c3d0d3a4857",
            "sortByColumn": "AGEING_SORT_ORDER",
            "sourceColumn": "AGEING_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "AGEING_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "29374a1d-bbc4-4898-8241-ce88d47fc7cb",
            "sourceColumn": "AGEING_SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3e6d953e-6b34-483d-8c49-dea8e1f3b95b",
        "partitions": [
          {
            "name": "DIM_APPROVER_AGEING_PO-5d323156-a8a1-421c-8fcf-5bd55b5ebc4a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DIM_APPROVER_AGEING",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AGREEMENT_WITH_PO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c413335e-80dc-4b31-bdab-e8dff27ffbd8",
            "sourceColumn": "PO_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a4bc768-6512-45be-8e87-5302cf2c08f8",
            "sourceColumn": "CONTRACT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "CONTRACT_UPLOAD_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "743bfb0f-3fdc-49b5-b663-1d5f7bb71d4c",
            "sourceColumn": "CONTRACT_UPLOAD_DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f7fa83fa-6454-4136-ac20-5409abdb416f",
        "partitions": [
          {
            "name": "AGREEMENT_WITH_PO-d1adda0f-4501-4abb-af2a-b88d8dca6941",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT DISTINCT TRIM(PO_NUMBER) CONTRACT_NUMBER,#(lf) TRIM(ATTRIBUTE1) PO_NUMBER, PO_CREATION_DATE CONTRACT_UPLOAD_DATE FROM XXFLP_BI_PO_HEADERS_ALL#(lf) WHERE UPPER(PO_TYPE)<>'PURCHASE ORDER'\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CONTRACT_UPLOAD_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_PO_COVERED",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8de2dfee-7c3f-4937-8cc3-ccc97bbef371",
            "sortByColumn": "Sort_order",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8036ebd-dbc7-4553-822e-1518dac95925",
            "sourceColumn": "Sort_order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f3170e80-176a-49f2-94bc-4c79f2e0dae3",
        "partitions": [
          {
            "name": "DIM_PO_COVERED-ab3687a2-2da8-4620-955a-3fdf96010543",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs4vSy1KTVEI8I8pNTAwMi9WKM8syVBIzs8rKUpMLlHIzFNwKy3OzM9T0lEyVIrViVbyy89TIEWXEViXM0zKNzU3HyhqrBQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Category\"}, {\"Column2\", \"Sort_order\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_CONTRACT_UPLOAD_AGEING",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "28649074-e1a3-4fae-ac91-fe4b29668703",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28de8539-4e15-47ed-8947-14bf42e15d7f",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "acfde1f5-422b-46ac-9d80-89bb077db0e2",
        "partitions": [
          {
            "name": "DIM_CONTRACT_UPLOAD_AGEING-1abea631-4554-4f86-9f47-2369fb4a8c6f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCs8sycjMUzBVcEmsLFbSUTJUitWJVnJKLSlPTc1TMFMoyVcwNoBJGqFIGhuCZM3gssZgWTMDbZiACVjAvyQjtQjENVWKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CATEGORY = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CATEGORY\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_Historical",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a71cd14a-3fc4-4f0b-b827-378aa91ca4ad",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ca28af2-3e66-4874-be41-87921a911665",
            "sourceColumn": "PO_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "LINE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d295e3a-c6cf-49e5-8b30-5dfa0f166a85",
            "sourceColumn": "LINE",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76718ced-a2be-4841-85d6-47f03b10d8ef",
            "sourceColumn": "SUPPLIER",
            "summarizeBy": "none"
          },
          {
            "name": "CLOSURE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "760f9143-2b1e-453a-ac53-3bc4392add8e",
            "sourceColumn": "CLOSURE_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "615be60f-2f77-4cb1-84a4-024a88283c66",
            "sourceColumn": "CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ea0d8a39-bce2-49e0-99ab-37cf572c0e66",
            "sourceColumn": "APPROVED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "BUYER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d02e1996-0e85-408b-8aec-9ada755a0877",
            "sourceColumn": "BUYER",
            "summarizeBy": "none"
          },
          {
            "name": "REQUISITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b43f758d-d701-4dcb-889d-b93c8ba645d7",
            "sourceColumn": "REQUISITION",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8b9534b-6fe9-430e-8614-a7c2449ec214",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "AMOUNT_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "86263bad-5d5d-4c47-943d-49e4d3af820f",
            "sourceColumn": "AMOUNT_AED",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "e3908913-0e29-4200-a626-9e645c9f6f00",
        "partitions": [
          {
            "name": "PO_Historical-aa1ba7bb-c6ee-4246-af70-c48ed300a36f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM PBI_PO_HISTORICAL_DATA\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{ {\"CREATION_DATE\", type date}, {\"APPROVED_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CONTRACT_EXPIRY_ACTION",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9f34e50995be4d699bef54bf1a536d8c"
          }
        ],
        "columns": [
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "032847f7-d8cd-49c2-8092-f9a41dd9bd0d",
            "sourceColumn": "PO_HEADERS[ATTRIBUTE5]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2e81dce5-bbac-464e-ad8a-c93304d87735",
        "partitions": [
          {
            "name": "CONTRACT_EXPIRY_ACTION-c283f935-b8ce-4f54-b75c-8122536bbbff",
            "mode": "import",
            "source": {
              "expression": "CALCULATETABLE(DISTINCT(PO_HEADERS[ATTRIBUTE5]), UPPER(PO_HEADERS[PO_TYPE])<>\"PURCHASE ORDER\", PO_HEADERS[ATTRIBUTE5]<>BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DIM_CONTRACT_EXPIRY_ACTION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CONTRACT_EXPIRY_ACTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0500f5b-42c6-4482-abd4-a269497905c4",
            "sortByColumn": "SORT_ORDER",
            "sourceColumn": "CONTRACT_EXPIRY_ACTION",
            "summarizeBy": "none"
          },
          {
            "name": "SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8971260e-8a2d-4bcd-9a30-fc136a619080",
            "sourceColumn": "SORT_ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "39eace7b-5135-4784-a0bd-94706d95cf8d",
        "partitions": [
          {
            "name": "DIM_CONTRACT_EXPIRY_ACTION-c8fa081a-9967-465f-8334-5e726cdfbbed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"JY1LDoMwDAWvYnlNF/0coEAPgEp3URZR6lauiI3yges3wPbNjJ4xOET9kc9wghfFwOIywR16DfNEmVWwwRvaxmCvklkKyxdGigt7qs2oJfptepDndOjXXW9LVniS0OqmKtb6wzFUfN5xN7THmkqYtx/oXKJ35Re09g8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CONTRACT_EXPIRY_ACTION = _t, SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CONTRACT_EXPIRY_ACTION\", type text}, {\"SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_BUYER_AGEING",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AGEING_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f20ab47-3f86-4db0-a120-080bb118a385",
            "sortByColumn": "AGEING_SORT_ORDER",
            "sourceColumn": "AGEING_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "AGEING_SORT_ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1bf7723-d968-451e-a31c-c316a8c99a1e",
            "sourceColumn": "AGEING_SORT_ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "93248faf-f873-4b55-b1e9-ff7f28982f89",
        "partitions": [
          {
            "name": "DIM_BUYER_AGEING-b5f336b9-a3c4-4885-b5a1-0019dfbab401",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlAoyVcwNlDSUTJUitWJVjI2BAmYgQSMwAJmBtpAtrFSbCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [AGEING_CATEGORY = _t, AGEING_SORT_ORDER = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AGEING_CATEGORY\", type text}, {\"AGEING_SORT_ORDER\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refreshed Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date Last Refreshed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1c0da374-1f9a-4737-90fa-194b7f8a1633",
            "sourceColumn": "Date Last Refreshed",
            "summarizeBy": "none"
          },
          {
            "name": "Last_Refreshed_Date_GST_Zone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy hh:nn:ss AM/PM",
            "lineageTag": "0b45feb8-9033-4aaa-b30b-51f13963661e",
            "sourceColumn": "Last_Refreshed_Date_GST_Zone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9ee2cdb5-9f47-48fb-b7e2-920bc68b6376",
        "partitions": [
          {
            "name": "Last Refreshed Date-0fbaefda-d573-4e63-b7eb-09150a600543",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(type table[Date Last Refreshed=date], {{DateTime.LocalNow()}}),",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"Last_Refreshed_Date_GST_Zone\", each DateTimeZone.SwitchZone( DateTimeZone.UtcNow() , +4,0)),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Date Last Refreshed\", type datetime}, {\"Last_Refreshed_Date_GST_Zone\", type datetimezone}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_DETAILS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AUCTION_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dca342de-1216-4747-b8ff-d45a6bc6188d",
            "sourceColumn": "AUCTION_HEADER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DOCUMENT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d829e92c-9449-49de-9203-1c486d467d1d",
            "sourceColumn": "DOCUMENT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a513b141-4e54-4a11-9d41-16a1dd4037c2",
            "sourceColumn": "VENDOR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d355f311-c719-485f-9f17-55af2189b0dc",
            "sourceColumn": "VENDOR_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_SITE_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2795e9db-7d12-4667-8d59-504c6d35409d",
            "sourceColumn": "VENDOR_SITE_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "PARTY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "134f33c4-0193-4ee5-a664-267b4a02b0f7",
            "sourceColumn": "PARTY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "ADDITIONAL_CONTACT_EMAIL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6abe37af-1567-4eee-bcd7-b8a0cecaa5bf",
            "sourceColumn": "ADDITIONAL_CONTACT_EMAIL",
            "summarizeBy": "none"
          },
          {
            "name": "ROUND_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a197a6f0-0be1-426e-92d0-51f5e298f7bb",
            "sourceColumn": "ROUND_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "BID_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "205061ff-e480-4ddf-b2e7-a9008dc80e00",
            "sourceColumn": "BID_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_RUN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9b157ca-a425-47df-a608-c48d2603359f",
            "sourceColumn": "LAST_RUN_DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "014839f1-6646-4d51-840f-69d3e13e836f",
        "partitions": [
          {
            "name": "REQ_DETAILS-f1ae7210-b2fc-4257-8b5e-3da6a92c4f61",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXMIR_PON_AUCTION_DETAILS_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AUCTION_HEADER_ID\", type text}, {\"VENDOR_ID\", type text}, {\"BID_NUMBER\", type text}, {\"LAST_RUN_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_APPROVALS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TASK_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c73dbff6-164e-4050-b484-336b0e60d57a",
            "sourceColumn": "TASK_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "VERSION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "88ef3b76-7174-4e46-bb3a-f6fb45930212",
            "sourceColumn": "VERSION",
            "summarizeBy": "sum"
          },
          {
            "name": "DOCUMENT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d135e95c-e5ad-4c48-bbb2-08d55bd3494f",
            "sourceColumn": "DOCUMENT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "NEG_TITLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfa8be6b-9a52-4dd7-93c1-6794a35d9c23",
            "sourceColumn": "NEG_TITLE",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6bebbe1-dd16-43a2-b7e7-47106d9652c9",
            "sourceColumn": "STATUS_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "OUTCOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2b483f1-f68a-4171-b641-15fdf424108d",
            "sourceColumn": "OUTCOME",
            "summarizeBy": "none"
          },
          {
            "name": "COMPLETED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "200cc614-d5e7-4523-a8a8-87902425ab36",
            "sourceColumn": "COMPLETED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "COMPLETED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7ed1f7ce-c9b5-4af3-bb00-ddf7899204e4",
            "sourceColumn": "COMPLETED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_RUN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "746e525a-004a-4278-aa68-0928294275c6",
            "sourceColumn": "LAST_RUN_DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "88e24c28-8a9f-40bf-afe0-1b8025d4305a",
        "partitions": [
          {
            "name": "REQ_APPROVALS-075baf6e-f95b-4b76-a1e2-bb4bdc2bd548",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXMIR_PON_APPROVAL_HISTORY_DETAILS#(lf)\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"TASK_NUMBER\", type text}, {\"COMPLETED_DATE\", type date}, {\"LAST_RUN_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_AWARD_ALLOCATIONS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AUCTION_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e062b2be-fde0-4baa-a47f-4fb306f44652",
            "sourceColumn": "AUCTION_HEADER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "BID_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a57933d-48dc-4e25-ba00-0707c331a69f",
            "sourceColumn": "BID_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "BID_LINE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca983680-4839-48bf-ba77-d87e8d774460",
            "sourceColumn": "BID_LINE_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "ORIG_REQ_LINE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa9cad65-d8bc-4ed9-b607-a36d7ead68cb",
            "sourceColumn": "ORIG_REQ_LINE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ORIG_REQ_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfb41ef7-9655-4d25-847e-a46907ac7daf",
            "sourceColumn": "ORIG_REQ_HEADER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ALLOCATED_QTY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c317e4d1-7ed9-40aa-b9a2-28e4f6330310",
            "sourceColumn": "ALLOCATED_QTY",
            "summarizeBy": "sum"
          },
          {
            "name": "SPLIT_REQ_LINE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "274fc439-724e-4824-8d31-fa2acb5ef1cc",
            "sourceColumn": "SPLIT_REQ_LINE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "AUCTION_LINE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "96d43a97-a959-4b28-b457-6a6f3dd3493c",
            "sourceColumn": "AUCTION_LINE_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "EXPORT_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0023db51-d1fd-4c6c-8f49-8eb0fbbc7330",
            "sourceColumn": "EXPORT_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CALCULATE(MIN(REQ_DETAILS[VENDOR_NAME]), FILTER(REQ_DETAILS, REQ_DETAILS[BID_NUMBER] = REQ_AWARD_ALLOCATIONS[BID_NUMBER]))",
            "isDataTypeInferred": true,
            "lineageTag": "c656c77a-eca4-46ee-98c8-7ca3f72705c4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7f7032f9-32cf-4cc8-81ee-7a3330936407",
        "partitions": [
          {
            "name": "REQ_AWARD_ALLOCATIONS-94d6b272-154c-42d8-b590-f07868acfea5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXFLP_BI_PON_AWARD_ALLOCATIONS\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AUCTION_HEADER_ID\", type text}, {\"BID_NUMBER\", type text}, {\"ORIG_REQ_LINE_ID\", type text}, {\"ORIG_REQ_HEADER_ID\", type text}, {\"SPLIT_REQ_LINE_ID\", type text}, {\"EXPORT_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_BUS_CLASSFICATION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VENDOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02d415c6-274e-40bd-ba15-5b0a4746736f",
            "sourceColumn": "VENDOR_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f57d13d6-dc09-484b-9795-eb47eede1bce",
            "sourceColumn": "VENDOR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "CLASSIFCATION_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64664ea9-2de8-44d3-be56-b26b0cdaf26c",
            "sourceColumn": "CLASSIFCATION_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "SUB_CLASSIFICATION_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd0c6082-f946-481a-8507-dcaf05e5ea6f",
            "sourceColumn": "SUB_CLASSIFICATION_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "CERTIFYING_AGENCY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1b30a66-665e-431e-8599-6034bd70567c",
            "sourceColumn": "CERTIFYING_AGENCY",
            "summarizeBy": "none"
          },
          {
            "name": "OTHER_CERTIFYING_AGENCY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cb9ed91-1f3c-4e63-8f3b-d72ff5d5f6d5",
            "sourceColumn": "OTHER_CERTIFYING_AGENCY",
            "summarizeBy": "none"
          },
          {
            "name": "CERTIFICATE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50d897e5-0f68-44d4-8b88-4af2d2913070",
            "sourceColumn": "CERTIFICATE_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "77e72f97-f068-4c3d-9f64-473b2ddefb5e",
            "sourceColumn": "START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPIRATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "lineageTag": "6e1a7d73-7b02-4d3c-9f50-e35097d1667e",
            "sourceColumn": "EXPIRATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "0c58570a-840f-4818-b443-caa23789fbd2",
            "sourceColumn": "UPDATE_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPORT_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1853042c-b906-4224-a0df-58d3d2c5a99d",
            "sourceColumn": "EXPORT_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28bad8c1-9bad-4354-987c-341c68451e1e",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24e5641e-2ab0-4339-ab87-739314c5ceb9",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "405e47a5-0393-4f77-9bea-1fbcd74bb61e",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e121be86-4418-4ad4-8c4d-0c6537ad24eb",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95697527-eb62-49c9-99c4-3a77819cc2c0",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          },
          {
            "name": "LICENSE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(SUPPLIER_BUS_CLASSFICATION[CERTIFICATION_EXPDATE_MAX]< [LAST_REFRESHED_DATE], \"EXPIRED\", \"ACTIVE\")",
            "isDataTypeInferred": true,
            "lineageTag": "342732b6-1df9-42ec-95c3-4c48290e51d7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TRADE_LICENSE_EXPIRED_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _DIFF = DATEDIFF( [LAST_REFRESHED_DATE], SUPPLIER_BUS_CLASSFICATION[CERTIFICATION_EXPDATE_MAX], DAY)",
              "RETURN",
              "IF(SUPPLIER_BUS_CLASSFICATION[TRADE_LICENSE_FLAG] =1 , ",
              "",
              "SWITCH(TRUE(),",
              "_DIFF<=0, 1,",
              "_DIFF>0 && _DIFF<=30, 2,",
              "_DIFF>30 && _DIFF<=60, 3,",
              "_DIFF>60 && _DIFF<=90, 4,",
              "_DIFF>90 && _DIFF<=240, 5,",
              "_DIFF>240 && _DIFF<=365, 6,",
              "_DIFF>365, 7",
              "))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3565aadf-cc08-49ac-b09c-9db020cf1373",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TRADE_LICENSE_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(SUPPLIER_BUS_CLASSFICATION[CLASSIFCATION_NAME] IN VALUES(DIM_LICENSES[LICENSE_NAME]), 1, 0 )",
              "",
              "//IF(SUPPLIER_BUS_CLASSFICATION[CLASSIFCATION_NAME] IN {\"CERTIFICATE OF INCORPORATION\", \"COMMERCIAL LICENSE\", \"LETTER OF INCORPORATION\", \"TRADE LICENSE CERTIFICATION\"}, 1, 0 )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fa27f63a-cda7-4d62-b9d4-2f644a475bcd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CERTIFICATION_EXPDATE_MAX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "CALCULATE(MAX(SUPPLIER_BUS_CLASSFICATION[EXPIRATION_DATE]),ALLEXCEPT(SUPPLIER_BUS_CLASSFICATION,SUPPLIER_BUS_CLASSFICATION[VENDOR_NAME],SUPPLIER_BUS_CLASSFICATION[CLASSIFCATION_NAME]))"
            ],
            "formatString": "dd-mmm-yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "de075524-5419-4a98-b2b5-aac0d2b9912d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CERTIFICATION_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(SUPPLIER_BUS_CLASSFICATION[EXPIRATION_DATE]< [LAST_REFRESHED_DATE], \"EXPIRED\", \"ACTIVE\")",
              "",
              "// IF(SUPPLIER_BUS_CLASSFICATION[EXPIRATION_DATE]< SUPPLIER_BUS_CLASSFICATION[START_DATE], \"EXPIRED\", \"ACTIVE\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "413e2951-286e-4d7c-a61a-a995a3205714",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "4488b74a-0379-4bf9-8109-655a4fe3247e",
        "partitions": [
          {
            "name": "SUPPLIER_BUS_CLASSFICATION-b816b779-9c98-4cde-9018-bf98456db15c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXFLP_BI_SUPPLIER_BUS_CLASS_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"START_DATE\", type date}, {\"EXPIRATION_DATE\", type date}, {\"UPDATE_DATE\", type date}, {\"EXPORT_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_INITIATIVES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VENDOR_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "237dc1dc-dbfb-4796-b746-509495959061",
            "sourceColumn": "VENDOR_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdde3cfe-6b76-47f0-93e2-962abc771e9b",
            "sourceColumn": "VENDOR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "INITIATIVE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60528a3f-2830-40d6-8790-b037c8556628",
            "sourceColumn": "INITIATIVE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "INITIATIVE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82b87bfe-90f0-4c5c-8f4f-b1bd304e7d7a",
            "sourceColumn": "INITIATIVE_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "TITLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48f35e65-6229-4329-83b4-cb1e805fe09e",
            "sourceColumn": "TITLE",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "672df93d-8745-4f2a-9203-ba3bc45fa11d",
            "sourceColumn": "DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "293491fd-a349-4b1a-8e1d-0ebd02ba535e",
            "sourceColumn": "TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc70f3df-c1a4-4c9e-b892-2485f6e9ccd9",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "INTERNAL_SURVEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a316cf2d-e4c7-4eb4-84fd-a6ec8ace5ac8",
            "sourceColumn": "INTERNAL_SURVEY",
            "summarizeBy": "none"
          },
          {
            "name": "LAUNCH_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy",
            "lineageTag": "f1f08a36-f6b2-4b49-b074-8631fe68af83",
            "sourceColumn": "LAUNCH_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "COMPLETED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy",
            "lineageTag": "3e3da64f-520c-4f29-9e58-bdd2bf6aab08",
            "sourceColumn": "COMPLETED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "INITIATIVE_OWNER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc68cace-7a03-4c32-b5c4-085bdbf49ea9",
            "sourceColumn": "INITIATIVE_OWNER",
            "summarizeBy": "none"
          },
          {
            "name": "UPDATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9f8dcf7f-3096-4e99-b40f-dee83c590714",
            "sourceColumn": "UPDATE_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "AUTOMATICALLY_CREATED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f66ebcc8-9763-4979-9138-3227dcc96058",
            "sourceColumn": "AUTOMATICALLY_CREATED",
            "summarizeBy": "none"
          },
          {
            "name": "CREATION_SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8db5a28d-00c9-4198-a616-8b11203ec160",
            "sourceColumn": "CREATION_SOURCE",
            "summarizeBy": "none"
          },
          {
            "name": "PROCUREMENT_BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac4e388-8178-4cc3-afa8-5f7ca9820e61",
            "sourceColumn": "PROCUREMENT_BU",
            "summarizeBy": "none"
          },
          {
            "name": "EXPORT_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83c2a0ee-0cd6-4b44-9133-ecf2fa8e1206",
            "sourceColumn": "EXPORT_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "167fed8e-639f-4968-bc67-884452cda353",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da83de47-4db2-46a0-b9c5-3427e013a397",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad2b019f-cc7b-4183-8208-5b6d8a5ecaff",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2527124-2d9d-4e99-91a5-6653f8c7fee5",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e03f7092-6ceb-40d0-b4a8-1e6997635edc",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cee350ac-8f42-440b-8a82-ef6b7740068c",
        "partitions": [
          {
            "name": "SUPPLIER_INITIATIVES-b0a6752e-af2e-491b-bf13-0a1c085ffe2f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXFLP_BI_SUPPLIER_INITIATIVES_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"INITIATIVE_UNIQUE_KEY\", type text}, {\"LAUNCH_DATE\", type date}, {\"COMPLETED_DATE\", type date}, {\"UPDATE_DATE\", type date}, {\"EXPORT_DATE\", type date}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"PROCUREMENT_BU\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_QUALIFICATIONS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "QUALIFICATION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9538204a-85b0-467e-bb64-a98877345ed7",
            "sourceColumn": "QUALIFICATION_ID",
            "summarizeBy": "none"
          },
          {
            "name": "QUALIFICATION_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd8a95e1-1659-4b77-b863-93a1f6276d10",
            "sourceColumn": "QUALIFICATION_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "QUALIFICATION_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50ce10e2-62f2-468c-ba77-20eb953fe9f3",
            "sourceColumn": "QUALIFICATION_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "OWNER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e23a93eb-6ffa-4d43-a2ae-7e79422d15a0",
            "sourceColumn": "OWNER",
            "summarizeBy": "none"
          },
          {
            "name": "START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "c45c0362-512e-4bb8-a6a1-81e2e0becf0b",
            "sourceColumn": "START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "3a91d533-c73d-4f2d-85c5-9d5eb0e9bcbe",
            "sourceColumn": "END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d66dc4af-9efa-41d9-b16f-3d3a18c9996c",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "PROCUREMENT_BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eebbf928-fdd7-4d84-9570-7b73fb564390",
            "sourceColumn": "PROCUREMENT_BU",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7789882e-a861-489e-a490-de6d85f35bb5",
            "sourceColumn": "SUPPLIER",
            "summarizeBy": "none"
          },
          {
            "name": "SUPPLIER_CONTACT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c82d65-0d42-4c57-bc79-217d372c7060",
            "sourceColumn": "SUPPLIER_CONTACT",
            "summarizeBy": "none"
          },
          {
            "name": "QUALIFICATION_OUTCOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e815593-100a-4429-9093-b3277ee87a3d",
            "sourceColumn": "QUALIFICATION_OUTCOME",
            "summarizeBy": "none"
          },
          {
            "name": "INITIATIVE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15976969-46f6-4221-bf4e-71df69be709b",
            "sourceColumn": "INITIATIVE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "EVALUATION_END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "329e870e-5cd4-442d-93e8-dafaa8934b77",
            "sourceColumn": "EVALUATION_END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPORT_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "82071b91-126b-42b3-8c81-f7027f77ac98",
            "sourceColumn": "EXPORT_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3455c2ac-ba72-485d-946f-a3627d6036dc",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4424e05f-7fb4-4989-a794-24738866cd1c",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8dd86be-9cb0-4ffb-ab64-c9f7fa4a6a12",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3b67c97-4858-4a0a-ac0e-b40ec39f669a",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1de1e0aa-a9ae-4ed2-9eff-50f5b415ca89",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "488516b2-79ed-40cf-946a-7235e7602658",
        "partitions": [
          {
            "name": "SUPPLIER_QUALIFICATIONS-30e8e613-652c-4c73-8e4c-ea66bfb075a8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM XXFLP_BI_SUPPLIER_QUALIFICATIONS_ALL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"QUALIFICATION_ID\", type text}, {\"START_DATE\", type date}, {\"END_DATE\", type date}, {\"EVALUATION_END_DATE\", type date}, {\"EXPORT_DATE\", type date}, {\"INITIATIVE_UNIQUE_KEY\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"PROCUREMENT_BU\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_PR_LINK",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PR_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f285fc1-1bd9-445b-a038-dcfac01bc48d",
            "sourceColumn": "PR_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTMENT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "846119f8-ff1d-40a0-9481-b720a2a7d67e",
            "sourceColumn": "DEPARTMENT_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "LEISURE_FACILITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82dbf7fa-958f-467c-97bf-a18c2348511a",
            "sourceColumn": "LEISURE_FACILITY",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f9442c1-3c38-4523-b5c8-94fbbbde8b11",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "AUCTION_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea3f97f6-080f-4f67-8e30-e22d6bc51c74",
            "sourceColumn": "AUCTION_HEADER_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ef720d4f-c90e-4a4c-a2d8-d367e6ecd562",
        "partitions": [
          {
            "name": "REQ_PR_LINK-357f97b8-0862-4e40-abd6-a664037a4be8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"#(lf)SELECT #(lf)DISTINCT D.AUCTION_HEADER_ID, #(lf)--UNIQUE_KEY \"\"PR_LINE_UNIQUE_KEY\"\",#(lf)PR_UNIQUE_KEY,#(lf)B.DEPARTMENT_NAME,#(lf)C.LEISURE_FACILITY,#(lf)SITE#(lf)FROM XXFLP_BI_PR_DETAILS_ALL A#(lf)LEFT OUTER JOIN DIM_DEPARTMENT B#(lf)ON A.DEPARTMENT = B.DEPARTMENT_ID#(lf)LEFT OUTER JOIN DIM_LEISURE_FACILITY C#(lf)ON A.ENTITY = C.FACILITY_ID#(lf)LEFT OUTER JOIN XXMIR_PON_AUCTION_HEADERS_ALL D#(lf)ON A.NEGOTIATION_NUMBER = D.DOCUMENT_NUMBER#(lf)WHERE NEGOTIATION_NUMBER IS NOT NULL\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PR_UNIQUE_KEY\", type text}, {\"AUCTION_HEADER_ID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GRN_DETAILS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aea39822-4f01-4427-9486-c6f16b7f1039",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "575ce76a-0249-4bc3-a166-39dced67a333",
            "sourceColumn": "GRN_NUM",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy",
            "lineageTag": "50c6fdee-e111-45e0-9cb9-c937e161f901",
            "sourceColumn": "GRN_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_LAST_MODIFIED_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy",
            "lineageTag": "d9fcc534-f815-4a61-bfe3-53b3eae596d1",
            "sourceColumn": "GRN_LAST_MODIFIED_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_QTY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f51098d8-7f8f-4102-8f8f-7b075e57954f",
            "sourceColumn": "GRN_QTY",
            "summarizeBy": "sum"
          },
          {
            "name": "UNIT_OF_MEASURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40a1066d-baf4-4819-b47f-2d445d234a0d",
            "sourceColumn": "UNIT_OF_MEASURE",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c445e92-2c60-437b-8085-e97c28bca602",
            "sourceColumn": "GRN_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "PARENT_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "345fd9a8-2609-4527-b417-46171ee9b13b",
            "sourceColumn": "PARENT_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_INSP_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1887de31-221d-4536-b6de-822a35a61746",
            "sourceColumn": "GRN_INSP_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "GRN_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b75f180e-0092-4e07-a3d9-127488d5d64b",
            "sourceColumn": "GRN_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "PO_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1fe2f5b-82ec-467a-9f83-35456c2ad57d",
            "sourceColumn": "PO_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_LINE_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34e19741-c33a-463a-adb8-a0d1a9b3e2f3",
            "sourceColumn": "PO_LINE_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_SHIPMENT_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b48e49a9-41b5-49ab-a492-a75333cb05d7",
            "sourceColumn": "PO_SHIPMENT_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "PO_DISTRIBUTION_UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9c1fcc3-df76-41a2-b397-ce3ebaaab2a3",
            "sourceColumn": "PO_DISTRIBUTION_UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "RETURN_REASON",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9c94567-371b-496d-b7a4-9831d94b4957",
            "sourceColumn": "RETURN_REASON",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bebbcd62-f8c3-4efe-9e7f-35e5bb0985e3",
            "sourceColumn": "CURRENCY_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "EXCHANGE_RATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b44d050e-8874-46c5-968a-85d2d70baf23",
            "sourceColumn": "EXCHANGE_RATE",
            "summarizeBy": "sum"
          },
          {
            "name": "ATTRIBUTE1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c9a8fa7-d81d-4f9d-91fc-2e42bc046759",
            "sourceColumn": "ATTRIBUTE1",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cfb01fa-e157-4fbc-b27d-db7e8b19289f",
            "sourceColumn": "ATTRIBUTE2",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4df05d0f-113c-40c3-a90b-33bd027a38b0",
            "sourceColumn": "ATTRIBUTE3",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43341816-7b65-4801-8dbb-147506cb69a0",
            "sourceColumn": "ATTRIBUTE4",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe431233-d85d-4ada-88ad-397601329899",
            "sourceColumn": "ATTRIBUTE5",
            "summarizeBy": "none"
          },
          {
            "name": "CREATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5debb26c-6125-4381-b87e-18b6a84f4bb7",
            "sourceColumn": "CREATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-yy",
            "lineageTag": "b58d115c-e9d5-4507-8a52-b86e6c90e488",
            "sourceColumn": "CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_UPDATED_BY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fbf25b7-4d11-4e2a-bc71-2b273267a86e",
            "sourceColumn": "LAST_UPDATED_BY",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_UPDATE_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7b94c001-8419-490c-a262-a66a1c995bc1",
            "sourceColumn": "LAST_UPDATE_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cda7883-5bc9-4c80-a8a8-f4fcfae1fdee",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "EXPECTED_DELIVERY_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "CALCULATE(MAX(PO_DETAILS[EXPECTED_DELIVERY_DATE]), FILTER(PO_DETAILS, PO_DETAILS[PO_LINE_UNIQUE_KEY]= GRN_DETAILS[PO_LINE_UNIQUE_KEY]))",
            "formatString": "dd-Mmm-yy",
            "isDataTypeInferred": true,
            "lineageTag": "d68753ea-db9b-40d3-863c-15ea28b91ed7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "UNIT_PRICE_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "784dcfde-7a11-464a-8bf2-d94268eb98fa",
            "sourceColumn": "UNIT_PRICE_AED",
            "summarizeBy": "sum"
          },
          {
            "name": "VALUE_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5dd6277c-66ad-471d-81fb-4014b573e800",
            "sourceColumn": "VALUE_AED",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "43533b62-48d7-4e88-814b-d41b13bbbfa3",
        "partitions": [
          {
            "name": "GRN_DETAILS-da255f92-97f5-47e3-9f3e-e04cfb4a3cbd",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"#(lf)SELECT #(lf)A.UNIQUE_KEY,#(lf)GRN_NUM,#(lf)GRN_DATE,#(lf)GRN_LAST_MODIFIED_DATE,#(lf)CASE WHEN GRN_TYPE IN ('RETURN TO RECEIVING','RETURN TO VENDOR') THEN GRN_QTY* -1#(lf)ELSE GRN_QTY#(lf)END GRN_QTY,#(lf)UNIT_OF_MEASURE,#(lf)GRN_TYPE,#(lf)PARENT_UNIQUE_KEY,#(lf)GRN_INSP_STATUS,#(lf)GRN_STATUS,#(lf)PO_UNIQUE_KEY,#(lf)PO_LINE_UNIQUE_KEY,#(lf)PO_SHIPMENT_UNIQUE_KEY,#(lf)PO_DISTRIBUTION_UNIQUE_KEY,#(lf)RETURN_REASON,#(lf)CURRENCY_CODE,#(lf)EXCHANGE_RATE,#(lf)ATTRIBUTE1,#(lf)ATTRIBUTE2,#(lf)ATTRIBUTE3,#(lf)ATTRIBUTE4,#(lf)ATTRIBUTE5,#(lf)CREATED_BY,#(lf)CREATION_DATE,#(lf)LAST_UPDATED_BY,#(lf)LAST_UPDATE_DATE,#(lf)SITE,#(lf)B.UNIT_PRICE_AED \"\"UNIT_PRICE_AED\"\",#(lf)GRN_QTY * B.UNIT_PRICE_AED \"\"VALUE_AED\"\"#(lf)FROM XXFLP_BI_GRN_DETAILS_ALL A#(lf)LEFT OUTER JOIN #(lf)(SELECT DISTINCT UNIQUE_KEY, MAX(UNIT_PRICE_AED) \"\"UNIT_PRICE_AED\"\" FROM XXFLP_BI_PO_DETAILS_ALL#(lf)GROUP BY UNIQUE_KEY )#(lf)B#(lf)ON A.PO_LINE_UNIQUE_KEY = B.UNIQUE_KEY\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}, {\"PARENT_UNIQUE_KEY\", type text}, {\"PO_UNIQUE_KEY\", type text}, {\"PO_LINE_UNIQUE_KEY\", type text}, {\"PO_SHIPMENT_UNIQUE_KEY\", type text}, {\"PO_DISTRIBUTION_UNIQUE_KEY\", type text}, {\"GRN_DATE\", type date}, {\"GRN_LAST_MODIFIED_DATE\", type date}, {\"CREATION_DATE\", type date}, {\"LAST_UPDATE_DATE\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "REQ_HEADERS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AUCTION_HEADER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b24a998d-8f09-4659-aa78-6901d101dc19",
            "sourceColumn": "AUCTION_HEADER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DOCUMENT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a4c170e-f37f-46bc-921e-85dd92c79fe3",
            "sourceColumn": "DOCUMENT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "AUCTION_TITLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e0829b5-6412-4f1a-a004-c5bde05fbc51",
            "sourceColumn": "AUCTION_TITLE",
            "summarizeBy": "none"
          },
          {
            "name": "OPEN_BIDDING_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "73404009-c757-4403-af43-0c4996b1d745",
            "sourceColumn": "OPEN_BIDDING_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "CLOSE_BIDDING_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "05a2c9e1-9871-4dcf-adbd-26d1766af6ad",
            "sourceColumn": "CLOSE_BIDDING_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "DISPLAY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51171d32-d005-422c-839f-b62643ce6c4a",
            "sourceColumn": "DISPLAY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "BU_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64d70657-be8f-467a-8bfb-ba67c7edeed0",
            "sourceColumn": "BU_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "APPROVAL_AMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee3fcd0b-fa18-4173-a4b7-6752af46f3bd",
            "sourceColumn": "APPROVAL_AMOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "ATTRIBUTE_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "062f533b-87d2-4ec7-87ff-aa53e3d13186",
            "sourceColumn": "ATTRIBUTE_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "TENDER_CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13f2bbe4-c915-47e7-b419-945030a04c0a",
            "sourceColumn": "TENDER_CATEGORY",
            "summarizeBy": "none"
          },
          {
            "name": "NEGOTIATION_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ca478c4-b28f-4596-8096-094beae6aeee",
            "sourceColumn": "NEGOTIATION_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01014a16-7093-4857-b12b-606086cb35a6",
            "sourceColumn": "CURRENCY_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_RUN_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "26458b8e-e569-4bec-9af1-be395a6e9ce7",
            "sourceColumn": "LAST_RUN_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "AUCTION_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ad55126-58f3-47cd-9e8b-dd6f3878a1f2",
            "sourceColumn": "AUCTION_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "SCORING_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7740814-640e-482f-812f-5e2eded89682",
            "sourceColumn": "SCORING_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "AWARD_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e88fd9ce-0d00-4308-9231-e3221ac9936d",
            "sourceColumn": "AWARD_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "SEALED_AUCTION_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba3b945e-b65c-451e-ab52-c4b75d045d2a",
            "sourceColumn": "SEALED_AUCTION_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "NEG_APPROVAL_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89c53ea8-8769-4ee1-b526-668b5f1bc4a9",
            "sourceColumn": "NEG_APPROVAL_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "OUTCOME_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ed1ee6d-d35f-4979-ab7c-8e88f94fec95",
            "sourceColumn": "OUTCOME_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "AWARD_APPROVAL_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "716f1004-949d-4cb4-af2b-8ced86e01679",
            "sourceColumn": "AWARD_APPROVAL_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "CREATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "d551d394-b6d0-4bf4-a728-ec0e9e1fae6b",
            "sourceColumn": "CREATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "OUTCOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "200f2bd9-ea73-4da9-abbd-241b881883b3",
            "sourceColumn": "OUTCOME",
            "summarizeBy": "none"
          },
          {
            "name": "ORIGINAL_CLOSE_BIDDING_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-Mmm-YY",
            "lineageTag": "91ea8705-f972-4323-97f6-8a5f8d17803d",
            "sourceColumn": "ORIGINAL_CLOSE_BIDDING_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "BIDDING_CLOSE_DIFF_DAYS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5a39e1ff-98e6-4e96-8a48-7c509127df4c",
            "sourceColumn": "BIDDING_CLOSE_DIFF_DAYS",
            "summarizeBy": "sum"
          },
          {
            "name": "PR_DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _PR_DEPT = CALCULATE(MAX(PR_HEADERS[DEPARTMENT]), FILTER(PR_DETAILS, PR_DETAILS[NEGOTIATION_NUMBER] = REQ_HEADERS[DOCUMENT_NUMBER]))",
              "// VAR _DEPT_NAME = LOOKUPVALUE(DIM_DEPARTMENT[DEPARTMENT_NAME], DIM_DEPARTMENT[DEPARTMENT_ID], _PR_DEPT)",
              "RETURN",
              "_PR_DEPT",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "320dc921-a702-4b22-8951-51931f9ae42d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PR_ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR _PR_ENTITY = CALCULATE(MAX(PR_DETAILS[LEISURE_FACILITY_ID]), FILTER(PR_DETAILS, PR_DETAILS[NEGOTIATION_NUMBER] = REQ_HEADERS[DOCUMENT_NUMBER]))",
              "VAR _ENT_NAME = LOOKUPVALUE(DIM_LEISURE_FACILITY[LEISURE_FACILITY], DIM_LEISURE_FACILITY[FACILITY_ID], _PR_ENTITY)",
              "RETURN",
              "_ENT_NAME",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a0f79afb-1e32-4c37-9558-5bdd79824e04",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CYCLE_TIME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _START_DATE = IF(REQ_HEADERS[OPEN_BIDDING_DATE]=BLANK(), REQ_HEADERS[CREATION_DATE], REQ_HEADERS[OPEN_BIDDING_DATE])",
              "VAR _END_DATE = REQ_HEADERS[CLOSE_BIDDING_DATE]",
              "RETURN",
              "IF(_END_DATE<>BLANK(), NETWORKDAYS(_START_DATE, _END_DATE, 1), BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "61395d48-c2d2-43b8-a071-634dc9183041",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "BASE_DOCUMENT_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16821124-17c1-4917-9933-69f55992aefd",
            "sourceColumn": "BASE_DOCUMENT_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "BASE_DOCUMENT_OR_NOT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53ba4089-eace-4920-8aac-8e5af77beab9",
            "sourceColumn": "BASE_DOCUMENT_OR_NOT",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b409d69a-68b5-488b-8e80-5160ca8d7aee",
        "partitions": [
          {
            "name": "REQ_HEADERS-2ea85e20-b956-4ac2-9622-27b7ed3f3383",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT #(lf)AUCTION_HEADER_ID,#(lf)DOCUMENT_NUMBER,#(lf)AUCTION_TITLE,#(lf)OPEN_BIDDING_DATE,#(lf)CLOSE_BIDDING_DATE,#(lf)DISPLAY_NAME,#(lf)BU_NAME,#(lf)APPROVAL_AMOUNT,#(lf)ATTRIBUTE_CATEGORY,#(lf)TENDER_CATEGORY,#(lf)DEPARTMENT \"\"NEGOTIATION_TYPE\"\",#(lf)CURRENCY_CODE,#(lf)LAST_RUN_DATE,#(lf)AUCTION_STATUS,#(lf)SCORING_STATUS,#(lf)AWARD_STATUS,#(lf)SEALED_AUCTION_STATUS,#(lf)NEG_APPROVAL_STATUS,#(lf)OUTCOME_STATUS,#(lf)AWARD_APPROVAL_STATUS,#(lf)CREATION_DATE,#(lf)OUTCOME,#(lf)ORIGINAL_CLOSE_BIDDING_DATE,#(lf)ROUND((CLOSE_BIDDING_DATE-ORIGINAL_CLOSE_BIDDING_DATE ),2) \"\"BIDDING_CLOSE_DIFF_DAYS\"\"#(lf)FROM XXMIR_PON_AUCTION_HEADERS_ALL#(lf)#(lf)\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"AUCTION_HEADER_ID\", type text}, {\"OPEN_BIDDING_DATE\", type date}, {\"CLOSE_BIDDING_DATE\", type date}, {\"LAST_RUN_DATE\", type date}, {\"CREATION_DATE\", type date}, {\"ORIGINAL_CLOSE_BIDDING_DATE\", type date}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"BU_NAME\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value1\", each not Text.StartsWith([DOCUMENT_NUMBER], \"30000\")),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows\", each ([BU_NAME] = \"Miral Experiences LLC\")),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows2\", \"DOCUMENT_NUMBER\", \"BASE_DOCUMENT_NUMBER\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Duplicated Column\",\",\",\"-\",Replacer.ReplaceText,{\"BASE_DOCUMENT_NUMBER\"}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Replaced Value\", \"BASE_DOCUMENT_NUMBER\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"BASE_DOCUMENT_NUMBER.1\", \"BASE_DOCUMENT_NUMBER.2\", \"BASE_DOCUMENT_NUMBER.3\", \"BASE_DOCUMENT_NUMBER.4\", \"BASE_DOCUMENT_NUMBER.5\"}),",
                "    #\"Merged Columns\" = Table.CombineColumns(Table.TransformColumnTypes(#\"Split Column by Delimiter\", {{\"BASE_DOCUMENT_NUMBER.3\", type text}}, \"en-US\"),{\"BASE_DOCUMENT_NUMBER.1\", \"BASE_DOCUMENT_NUMBER.2\", \"BASE_DOCUMENT_NUMBER.3\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"BASE_DOCUMENT_NUMBER\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Merged Columns\", \"BASE_DOCUMENT_OR_NOT\", each if [BASE_DOCUMENT_NUMBER.4] = null and ",
                "[BASE_DOCUMENT_NUMBER.5]=null  then \"Yes\"",
                "else \"No\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"BASE_DOCUMENT_NUMBER.4\", \"BASE_DOCUMENT_NUMBER.5\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"BASE_DOCUMENT_OR_NOT\", type text}}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Changed Type1\",\"NO\",\"NO - NOT AWARDED\",Replacer.ReplaceText,{\"AWARD_STATUS\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Replaced Value2\", {\"DOCUMENT_NUMBER\"}, REQ_HEADERS_LATEST_VERSION, {\"DOCUMENT_NUMBER\"}, \"REQ_HEADERS_LATEST_VERSION\", JoinKind.LeftOuter),",
                "    #\"Expanded REQ_HEADERS_LATEST_VERSION\" = Table.ExpandTableColumn(#\"Merged Queries\", \"REQ_HEADERS_LATEST_VERSION\", {\"DOCUMENT_NUMBER\"}, {\"DOCUMENT_NUMBER.1\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded REQ_HEADERS_LATEST_VERSION\", each ([DOCUMENT_NUMBER.1] <> null)),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"DOCUMENT_NUMBER.1\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PBI_RFP_CUST_DATE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b17ab6b9-54c3-48fc-aba0-2e0e21170767",
            "sortByColumn": "ID",
            "sourceColumn": "Names",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a515eb6-4a8f-45a7-aa0d-b183921e6274",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "059fc2c5-7648-4dd7-9ddb-6b4ded9bb4ad",
        "partitions": [
          {
            "name": "PBI_RFP_CUST_DATE-15e8160d-9ddb-46bb-964d-1a873cdb6dd5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wci5KTSzJzM9TcEksSVXSUTJUitUBiubkF2fmpcMEjZRiYwE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Names = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PO_LINES_UNIQUE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecdd1d30-527b-4a75-ab7b-6a7e2119c0c7",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "UNIT_PRICE_AED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2596ac3-d2a3-43ab-80b9-e52055b1e941",
            "sourceColumn": "UNIT_PRICE_AED",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6ac138f3-579b-4661-8ef1-b6b255efd51e",
        "partitions": [
          {
            "name": "PO_LINES_UNIQUE-a2a3d41b-9826-4165-8b63-f4bc0ef8049a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT DISTINCT UNIQUE_KEY, MAX(UNIT_PRICE_AED) \"\"UNIT_PRICE_AED\"\" FROM XXFLP_BI_PO_DETAILS_ALL#(lf)GROUP BY UNIQUE_KEY\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_YES_NO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b54dcb74-20a2-4077-ba3c-b0b5e755351f",
            "sortByColumn": "Sort_Number",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd637ecd-15a5-4a95-af1a-9bccd5907444",
            "sourceColumn": "Sort_Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "07086291-44a7-44f5-9a48-78cd0d3209cf",
        "partitions": [
          {
            "name": "DIM_YES_NO-6fa407a0-47fb-4d16-9df9-475483ad9635",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WikwtVtJRMlSK1YlW8ssHMo2UYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Sort_Number = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Category\", type text}, {\"Sort_Number\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_CATEGORIES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad793df9-9412-4292-bb32-dfb119ee4e6e",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a652840-34e1-4e6a-b5a6-1736f64b6949",
            "sourceColumn": "CATEGORY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e7e24ad7-9902-4d59-9584-cee8003ac47c",
        "partitions": [
          {
            "name": "SUPPLIER_CATEGORIES-b74de9b6-e751-4781-844f-3ed5005f0b2e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT DISTINCT UNIQUE_KEY, #(lf)ATTRIBUTE5 \"\"CATEGORY\"\"#(lf)FROM XXFLP_BI_SUPPLIERS_ALL \"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"CATEGORY\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"CATEGORY.1\", \"CATEGORY.2\", \"CATEGORY.3\", \"CATEGORY.4\", \"CATEGORY.5\", \"CATEGORY.6\", \"CATEGORY.7\", \"CATEGORY.8\", \"CATEGORY.9\", \"CATEGORY.10\", \"CATEGORY.11\", \"CATEGORY.12\", \"CATEGORY.13\", \"CATEGORY.14\", \"CATEGORY.15\", \"CATEGORY.16\", \"CATEGORY.17\", \"CATEGORY.18\", \"CATEGORY.19\", \"CATEGORY.20\", \"CATEGORY.21\", \"CATEGORY.22\", \"CATEGORY.23\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"CATEGORY.1\", type text}, {\"CATEGORY.2\", type text}, {\"CATEGORY.3\", type text}, {\"CATEGORY.4\", type text}, {\"CATEGORY.5\", type text}, {\"CATEGORY.6\", type text}, {\"CATEGORY.7\", type text}, {\"CATEGORY.8\", type text}, {\"CATEGORY.9\", type text}, {\"CATEGORY.10\", type text}, {\"CATEGORY.11\", type text}, {\"CATEGORY.12\", type text}, {\"CATEGORY.13\", type text}, {\"CATEGORY.14\", type text}, {\"CATEGORY.15\", type text}, {\"CATEGORY.16\", type text}, {\"CATEGORY.17\", type text}, {\"CATEGORY.18\", type text}, {\"CATEGORY.19\", type text}, {\"CATEGORY.20\", type text}, {\"CATEGORY.21\", type text}, {\"CATEGORY.22\", type text}, {\"CATEGORY.23\", type text}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"UNIQUE_KEY\"}, \"Attribute\", \"CATEGORY\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Unpivoted Other Columns\",{\"Attribute\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_EXPIRATION_DATE_TABLE",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "19c7f204db2f4b8382487dbb67190e83"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ca5576d7-6d74-48af-950a-924b0c8765f8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aca359d0-2048-4d48-8da4-891d991ef4e2",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "acdd2b20-804b-451b-8f4a-9ce81c6769a2",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month NO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d04315ec-8d1d-4455-93af-2fdfd0b1917c",
            "sourceColumn": "[Month NO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ShortMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0f56791f-4d91-456c-bfa4-94eaa76551d6",
            "sourceColumn": "[ShortMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "90ba9342-681f-4621-8661-ae33f0571246",
            "sortByColumn": "YearMonthNum",
            "sourceColumn": "[Year-Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d98873ed-6812-4b2e-bbb4-7a19eefa407b",
            "sourceColumn": "[YearMonthNum]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "HY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "50b220d9-5932-486b-a505-fefe6d45da29",
            "sourceColumn": "[HY]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WEEKDAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "348218cb-9654-46f2-8ea8-599c614ca410",
            "sourceColumn": "[WEEKDAY]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WEEKNUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "75bfe598-e62a-4d6b-910f-7847c8ff268b",
            "sourceColumn": "[WEEKNUM]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "02984d4d-0ae9-4451-b665-03f4958cc353",
        "partitions": [
          {
            "name": "SUPPLIER_EXPIRATION_DATE_TABLE-bbf7ef97-de71-45e1-bc99-52f36ce8c1d5",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _MIN_DATE= DATE(2021, 1, 1)",
                "VAR _TEMP_MAX_DATE = [LAST_REFRESHED_DATE]",
                "VAR _MAX_DATE= EOMONTH( _TEMP_MAX_DATE,24)",
                "RETURN",
                "ADDCOLUMNS( ",
                "CALENDAR(_MIN_DATE,_MAX_DATE),",
                "\"Year\",YEAR([Date]),",
                "\"Month\",FORMAT([Date],\"MMMM\"),",
                "\"Month NO\",MONTH([Date]),",
                "\"ShortMonth\",FORMAT([Date],\"MMM\"),",
                "\"Year-Month\",FORMAT([Date],\"MMM\") & \"-\" & FORMAT([Date],\"YY\"),",
                "\"YearMonthNum\",  INT(FORMAT([Date],\"YY\") & FORMAT([Date],\"MM\")) ,",
                "\"HY\",ROUNDUP(DIVIDE(MONTH([Date]),6),0),",
                "\"WEEKDAY\", WEEKDAY([Date], 2),",
                "\"WEEKNUM\", WEEKNUM([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "GLOSSARY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e66f0e1-c5fc-4a1c-89df-8242bc1062df",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          },
          {
            "name": "REPORT_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2b2f176-2390-4ac5-97d9-491e52d5d4bb",
            "sourceColumn": "REPORT_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "REPORT_TAB_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdb31b22-ff08-4e08-ae5e-729aba469f51",
            "sourceColumn": "REPORT_TAB_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "DEFINITION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cfc45dd-167e-47b2-9f92-7919648edc05",
            "sourceColumn": "DEFINITION",
            "summarizeBy": "none"
          },
          {
            "name": "CALCULATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db668977-a898-4ae4-bd04-d05e7871a31b",
            "sourceColumn": "CALCULATION",
            "summarizeBy": "none"
          },
          {
            "name": "POWER_BI_TABLE_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dbdb6e2-8166-4e2e-b23e-dc0cc427abaa",
            "sourceColumn": "POWER_BI_TABLE_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "PBI_COLUMN_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9c89eb4-7b8e-45f0-9c76-f05427eaa7f7",
            "sourceColumn": "PBI_COLUMN_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "FILTERS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6dee4c8-ea85-462d-a998-96569a92b4bd",
            "sourceColumn": "FILTERS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1f955f55-2e95-4a7e-b9d5-ff1abb975fc3",
        "partitions": [
          {
            "name": "GLOSSARY-8c759c25-ade1-4c08-a067-21aea54f9139",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM PBI_GLOSSARY\"]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each [REPORT_NAME] = \"Procurement Dashboard\")",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_PR_DEPARTMENT",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DEPARTMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "749a6c71-53d3-495e-8a2c-9e74bbc261b5",
            "sourceColumn": "DEPARTMENT",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8e6eedef-5ad0-4c32-9fa7-e7bb8ae50014",
        "partitions": [
          {
            "name": "DIM_PR_DEPARTMENT-3f58a499-e8cc-41ef-9eca-6950bf7a9f09",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT DISTINCT ATTRIBUTE4 FROM XXFLP_BI_PR_HEADERS_ALL #(lf)WHERE ATTRIBUTE4<>' ' AND ATTRIBUTE4 IS NOT NULL AND UPPER(SITE) = 'FARAH EXPERIENCES LLC'\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"ATTRIBUTE4\", \"DEPARTMENT\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_LICENSES",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LICENSE_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ddc9f52-861e-490e-815f-0cde095610ed",
            "sourceColumn": "LICENSE_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "LICENSE_GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0424006f-ae93-41ad-9148-0d2db175b100",
            "sourceColumn": "LICENSE_GROUP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6655a282-b571-44b0-a175-78fad6347143",
        "partitions": [
          {
            "name": "DIM_LICENSES",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT * FROM DIM_LICENSES ORDER BY 2 DESC\"]),",
                "    #\"Trimmed Text\" = Table.TransformColumns(Source,{{\"LICENSE_NAME\", Text.Trim, type text}, {\"LICENSE_GROUP\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SUPPLIER_SITE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "UNIQUE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dda2a758-610d-4d82-8b8b-8b3769781b48",
            "sourceColumn": "UNIQUE_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6391cea-763d-48e1-a67d-310c102e8526",
            "sourceColumn": "VENDOR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_SITE_CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acb94f8b-eec9-402a-b21c-ed5d3800fd60",
            "sourceColumn": "VENDOR_SITE_CODE",
            "summarizeBy": "none"
          },
          {
            "name": "ADVANCE_PAYMENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3f245230-f07b-4306-9195-9bb71039431d",
            "sourceColumn": "ADVANCE_PAYMENT",
            "summarizeBy": "sum"
          },
          {
            "name": "AMOUNT_REMAINING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8d1de378-50f0-4e6b-82c8-7e948149509e",
            "sourceColumn": "AMOUNT_REMAINING",
            "summarizeBy": "sum"
          },
          {
            "name": "INVITING_PROCUREMENT_BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6248c754-1b7f-4cbf-bae7-ae01b7e5f040",
            "sourceColumn": "INVITING_PROCUREMENT_BU",
            "summarizeBy": "none"
          },
          {
            "name": "SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc4d119f-5b4e-4c59-8619-4505fbb45cca",
            "sourceColumn": "SITE",
            "summarizeBy": "none"
          },
          {
            "name": "REGISTRATION_ENTITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89c3a597-3275-4a69-8574-9fbaf1decafc",
            "sourceColumn": "REGISTRATION_ENTITY",
            "summarizeBy": "none"
          },
          {
            "name": "VENDOR_SITE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a83179d9-9fda-4433-843d-fe3433b8d0ac",
            "sourceColumn": "VENDOR_SITE_ID",
            "summarizeBy": "count"
          },
          {
            "name": "MIRAL_EXT_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68decf31-52dd-4750-a351-76a95446f8fc",
            "sourceColumn": "MIRAL_EXT_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "SITE_STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad8cc506-36f9-4837-9bf0-0a7fd0e53134",
            "sourceColumn": "SITE_STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "INACTIVE SITE DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d00ef05a-86fc-44fb-9512-0e12339b3c2d",
            "sourceColumn": "INACTIVE SITE DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dadd70d0-494d-4ab4-b2a2-5448e4f4bf11",
        "partitions": [
          {
            "name": "SUPPLIER_SITE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "    Source = Oracle.Database(SERVER_NAME, [HierarchicalNavigation=true, Query=\"SELECT#(lf)UNIQUE_KEY,#(lf)VENDOR_NUMBER,#(lf)VENDOR_SITE_CODE,#(lf)OBSOLETE_FROM \"\"INACTIVE SITE DATE\"\" ,#(lf)ADVANCE_PAYMENT,#(lf)AMOUNT_REMAINING,#(lf)ATTRIBUTE4 \"\"INVITING_PROCUREMENT_BU\"\",#(lf)SITE,#(lf)REGISTRATION_ENTITY,#(lf)VENDOR_SITE_ID,#(lf)CASE #(lf)WHEN OBSOLETE IS NULL AND OBSOLETE_FROM > SYSDATE THEN 'Active'#(lf)WHEN OBSOLETE IS NULL AND OBSOLETE_FROM <= SYSDATE THEN 'Inactive'#(lf)WHEN OBSOLETE IS NULL AND OBSOLETE_FROM IS NULL THEN 'Active'#(lf)WHEN OBSOLETE='Yes' then 'Inactive'#(lf)WHEN OBSOLETE='No' then 'Active'#(lf)ELSE OBSOLETE#(lf)END SITE_STATUS#(lf)FROM XXFLP_BI_SUPPLIERS_ALL#(lf)--WHERE TAX_ORGANIZATION_TYPE <> 'EMPLOYEE'\"]),",
                "",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}}),",
                "",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"SITE\", \"INVITING_PROCUREMENT_BU\", \"REGISTRATION_ENTITY\"}),",
                "",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"MIRAL_EXT_FLAG\", each if [REGISTRATION_ENTITY] = \"Miral Experiences LLC\" or ([REGISTRATION_ENTITY]<> null and Text.StartsWith([REGISTRATION_ENTITY], \"Experiences Hub\")) then 1 else if [INVITING_PROCUREMENT_BU] = \"Miral Experiences LLC\" or ([INVITING_PROCUREMENT_BU]<> null and Text.StartsWith([INVITING_PROCUREMENT_BU], \"Experiences Hub\")) then 1 else if [SITE] = \"Miral Experiences LLC\" or( [SITE]<> null and Text.StartsWith([SITE], \"Experiences Hub\")) then 1 else 0),",
                "",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"MIRAL_EXT_FLAG\", Int64.Type}})",
                "",
                "in",
                "",
                "    #\"Changed Type1\"",
                "    ",
                "// let",
                "//     Source = Oracle.Database(#\"SERVER_NAME(UAT)\", [HierarchicalNavigation=true, Query=\"SELECT#(lf)UNIQUE_KEY,#(lf)VENDOR_NUMBER,#(lf)VENDOR_SITE_CODE,#(lf)OBSOLETE_FROM \"\"INACTIVE SITE DATE\"\",#(lf)ADVANCE_PAYMENT,#(lf)AMOUNT_REMAINING,#(lf)ATTRIBUTE4 \"\"INVITING_PROCUREMENT_BU\"\",#(lf)SITE,#(lf)REGISTRATION_ENTITY,#(lf)VENDOR_SITE_ID,#(lf)CASE WHEN OBSOLETE='Yes' then 'Inactive'#(lf)WHEN OBSOLETE='No' then 'Active'#(lf)END SITE_STATUS#(lf)FROM XXFLP_BI_SUPPLIERS_ALL#(lf)--WHERE TAX_ORGANIZATION_TYPE <> 'EMPLOYEE'\"]),",
                "//     #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UNIQUE_KEY\", type text}, {\"VENDOR_SITE_ID\", type text}}),",
                "//     #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Farah Experiences LLC\",\"Miral Experiences LLC\",Replacer.ReplaceText,{\"SITE\", \"INVITING_PROCUREMENT_BU\", \"REGISTRATION_ENTITY\"}),",
                "//     #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"MIRAL_EXT_FLAG\", each if [REGISTRATION_ENTITY] = \"Miral Experiences LLC\" then 1 else if [INVITING_PROCUREMENT_BU] = \"Miral Experiences LLC\" then 1 else if [SITE] = \"Miral Experiences LLC\" then 1 else 0),",
                "//     #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"MIRAL_EXT_FLAG\", Int64.Type}})",
                "// in",
                "//     #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}